### PR TITLE
ci: add sync test workflow

### PR DESCRIPTION
**Pull request by annieke**
**Description**
The sync tests add too much time both when running in parallel and sequentially with integration tests. before we have better caching, this separate workflow is the solution. 

**Additional context**
decoupling from https://github.com/ethereum-optimism/optimism/pull/981 since i'm having issues bringing a replica up.

**Metadata**
- https://github.com/ethereum-optimism/optimism/issues/604

### CODE REVIEW

**Review by tynes — APPROVED** [review]
I see that the sync tests pass

**Comment by tynes** [comment]
The sync tests should be a subdirectory inside of tests because it imports things from `tests/shared`. There should be `tests/{shared,sync,integration}` and then the different npm command will target the subdirectories with a glob

**Comment by annieke** [comment]
@tynes agreed it should be moved there! but these currently error when ran in docker along-side other tests, so i could tweak the test script or put back in when verifier tests are fixed - thoughts?

**Comment by gakonst** [comment]
Instead of bringing up the replicas or the verifiers INSIDE docker, you can just bring them up by running `docker-compose up --scale <...>=1` in the step before running the integration tests.

**Review by gakonst — APPROVED** [review]

**Pull request merged**
