### PR TITLE
alt-da: remove unused error handling

### PR DESCRIPTION
**Pull request by qzhodl**
**Description**

The `GetInput` function of `s.fetcher` never returns an `ErrReorgRequired` error, so we can remove the handling for this error type.

### CODE REVIEW

**Comment by tynes** [comment]
This needs a rebase for new CI jobs that were added. Also tagging @samlaf here for review

**Review by samlaf — COMMENTED** [review]
Seems true to me. Tried quickly looking through previous PRs for where the ErrReorgRequired was removed from GetInput but couldn't find anything.

**Comment by qzhodl** [comment]
> This needs a rebase for new CI jobs that were added. Also tagging @samlaf here for review

Sure, I’ve merged the latest changes

**Comment by samlaf** [comment]
@qzhodl Im not a member of this repo, you should request review from someone on the team. Maybe @sebastianst ?

**Review by sebastianst — COMMENTED** [review]
I've confirmed that the `altda.ErrReorgRequired` error only bubbles up in the callstack of `DA.AdvanceL1Origin` so removing it for the `GetInput` call looks fine to me.

Is it guaranteed that this error won't be returned by `GetInput` in the future?

cc @qzhodl @samlaf

**Comment by samlaf** [comment]
@qzhodl mistake?

**Comment by qzhodl** [comment]
> @qzhodl mistake?

Oh, yes, I didn’t realize the repo still has unmerged PRs...

**Pull request closed without merging**
