### PR TITLE
op-challenger: clarify the output

### PR DESCRIPTION
**Pull request by DenseDenise**
For my first time to use `./bin/op-challenger list-claims`
The data name really confuses me, after I check the spces, I found the index means for Trace_Index, we should clarify it. And the parent for the root shouldn't be `NIL`, Because of the missing data, I mistakenly thought that `Parent Depth` was a whole data, not two data.

### CODE REVIEW

**Review by ajsutton — CHANGES_REQUESTED** [review]
These longer names aren't currently reflected din the `lineFormat` above to ensure the columns line up.  The names are deliberately quite succinct to keep the output to a reasonable line length so it can display well in most terminals so I'd rather not increase them.  You need a pretty good understanding of dispute games to be able to understand this output anyway.

Also not sure why spaces in titles are being replaced by `_`.

**Comment by DenseDenise** [comment]
image
image

The reason for adding the hyphen is that without it, attributes with spaces in the middle can easily be misunderstood as two separate attributes rather than one whole attribute. As for the alignment, the arrangement on my CLI is basically the same as before, so there shouldn't be any misalignment. As shown in the picture. @ajsutton

**Comment by ajsutton** [comment]
ah yeah I can see the new names still fit within the allocated space so the line format doesn't need changing.  I'm definitely not a fan of adding in underscores - they just add more visual clutter.  I'd also keep `Value` instead of `Claim Value` since all of the values are clearly from the claim.  

I would also suggest just using `Trace` instead of `Trace Index` to keep it shorter - the values make it clear that it's a trace index.  And a `-` instead of `N/A` for the root parent would reduce clutter a lot.

**Comment by DenseDenise** [comment]
> ah yeah I can see the new names still fit within the allocated space so the line format doesn't need changing. I'm definitely not a fan of adding in underscores - they just add more visual clutter. I'd also keep `Value` instead of `Claim Value` since all of the values are clearly from the claim.
> 
> I would also suggest just using `Trace` instead of `Trace Index` to keep it shorter - the values make it clear that it's a trace index. And a `-` instead of `N/A` for the root parent would reduce clutter a lot.

Make sense. updated now

**Review by ajsutton — APPROVED** [review]
Thanks.

**Pull request merged**
