### PR TITLE
op-challenger: Handle Reader reading data and returning EOF in the same call

### PR DESCRIPTION
**Pull request by ajsutton**
**Description**

This is an unusual but valid corner case of io.Reader. Special handling is required to ensure that the state commitment is captured both before and after the last, padding only block. With a `Reader` that only returns `io.EOF` in the call _after_ the last data is read, the state commitments are automatically captured but for safety we should ensure we handle both possibilities.

**Additional context**

Builds on https://github.com/ethereum-optimism/optimism/pull/9166

**Metadata**

- https://github.com/ethereum-optimism/client-pod/issues/480

### CODE REVIEW

**Review by Inphi — APPROVED** [review]
oof! Good fix!

**Comment by refcell** [comment]
I think we unintentionally wanted the original `io.Reader` behavior here. If the preimage data size is exactly 136 byte aligned (a whole number of leafs), the contracts expect one additional leaf of padding. Since the io.Reader only returned _after_ EOF, this did return the additional empty padded leaf data prior to this pr. cc @clabby for visibility

**Comment by ajsutton** [comment]
> I think we unintentionally wanted the original `io.Reader` behavior here. If the preimage data size is exactly 136 byte aligned (a whole number of leafs), the contracts expect one additional leaf of padding. Since the io.Reader only returned _after_ EOF, this did return the additional empty padded leaf data prior to this pr. cc @clabby for visibility

Yes, we were getting the correct behaviour by accident because we always used `bytes.NewReader` which only returns `0, EOF`. This is a defensive change to ensure that we also get the right behaviour even if we're given a reader that does return EOF in the same call that it read data.  Note that in production code we still always use `bytes.NewReader` - the custom reader is only used in tests to ensure the code works with the full range of allowed behaviour from Read.

**Review by refcell — APPROVED** [review]
Ah I understand, this looks great!

**Review by refcell — APPROVED** [review]

**Pull request merged**
