### PR TITLE
fix(l2geth): revert rpcGasCap logic to upstream geth behavior

### PR DESCRIPTION
**Pull request by timmyers**
**Description**
Fixes the `rpcGasCap` logic by reverting to the upstream geth behavior:
https://github.com/ethereum/go-ethereum/blob/v1.9.10/internal/ethapi/api.go#L807

**Additional context**
This was erroneously loading the value of `MinerGasLimitFlag` and using that for the rpc gas limit, which is a much lower value.

### CODE REVIEW

**Comment by timmyers** [comment]
Whoops, will revert the auto formatted diffs.

**Comment by karlfloersch** [comment]
@tynes -- is this change safe? I am not entirely sure without diving deeper what the downstream impacts are here if there are any.

**Comment by tynes** [comment]
> @tynes -- is this change safe? I am not entirely sure without diving deeper what the downstream impacts are here if there are any.

Seeing as it is in upstream geth, it should be fine. This change will allow `eth_call` to execute with more gas in the case when `tx.gasLimit` is not specified and is useful for querying `pure`/`view` functions. We do not currently use the RPC Gas Cap config option so that is `nil` in this code path. It should not impact `eth_estimateGas` as the `eth_call` `gas` value is specified during the binary search.

**Review by tynes — APPROVED** [review]

**Comment by tynes** [comment]
I've opened https://github.com/ethereum-optimism/optimism/pull/1279 and will merge it once it passes CI, this was done to rebase the `develop` branch instead of merging the `develop` branch

**Comment by tynes** [comment]
Merged in https://github.com/ethereum-optimism/optimism/pull/1285

**Pull request closed without merging**
