### PR TITLE
docs: add truffle example + ci

### PR DESCRIPTION
**Pull request by platocrat**
**Description**
Adds [Truffle-ERC20-Example](https://github.com/ethereum-optimism/Truffle-ERC20-Example) repository to monorepo.

**Additional context**
Related to #641 and #665. Need estimateGas issue to be resolved before #665 and this PR can be merged.

### CODE REVIEW

**Comment by gakonst** [comment]
Blocked on https://github.com/trufflesuite/truffle/issues/4000#issuecomment-829501411.

**Comment by platocrat** [comment]
@gakonst It looks like Mark's recent changes in #721 fixed our Truffle issue.

From the comment I made in https://github.com/ethereum-optimism/optimism/issues/664#issuecomment-832293814, Truffle tests pass when you hardcode `gasPrice` to 0 everywhere.

**Comment by platocrat** [comment]
@gakonst I'm unsure how to resolve these conflicts. Do you think you could handle this one?

**Comment by smartcontracts** [comment]
> @gakonst I'm unsure how to resolve these conflicts in the `yarn.lock` file.
> Do you think you could handle this one?

I gotcha

**Review by smartcontracts — APPROVED** [review]

**Comment by gakonst** [comment]
I think that the unsafe bytecode error may be a false positive? Not sure.

**Comment by platocrat** [comment]
Solved the issue with "installing" `@eth-optimism/solc`.
In places where I imported packages from `node_modules`, I walked up to the top-level `node_modules` to import from there.

E.g. I changed this:
```js
version: "node_modules/@eth-optimism/solc",
```
to this
```js
version: "../../node_modules/@eth-optimism/solc",
```
and this:
```js
const HDWalletProvider = require('@truffle/hdwallet-provider')
```
to this
```js
const HDWalletProvider = require('../../node_modules/@truffle/hdwallet-provider')
```

Now, I still receive this error: 
```
Error: while migrating ERC20: invalid transaction: invalid sender
```

So, I think this means that the migrations file is not properly specifying a sender address.
Although, I'm not sure why this is becoming an issue while under the monorepo and not while under the external repo.

**Pull request merged**
