### PR TITLE
Remove unused variables from contracts-bedrock

### PR DESCRIPTION
**Pull request by protocolwhisper**
**Description**

Deleted unused variables sendImpersonatedTx and FundAccount, cause they slipped in a recent PR

**Tests**

There was no test for deleting unused variables

**Metadata**
- Fixes #https://github.com/ethereum-optimism/optimism/issues/3838

### CODE REVIEW

**Comment by protocolwhisper** [comment]
Updated Changeset

**Comment by tynes** [comment]
Confirming that only dependencies are removed from looking at the `yarn.lock`

**Review by tynes — APPROVED** [review]

**Review by smartcontracts — APPROVED** [review]

**Comment by maurelian** [comment]
Why does this have a yarn.lock diff at all? @smartcontracts just merged another PR that modified it b3dc2e69ed0dea6a5b22667cf4d2df3cf2e6b78a.

**Comment by protocolwhisper** [comment]
Oh, it was committed 5 hours ago.
Want me to pull a new pull request with that pr merged?

**Comment by protocolwhisper** [comment]
I just make another PR with the branch updated https://github.com/ethereum-optimism/optimism/pull/4003

**Pull request closed without merging**
