### PR TITLE
test: always run sync tests

### PR DESCRIPTION
**Pull request by gakonst**
Enables running the sync tests introduced in #913 on CI by moving them under the `test/` directory.

### CODE REVIEW

**Comment by platocrat** [comment]
i'm updating the branch here

**Comment by tynes** [comment]
I like the idea but it looks like the path to the `docker-compose.yml` is incorrect

**Review by annieke — COMMENTED** [review]
this is where i want to eventually move to! i think 2 issues right now:
1. running the tests in docker also gives me this `spawn docker-compose ENOENT` error locally, which i think is from trying to use docker-compose within docker. haven't tried too hard to debug it, because
2. sync tests will always fail when ran with integration tests right now, since erc20 deploys + transfers produce mismatched stateroots
so as of now the simplest way is still to run sync tests in their own workflow, i'll try out the other solution to see if it's faster https://github.com/ethereum-optimism/optimism/pull/972#issuecomment-852133053

**Comment by gakonst** [comment]
Closing given Annie is on it. I think we should figure out what causes the mismatched state roots before enabling the tests (independently of having it in the same or other workflow, since otherwise the test would give us false confidence)

**Pull request closed without merging**
