### PR TITLE
l2geth: allow for the configured max tx gaslimit to be set in the cfg

### PR DESCRIPTION
**Pull request by tynes**
**Description**
This PR allows the configured gasLimit to be passed through to the contracts state. It was previously depending on the state dump to set the gasLimit in the contracts while the configured value must match the value set in the state dump

**Additional context**
If this value is misconfigured, it will result in a mismatched state root instantly. I suppose that is better than it eventually resulting in a mismatched state root if it was configured improperly.

I found the storage slot with the command:

```
$ seth storage 0xdeaddeaddeaddeaddeaddeaddeaddeaddead0005 4
```

After bringing up `l2geth` with the sync service turned off

You can see that the value is set here in the state dump: https://github.com/ethereum-optimism/optimism/blob/52d9e6b73362a203bdae3fa0182bd6e7c9693b13/packages/contracts/src/contract-dumps.ts#L118
The value that is being set in the state dynamically is here: https://github.com/ethereum-optimism/optimism/blob/52d9e6b73362a203bdae3fa0182bd6e7c9693b13/packages/contracts/contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol#L49

The gaslimit can be configured with: `TARGET_GAS_LIMIT` or `--miner.gastarget` and `--miner.gaslimit`
See:
- https://github.com/ethereum-optimism/optimism/blob/52d9e6b73362a203bdae3fa0182bd6e7c9693b13/l2geth/cmd/utils/flags.go#L455
- https://github.com/ethereum-optimism/optimism/blob/52d9e6b73362a203bdae3fa0182bd6e7c9693b13/l2geth/cmd/utils/flags.go#L441

### CODE REVIEW

**Comment by smartcontracts** [comment]
Also; does this need a changeset?

**Comment by tynes** [comment]
> Were we making use of `TARGET_GAS_LIMIT` previously? I'm concerned that we might accidentally set this value to something different than `ExecutionManager.maxTransactionGasLimit`. Is there something we can do to prevent shooting ourselves in the foot here?

This PR overwrites the value from the state dump, we currently have nothing stopping us from using the configured value from differing from the value in the state dump. This is technically safer than before because the values could differ. The remaining problem is that there is a transaction gas limit in the CTC as well that is used to meter L1 to L2 transactions that may be different than the gas limit in the execution manager. There really should be only 1 gas limit config option and setting it in geth is the most flexible.

> Also; does this need a changeset?

This does need a changeset, I was on the fence of whether or not this PR should actually get merged as it was put together to help debug other issues. Now I'd like it to be merged so I will add a changeset.

The remaining question for me is should the value also be used to set the value in the CTC?
https://github.com/ethereum-optimism/optimism/blob/52d9e6b73362a203bdae3fa0182bd6e7c9693b13/packages/contracts/contracts/optimistic-ethereum/OVM/chain/OVM_CanonicalTransactionChain.sol#L59

**Comment by tynes** [comment]
I've added a changeset, the last remaining question is if the same env var should set the storage slot in the CTC as well

**Comment by tynes** [comment]
It sounds like we will not be setting the CTC storage slot - this must be fixed at the contract level

**Review by smartcontracts — APPROVED** [review]

**Pull request merged**
