### PR TITLE
chore: small fix in op-alt-da

### PR DESCRIPTION
**Pull request by Gmanboy**
fix some typos in alt-da

### CODE REVIEW

**Comment by Gmanboy** [comment]
rebased and please have a review @tynes

**Review by smartcontracts — APPROVED** [review]

**Comment by smartcontracts** [comment]
Heyo @Gmanboy sorry for the delay here, please rebase one last time and then I can merge

**Comment by Gmanboy** [comment]
rebased @smartcontracts

**Comment by smartcontracts** [comment]
Merging! Thanks

**Pull request merged**
