### PR TITLE
ci: `ci-builder:0.49.0`

### PR DESCRIPTION
**Pull request by tynes**
**Description**

Includes a bump of slither

https://github.com/ethereum-optimism/optimism/pull/10411

### CODE REVIEW

**Comment by trianglesphere** [comment]
@tynes slither seems to be failing in GH Actions

**Comment by tynes** [comment]
Same error as before

```
[-] SARIF output enabled, writing to results.sarif.
[-] Slither config provided: packages/contracts-bedrock/slither.config.json
[-] SLITHERARGS provided. Running slither with extra arguments
'forge clean' running (wd: /github/workspace/packages/contracts-bedrock)
'forge config --json' running
'forge build --build-info --skip */test/** */scripts/** --force' running (wd: /github/workspace/packages/contracts-bedrock)
Traceback (most recent call last):
  File "/opt/slither/bin/slither", line 8, in <module>
    sys.exit(main())
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 753, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 859, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 107, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 80, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/opt/slither/lib/python3.9/site-packages/slither/slither.py", line 156, in __init__
    sol_parser.parse_top_level_items(ast, path)
  File "/opt/slither/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 326, in parse_top_level_items
    get_imported_scope = self.compilation_unit.get_scope(import_directive.filename)
  File "/opt/slither/lib/python3.9/site-packages/slither/core/compilation_unit.py", line 282, in get_scope
    filename = self._crytic_compile_compilation_unit.crytic_compile.filename_lookup(
  File "/opt/slither/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 283, in filename_lookup
    raise ValueError(f"{filename} does not exist")
ValueError: lib/openzeppelin-contracts/contracts/utils/Context.sol does not exist
```

**Comment by trianglesphere** [comment]
> Same error as before
> 
> ```
> [-] SARIF output enabled, writing to results.sarif.
> [-] Slither config provided: packages/contracts-bedrock/slither.config.json
> [-] SLITHERARGS provided. Running slither with extra arguments
> 'forge clean' running (wd: /github/workspace/packages/contracts-bedrock)
> 'forge config --json' running
> 'forge build --build-info --skip */test/** */scripts/** --force' running (wd: /github/workspace/packages/contracts-bedrock)
> Traceback (most recent call last):
>   File "/opt/slither/bin/slither", line 8, in <module>
>     sys.exit(main())
>   File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 753, in main
>     main_impl(all_detector_classes=detectors, all_printer_classes=printers)
>   File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 859, in main_impl
>     ) = process_all(filename, args, detector_classes, printer_classes)
>   File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 107, in process_all
>     ) = process_single(compilation, args, detector_classes, printer_classes)
>   File "/opt/slither/lib/python3.9/site-packages/slither/__main__.py", line 80, in process_single
>     slither = Slither(target, ast_format=ast, **vars(args))
>   File "/opt/slither/lib/python3.9/site-packages/slither/slither.py", line 156, in __init__
>     sol_parser.parse_top_level_items(ast, path)
>   File "/opt/slither/lib/python3.9/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 326, in parse_top_level_items
>     get_imported_scope = self.compilation_unit.get_scope(import_directive.filename)
>   File "/opt/slither/lib/python3.9/site-packages/slither/core/compilation_unit.py", line 282, in get_scope
>     filename = self._crytic_compile_compilation_unit.crytic_compile.filename_lookup(
>   File "/opt/slither/lib/python3.9/site-packages/crytic_compile/crytic_compile.py", line 283, in filename_lookup
>     raise ValueError(f"{filename} does not exist")
> ValueError: lib/openzeppelin-contracts/contracts/utils/Context.sol does not exist
> ```

Confirmed. This PR lgtm, but we do need to look into this bug

**Review by trianglesphere — APPROVED** [review]

**Comment by tynes** [comment]
@mds1 - thoughts on this slither issue?

**Comment by 0xalpharush** [comment]
I suspect this is related to https://github.com/foundry-rs/foundry/pull/7822

**Comment by mds1** [comment]
If this doesn't resolve the issue, let's also try a new CI builder image that bumps to the latest foundry per @0xalpharush's comment. We're on a nightly from Apr 21, so seems likely we're susceptible to the foundry-compilers issue

**Comment by 0xalpharush** [comment]
@mds1 To be clear, I think an older version of Foundry would need to be pinned since I think that PR introduced a bug. The one used in ci-builder appears to be older than the PR so it should work. Currently, slither-action fetches the latest foundry version with `foundryup`

@elopez is [drafting](https://github.com/crytic/slither-action/tree/dev-pin-foundry) the ability to pin a foundry version in slither-action and said:
> they’d need to use: crytic/slither-action@dev-pin-foundry and pass the foundry-version  as you would to foundryup -v (I think it’s one of their github release names like nightly-xyz?)

**Comment by mds1** [comment]
I thought you were suggesting https://github.com/foundry-rs/foundry/issues/7797 is the problem, which was closed by https://github.com/foundry-rs/foundry/pull/7822. But I think you are saying https://github.com/foundry-rs/foundry/pull/7822 introduced a bug?

Pinning foundry in slither action is ideal in either case, so we can ensure it matches the version we specify in [`versions.json`](https://github.com/ethereum-optimism/optimism/blob/29c7b445e17763aee0e73676e19053d08e712821/versions.json#L3)

**Pull request merged**
