### PR TITLE
`chain-mon` restructuring 

### PR DESCRIPTION
**Pull request by Ethnical**
**Description**
Restructuring `Chain-mon` with the new architecture and pass the test accordingly.

### CODE REVIEW

**Review by raffaele-oplabs — CHANGES_REQUESTED** [review]
ops/docker/Dockerfile.packages
would needs to change according to the new structure of the folders.

**Review by zhwrd — APPROVED** [review]
initialized-upgraded-mon should potentially be an internal service, as it was developed recently and is used internally, cc @zchn 

but otherwise lgtm

**Comment by zchn** [comment]
> initialized-upgraded-mon should potentially be an internal service, as it was developed recently and is used internally, cc @zchn
> 
> but otherwise lgtm

Sgtm

**Comment by zchn** [comment]
> > initialized-upgraded-mon should potentially be an internal service, as it was developed recently and is used internally, cc @zchn
> > but otherwise lgtm
> 
> Sgtm

Also need to update the code owner path for balance mon and add initialized-upgraded-mon unless it is owned by security : https://github.com/ethereum-optimism/optimism/blob/613e5dc47817bcb19de03c995d6c4dd4d37dad18/.github/CODEOWNERS#L3

**Review by raffaele-oplabs — APPROVED** [review]

**Pull request merged**
