### PR TITLE
Forkmode support in dockerized infrastructure

### PR DESCRIPTION
**Pull request by krzkaczor**
**Description**
Add a possibility to easily run a dockerized optimism from a given point of mainnet (forkmode) rather than running with a fresh state. 

**Additional context**
There is also a fix for misconfiguration of batch_submitter(?) included. It seems like a pkey for bonder is wrong. This might not be a root cause of the issue (perhaps the deployer sets it incorrectly?) but I didn't have time to inspect further.

### CODE REVIEW

**Comment by tynes** [comment]
Something doesn't seem right here as the batch submitter was updated to throw an error if the same key is used for both the proposer and sequencer. see:

https://github.com/ethereum-optimism/optimism/blob/b9ee2d7f01cc82c5b696252ad23b6f4b6098574d/packages/batch-submitter/src/exec/run-batch-submitter.ts#L361-L365

**Comment by tynes** [comment]
Thanks for the PR, going to merge in the same config as part of https://github.com/ethereum-optimism/optimism/pull/1879

**Comment by tynes** [comment]
If you run into the same problem with the config of the proposer, try rebuilding the containers from scratch. If that config was off, then the integration tests would be failing

**Comment by krzkaczor** [comment]
> If you run into the same problem with the config of the proposer, try rebuilding the containers from scratch. If that config was off, then the integration tests would be failing

Yes 🤦 This is I think what happened. I rebuilt *some* of the images. Sorry, I was on holidays and didn't have time to drop that commit.

Thanks for merging!

**Pull request closed without merging**
