### PR TITLE
Contracts-bedrock: put hardhat tasks in /tasks folder

### PR DESCRIPTION
**Pull request by cyborgdennett**
**Description**

I moved tasks from hardhat.config.ts to their own files in /tasks

Thanks to @smartcontracts for increasing my commit score 💯  #3777

### CODE REVIEW

**Review by tynes — APPROVED** [review]

**Review by maurelian — APPROVED** [review]

**Comment by maurelian** [comment]
Trying the old pull and push to get [these tests working](https://app.circleci.com/pipelines/github/ethereum-optimism/optimism?branch=contracts_bedrock%2Fhardhat_tasks). 🤞

**Comment by trianglesphere** [comment]
I'm pulling this from the merge train. @mslipper `op-*-publish-dev` are dependencies for `hive-test-*` & the hive tests are required but the publish ones are not. We should probably make the publish ones required or somehow fail the hive tests fast.

**Comment by tynes** [comment]
Bump @trianglesphere on progress here

**Comment by trianglesphere** [comment]
> Bump @trianglesphere on progress here

@mslipper did you check on this? If merges/rebases aren't fixing the publish step, do we need to ignore the check? It feels like there might be a permission issue with publishing / authenticating here.

**Pull request merged**
