### PR TITLE
maint(ct): clean up periphery deploy script

### PR DESCRIPTION
**Pull request by smartcontracts**
Cleans up the deploy script for periphery contracts. Script was a bit messy and we need a cleaned up version so that we can safely deploy and manage Drippie for the Challenger.

### CODE REVIEW

**Comment by tynes** [comment]
This generally looks good to me but no test coverage

**Comment by smartcontracts** [comment]
> This generally looks good to me but no test coverage

Yeah, I don't think this file has any test coverage at all. What do you think is the best way to add coverage?

**Review by refcell — APPROVED** [review]
Very very nice cleanup.

It's a bit difficult to be sure I caught everything in my review since there isn't a good way to establish test coverage.

**Comment by refcell** [comment]
I wonder if we could use interfaces to assert the behavior of at least a portion of the functions in the script.

**Comment by tynes** [comment]
> > This generally looks good to me but no test coverage
> 
> Yeah, I don't think this file has any test coverage at all. What do you think is the best way to add coverage?

An easy way would be to use the deploy script to set up the contracts for their unit tests

**Review by tynes — APPROVED** [review]

**Pull request merged**
