### PR TITLE
docs: add l1-l2-deposit-withdrawal

### PR DESCRIPTION
**Pull request by platocrat**
**Description**
Add [`l1-l2-deposit-withdrawal`](https://github.com/ethereum-optimism/l1-l2-deposit-withdrawal) repository to monorepo.

### **Additional context**
_Still need to add tests for deployments and message passing_

### CODE REVIEW

**Comment by platocrat** [comment]
@gakonst I cannot compile `L2DepositedERC20.sol` due to `yarn` not allowing me to install `@eth-optimism/contracts` (will not show up in my `node_modules`) to import `Abs_L2DepositedToken.sol`.

Hardhat also does not allow imports outside of the project directory where the hardhat config file being run.

**Comment by platocrat** [comment]
@gakonst not sure why your integration tests are timing out here

**Comment by platocrat** [comment]
# UPDATE
IT PASSES
@gakonst

**Review by gakonst — APPROVED** [review]
LGTM, it may be worth splitting the examples testing in a separate github workflow to reduce CI times, as they've become long.

**Comment by platocrat** [comment]
> LGTM, it may be worth splitting the examples testing in a separate github workflow to reduce CI times, as they've become long.

I'll start this another PR

**Pull request merged**
