### PR TITLE
update: security checks on go modules

### PR DESCRIPTION
**Pull request by adriang-90**
**Description**
As everybody knows security is a big deal in crypto. I did a [Trivy](https://github.com/aquasecurity/trivy) security checks and it found a lot of CVEs in go modules. I updated them with ``` replace ``` command.

### CODE REVIEW

**Comment by tynes** [comment]
This is going to need careful review before merge

**Comment by tynes** [comment]
This would be much easier to merge if it was broken up into smaller PRs that targeted individual services + didn't use `replace`

**Comment by adriang-90** [comment]
I can do that. So we can close this PR?

**Comment by adriang-90** [comment]
> I can do that. So we can close this PR?

Closing and opening splitted ones.

**Pull request closed without merging**
