### PR TITLE
op-e2e: Capture tx trace when receipt has an unexpected status

### PR DESCRIPTION
**Pull request by ajsutton**
**Description**

Update the `WaitForReceipt` function to automatically capture the output of `debug_traceTransaction` if the receipt doesn't have the expected status and add it to the resulting error message.

This will provide more context to debug flaky e2e tests (in particular trying to understand why dispute game creation sometimes fails).

The wait utils got moved out of op-e2e into op-service so they could be reused by indexer tests without also inheriting the op-e2e init code. The second commit moves them to a new `wait` module under `op-e2e/e2eutils` to make it clear that these are test utilities, not intended for production code. The resulting renames are the majority of changes in this PR but seems worth it to avoid production code depending on something that suddenly calls `debug_traceTransaction`...

**Metadata**

- https://linear.app/optimism/issue/CLI-4306/cannon-e2e-tests

### CODE REVIEW

**Comment by ajsutton** [comment]
ugh, indexer docker build for some reason needs the wait package.  Not sure if its actually being used in production code or not so marking as draft and I'll dig into the usages further to work out the best options.

**Comment by trianglesphere** [comment]
> ugh, indexer docker build for some reason needs the wait package. Not sure if its actually being used in production code or not so marking as draft and I'll dig into the usages further to work out the best options.

There's a new conflict, but tests did seem to pass. The changes look good to me, so if you can figure out the indexer thing I'm happy to merge this.

**Comment by ajsutton** [comment]
> > ugh, indexer docker build for some reason needs the wait package. Not sure if its actually being used in production code or not so marking as draft and I'll dig into the usages further to work out the best options.
> 
> There's a new conflict, but tests did seem to pass. The changes look good to me, so if you can figure out the indexer thing I'm happy to merge this.


Yeah I fixed the indexer build before marking it ready to review. There were a couple of test functions for waiting for withdrawals in op-node production code so needed to move them to the new wait module too.

Conflicts are now resolved so this should be good to go.

**Review by trianglesphere — APPROVED** [review]

**Review by mslipper — APPROVED** [review]

**Review by roninjin10 — APPROVED** [review]

**Comment by roninjin10** [comment]
Any way this pr and/or something I"m doing wrong could be causing `tx trace unavailable: websocket: read limit exceeded` when waiting for a receipt?

**Pull request merged**
