### PR TITLE
feature: backport l2geth with go-ethereum native trace v1.10.20

### PR DESCRIPTION
**Pull request by jsvisa**
**Description**
A clear and concise description of the features you're adding in this pull request.

**Additional context**
Add any other context about the problem you're solving.

**Metadata**
- Fixes #[Link to Issue]

### CODE REVIEW

**Comment by jsvisa** [comment]
@tynes Thanks for your review, it there any update on this?

**Comment by tynes** [comment]
> @tynes Thanks for your review, it there any update on this?

Hey @jsvisa appreciate all the work that you did to backport this. The diff is massive and I do not think we will be able to merge it in this state. We are open to the idea of cutting a special release from this branch that community members can try at their own risk because we know that tracing has been difficult. If there is a bug in here, it would be basically like introducing a hardfork into the protocol and we do not want to risk that right now with an upcoming upgrade to the system.

**Comment by jsvisa** [comment]
@tynes thanks for your advice, and looks good to me. BTW, in our infra, we can run [ethereum-etl](https://github.com/blockchain-etl/ethereum-etl) on the two branches, and compare the difference.

**Comment by jsvisa** [comment]
any update？

**Comment by mslipper** [comment]
Hey there!

After conferring with the team, I'm going to close this PR. The team is all-hands-on-deck with the Bedrock upgrade, and we don't have the bandwidth right now to review such a large and high-risk diff carefully enough.

That said, if anyone needs these fixes prior to Bedrock launching and is willing to take on the risk of using themselves, we'll direct them to your branch.

We very much appreciate the effort here - if we weren't so close to the Bedrock finish line, we'd strongly consider merging this in.

**Pull request closed without merging**
