### PR TITLE
Add fraud prover

### PR DESCRIPTION
**Pull request by jliphard**
Basic Function Testing Completed - See Readme for Documentation Thereof

**HOWTO**
For basic instructions on adding a *Verifier* and *Fraud_Prover* pair to your local test system, please see the Readme.

**Description**
Refactor the now archived fraud-prover service for the new monorepo.

**Context** 
The `fraud-prover` service is relevant to the sequencer operating in its verifier mode. Adding the fraud-prover service into the monorepo raises several questions that relate to other repos, the dockers, the ci, etc. For example, some of the utility functions needed by the fraud-prover might be best located in `core-utils`? More generally, it could be useful to write a few simple scripts/commands related to running a verifier, rather than running the system in its normal operating mode.

Please let me know what would be most useful for you all!

### CODE REVIEW

**Comment by tynes** [comment]
Hey @jliphard thanks for your contribution! It looks like some files could use some linting. I think the first step is to get the code into the repo and then we can follow up with additional PRs that add in the CI. Let us know when its ready for review and we can remove the `DO-NOT-MERGE` label

**Comment by jliphard** [comment]
Ok, lint looks good and cleaned up some other things. No idea why the unit tests are failing for smockit (_Error: src/smockit/binding.ts(2,43): error TS2307: Cannot find module 'hardhat/internal/hardhat-network/provider/errors' or its corresponding type declarations._) since that's in an entirely different part of the codebase.

**Comment by tynes** [comment]
> Ok, lint looks good and cleaned up some other things. No idea why the unit tests are failing for smockit (Error: src/smockit/binding.ts(2,43): error TS2307: Cannot find module 'hardhat/internal/hardhat-network/provider/errors' or its corresponding type declarations.) since that's in an entirely different part of the codebase.

I bet this is due it being on an older version of `smock`, try updating to `1.0.2`

**Comment by tynes** [comment]
Created an issue to track fixing this bug: https://github.com/ethereum-optimism/optimism/issues/554

**Comment by jliphard** [comment]
Ok, things seems to work as expected. I documented (in the readme) the needed `local.yaml`, `local.env.yaml`, `Dockerfile.faruad_prover`,  and `wait_for_Verifier_and_L2.sh` code - this might also help to generate the needed /ops files.

**Comment by tynes** [comment]
Hey @jliphard, a fix to `smock` was merged here: https://github.com/ethereum-optimism/optimism/pull/576. The problem seems to have gone away before this was merged? Would love to see if the integration tests pass now. You may be already aware of this, but fixing the `yarn.lock` can be done automatically just by rebasing and then running `yarn`

**Comment by jliphard** [comment]
GitHub actions seem to be stuck? Will reset them by closing the PR, and then re-opening it.

**Comment by gakonst** [comment]
Hey @jliphard, we'll hold off on merging this PR until we can get some integration tests in for this functionality, as well as bringing it up in the docker-compose stack. 

If you end up writing any of these, go ahead and push them in this PR.

**Comment by jliphard** [comment]
Hello @gakonst - makes perfect sense not to merge for the time being. I'm happy to help, but would require some input on what you think would be most useful. Which fraud scenarios should be evaluated? There are 'simple' fraud scenarios but also presumably others (e.g. involving the safety checker or gas limits or timing). 

**What kind(s) of fraud to consider -> Simple Fraudulent State Roots only?**

A basic thing could be to inject/generate fraudulent state roots in the `state-batch-submitter` (specifically, `_generateStateCommitmentBatch`) which can already return an incorrect `stateRoot` if desired. Since that's done simply by using specific preconfigured `blockTx.from` values, that's really convenient. That should trigger the Verifier/Fraud Prover, although from a testing perspective, it would be good to write some valid state roots into the SCC first, so that correct pruning by `finalizeFraudVerification` and `deleteStateBatch` can be verified. Alternatively, the test-fraud could be injected upstream of the batch submitter (in the l2Provider) but the batch-submitter seems like a good place for that - and the entire functionality is already in place anyway. 

**Mockchain vs. live local system**

It would be easiest (in terms of lines of code written) to just spin up a local system and define/use a suitable `env.FRAUD_SUBMISSION_ADDRESS` value. One could then push _N_ transactions and, knowing that the `generateStateCommitmentBatch` will trigger after e.g. 5 transactions, test against that. This would require a few lines of code in `generateStateCommitmentBatch`. A test would be considered successful if the Verifier and Fraud Prover kick in, the system switches to Fraud Proof Mode, and after some time delay, the SCC roots would be reconciled the CTC transactions. Could also make sure that the gas was in line with expectations.  

**Where could/should the integration test live?** 

Setup could be (partially) handled in /integration-tests/test/shared/util.ts, although not entirely, since the `batch_submitter` would be needed to be brought up first.

Let me know what would be useful (and please correct the above) - there are dozens of ways of doing this - in the above tried to minimize the number of lines of code that would be affected.

**Comment by gakonst** [comment]
If you wanted to use the Mockchain, I think it'd end up being a fraud prover unit test - see how the batch submitter unit tests are written.

For the integration tests, the setup code would be:
1. a new docker image (see e.g. [batch submitter](https://github.com/ethereum-optimism/optimism/blob/master/ops/docker/Dockerfile.batch-submitter), and the [monorepo builder](https://github.com/ethereum-optimism/optimism/blob/master/ops/docker/Dockerfile.monorepo#L33)
2. adding it to the [docker-compose](https://github.com/ethereum-optimism/optimism/blob/master/ops/docker-compose.yml)
3. adding a new l2geth container which syncs from L1 data

In order to get a fraudulent batch in, you'd make a manual tx/state root submission to the smart contracts such that the post-tx state root is not the one which corresponds to the one from the transaction. Then you'd wait for the fraud prover to do its job.

**Comment by tynes** [comment]
> you'd make a manual tx/state root submission to the smart contracts such that the post-tx state root is not the one which corresponds to the one from the transaction.

This could be done by calling the contracts directly from the tests, ie skipping the batch submitter. The key to use in the tests can be found here: https://github.com/ethereum-optimism/optimism/blob/01a2e7d2f225c33316c780c6f3b30a27d59556d5/ops/docker-compose.yml#L113

**Comment by jliphard** [comment]
Yes, @gakonst and @tynes - that's a much more elegant way to do it - perfect! Give me some time though...

**Comment by gakonst** [comment]
All good - take your time. Thank you again.

**Comment by snario** [comment]
Closing for now until there is more activity.

**Pull request closed without merging**
