### PR TITLE
cannon: delete extra go.mod

### PR DESCRIPTION
**Pull request by tynes**
**Description**

Makes dependabot work more easily and keep the
deps in sync.

### CODE REVIEW

**Review by protolambda — APPROVED** [review]

**Comment by trianglesphere** [comment]
Does this need a rebase? Error in tests is `open ../example/bin/claim.elf`. Maybe CI go something wrong? This doesn't appear to change it.

**Comment by trianglesphere** [comment]
bump @tynes, would a merge in from develop fix this?

**Comment by tynes** [comment]
Maybe, not sure what it's failing

**Comment by protolambda** [comment]
The `claim.elf` that the testing depends on is not getting build, likely due to the effective change in `go.mod` position

**Comment by tynes** [comment]
I rebased this, not sure exactly what the solution is, will close if nothing obvious

**Pull request closed without merging**
