### PR TITLE
chore: remove repetitive words

### PR DESCRIPTION
**Pull request by majorteach**
**Description**

remove repetitive words

### CODE REVIEW

**Comment by majorteach** [comment]
> This PR is stale because it has been open 14 days with no activity. Remove stale label or comment or this will be closed in 5 days.

@Inphi  @clabby 

Friendly ping~
Sorry to disturb

**Comment by majorteach** [comment]
Anything need I to do? If have, Please feel free to tell me.

**Review by smartcontracts — DISMISSED** [review]

**Comment by smartcontracts** [comment]
Thanks for the PR! It looks like CI is complaining because a contract got changed, which in turn changed the code hash. I thought the compiler was set up not to do that but I guess it's doing that. You'll need to regenerate some artifacts by running `pnpm pre-pr` inside of the `contracts-bedrock` package.

**Comment by majorteach** [comment]
> Thanks for the PR! It looks like CI is complaining because a contract got changed, which in turn changed the code hash. I thought the compiler was set up not to do that but I guess it's doing that. You'll need to regenerate some artifacts by running `pnpm pre-pr` inside of the `contracts-bedrock` package.

Thanks!

image

I have done the relevant operations, but they have been unsuccessful.

To solve this problem, I rolled back the modifications to the contracts bedrock related files. I think CI should be able to pass now.


Please review again.

I will try to fix the modifications related to contracts bedrock once I have enough time and familiarity with the project. Thank you again

**Pull request closed without merging**
