### PR TITLE
op-batcher: support auto switch to cheaper DA type

### PR DESCRIPTION
**Pull request by ghost**
**Description**

This PR adds auto switch DA type feature to op-batcher.

When set `--data-availability-type=auto`, this feature is enabled. Batcher will start with blob-type, and keep monitoring the cost of blob-type and calldata-type, when another type is cheaper, batcher will switch to that type to save the cost.

~~L1 txpool `ErrAlreadyReserved` is handled as well to avoid stuck when switching~~(removed it in this pr due to another [pr](https://github.com/ethereum-optimism/optimism/pull/10941) merged into develop)

**Tests**

**Additional context**

**Metadata**

### CODE REVIEW

**Comment by tynes** [comment]
This is a very useful feature, thank you for implementing it. For this to be merged, there will need to be test coverage added. I also believe it should be possible to implement in fewer lines of code.

**Comment by ghost** [comment]
> This is a very useful feature, thank you for implementing it. For this to be merged, there will need to be test coverage added. I also believe it should be possible to implement in fewer lines of code.

sure. let me add tests and welcome any comments about the implement

**Comment by ghost** [comment]
@sebastianst i saw that there's another pr https://github.com/ethereum-optimism/optimism/pull/11219 trying to implement the same feature, you can close this pr if the other one is preferred. If this pr is still needed, plz let me know and i'll add some test code

**Comment by sebastianst** [comment]
> @sebastianst i saw that there's another pr #11219 trying to implement the same feature, you can close this pr if the other one is preferred. If this pr is still needed, plz let me know and i'll add some test code

Hey @bnoieh thanks for this PR! It inspired the work in that [other PR](https://github.com/ethereum-optimism/optimism/pull/11219) and I gave you credit in the description. I'm gonna close this one as redundant.

**Pull request closed without merging**
