### PR TITLE
feat: add interfaces for L1 contracts

### LINKED ISSUE #11681: EVM Engineering: add interfaces for L1 contracts
Tracking issue for adding interfaces for L1 contracts.

### PR DESCRIPTION
**Pull request by renlulu**
**Description**

Add interfaces for L1 contracts.

**Tests**

Refactor only, no major logic change, so no new tests added.

**Additional context**

**Metadata**

- Fixes #11681 #11678

### CODE REVIEW

**Comment by renlulu** [comment]
Fixing the checking issue.

**Comment by renlulu** [comment]
The interface checking issue is, it needs contracts abis are exactly the same as interfaces' abi, but there are extra abis got generated cause of some constants, and those constants cannot be defined inside the interface contract due to Solidity's constriction or language feature:

```
    # Use jq to compare the ABIs
    if ! diff_result=$(diff -u <(echo "$interface_abi" | jq -S .) <(echo "$contract_abi" | jq -S .)); then
        if ! grep -q "^$contract_name$" "$REPORTED_INTERFACES_FILE"; then
            echo "$contract_name" >> "$REPORTED_INTERFACES_FILE"
            if ! is_excluded "$contract_name"; then
                echo "Issue found in ABI for interface $contract_name from file $interface_file."
                echo "Differences found in ABI between interface $contract_name and actual contract $contract_basename."
                if [ "$no_diff" = false ]; then
                    echo "$diff_result"
                fi
                issues_detected=true
            fi
        fi
        continue
    fi
 ```
 
 So i am thinking instead of doing exact match, can we just do some substring comparison, to make sure contracts is fully implementing those functions define inside interface contract? But this also sounds weird to me, as solidity complier always has such check if you run forge build.

**Comment by smartcontracts** [comment]
This is amazing, thank you. I am going to make some minor edits to this PR to get it to pass CI.

**Comment by renlulu** [comment]
> This is amazing, thank you. I am going to make some minor edits to this PR to get it to pass CI.

Thank you, if you don't mind i can take other refactor also

**Comment by smartcontracts** [comment]
Heyo @renlulu to simplify this PR do you mind opening up a new PR that only introduces the new interfaces without modifying the contracts to use those interfaces? Modifying the contracts adds a lot of complexity, I will probably just do that as part of a separate PR.

**Comment by smartcontracts** [comment]
I also recommend using `cast interface ./forge-artifacts/to/Contract.sol/Contract.json` to automatically generate interfaces, can be very helpful

**Comment by smartcontracts** [comment]
Actually for now it may be easier if I take over this PR, would you be willing to work on the L2 contracts instead? This PR blocks some important work on reducing compile time so I'd like to get it in as quickly as possible.

**Comment by renlulu** [comment]
> Actually for now it may be easier if I take over this PR, would you be willing to work on the L2 contracts instead? This PR blocks some important work on reducing compile time so I'd like to get it in as quickly as possible.

Yes sure, you can take over this, and do what ever modification that convenient for you. I can look for L2 contracts. Thanks!

**Comment by renlulu** [comment]
> Actually for now it may be easier if I take over this PR, would you be willing to work on the L2 contracts instead? This PR blocks some important work on reducing compile time so I'd like to get it in as quickly as possible.

Or i can quickly move those events and error back, just let me know

**Comment by renlulu** [comment]
> I also recommend using `cast interface ./forge-artifacts/to/Contract.sol/Contract.json` to automatically generate interfaces, can be very helpful

Yes, this one quite helpful, just had a try. But it looks like it is very hard to retain the comments (which is useful) as the interface is generated from the abi.

**Comment by smartcontracts** [comment]
So the plan for the interfaces is:

1. Generate simple interfaces for everything (without comments if necessary)
2. Use these simple interfaces to improve the compilation time
3. Update contracts to use the interfaces and move comments/errors/whatever into the interfaces themselves

**Comment by renlulu** [comment]
> So the plan for the interfaces is:
> 
> 1. Generate simple interfaces for everything (without comments if necessary)
> 2. Use these simple interfaces to improve the compilation time
> 3. Update contracts to use the interfaces and move comments/errors/whatever into the interfaces themselves

ok since i am still keen here, shall i restart a new PR for it? I guess i can submit it quickly. or you want do it yourselves, both works for me.

**Comment by renlulu** [comment]
> So the plan for the interfaces is:
> 
> 1. Generate simple interfaces for everything (without comments if necessary)
> 2. Use these simple interfaces to improve the compilation time
> 3. Update contracts to use the interfaces and move comments/errors/whatever into the interfaces themselves

https://github.com/ethereum-optimism/optimism/pull/11809

i think this could be the style you like

**Comment by smartcontracts** [comment]
I am going to work on this in #11627 because the changes are quite extensive to be able to get CI to pass

**Comment by renlulu** [comment]
> I am going to work on this in #11627 because the changes are quite extensive to be able to get CI to pass

ah ok, just saw it. closed mine, thanks!

**Comment by renlulu** [comment]
> I am going to work on this in #11627 because the changes are quite extensive to be able to get CI to pass

Going to close this PR as well as it is not needed. But i still want to try L2 contracts, curious to see how CI works in this case. Thanks for all the conversation btw

**Pull request closed without merging**
