### PR TITLE
Add clarity to the expectApprox function signature

### PR DESCRIPTION
**Pull request by reggieag**
**Description**
This PR attempts to add clarity to the `expectApprox` function signature by turning the deviation arguments into an object. This pattern is similar to named parameters in other languages like Python. I also made the argument names a little bit more verbose.

**Additional context**
This is my first PR to Optimism and my first time messing around with Typescript. I'm very open to feedback!

**Metadata**
- Fixes https://github.com/ethereum-optimism/optimism/issues/1154
- Fixes OP-914 (linear)

### CODE REVIEW

**Comment by smartcontracts** [comment]
It might be worth simply adding a single `percentDeviation` parameter. I'm not sure if we're ever really going to need different upper and lower bounds. cc @maurelian since you added this function, wdyt?

**Comment by maurelian** [comment]
@reggieag, I like this change, thank you.

> I'm not sure if we're ever really going to need different upper and lower bounds.

My first thought is that there's a big difference between upper/lower bounds; typically we want to limit how much a function might become more expensive, but we don't mind if something gets cheaper by a large margin. 

OTOH, I can imagine that we might want to be aware when something gets a lot cheaper, and lock in those savings by updating the target.... 

OK, then IMO this PR should do the following things: 
1. Use a single `percentDeviation` parameter.
2. Have that value default to 1%

**Comment by tynes** [comment]
I'm not super opinionated and am fine with either approach, ie having 2 params or 1 param. Having 1 param semi defeats the purpose of this PR but I do suppose that having the 3rd arg be an object still would be useful

**Comment by maurelian** [comment]
Akshully, I think this PR is a sufficient improvement over the status quo, and we should just get it in.
And I think it's fine to have both the upper and lower deviation options.

**Comment by maurelian** [comment]
Thanks so much @reggieag! FWIW, there were a few esoteric changes related to our workflow that were just easier to do myself, so I opened a new PR that addresses them at #1187 (preserves your authorship of course). Gonna close this one now, and hopefully get that one merged in ASAP.

**Comment by reggieag** [comment]
sounds good @maurelian ! I'm definitely curious to see what the workflow specifics are and will follow along your PR to peek.


FWIW, I think having one parameter would make for cleaner code. You could then replace the named parameter with a constant. The constant name should add clarity IMO.

**Comment by maurelian** [comment]
> FWIW, I think having one parameter would make for cleaner code. You could then replace the named parameter with a constant. The constant name should add clarity IMO.

I see your point, but think we're in a 'good enough' spot as is. :)

**Comment by reggieag** [comment]
Sounds good to me!

**Pull request closed without merging**
