### PR TITLE
fix: have messenger return true on success

### PR DESCRIPTION
**Pull request by smartcontracts**
**Description**
Having the bridge return `abi.encode(true, bytes(""))` on success. Seeing if this will solve #497.

### CODE REVIEW

**Comment by tynes** [comment]
This should be based on `v4.0.0-rc`

**Comment by snario** [comment]
This needs to re-target `regenesis/0.4.0`.

**Comment by gakonst** [comment]
I've rebased this on top of regenesis/0.4.0. It looks like the receipt returned is 0 still in the integration test!

**Comment by smartcontracts** [comment]
Superseded by #937

**Pull request closed without merging**
