### PR TITLE
feat(ctb): Append Only Array in DisputeGameFactory

### PR DESCRIPTION
**Pull request by refcell**
**Description**

Adds an append-only array of game implementations to improve downstream game solver offchain reliability.

### CODE REVIEW

**Review by clabby — COMMENTED** [review]
LGTM, will approve when CI passes.

**Comment by refcell** [comment]
@Mergifyio queue

**Comment by refcell** [comment]
rugged

**Comment by refcell** [comment]
@mergifyio requeue

**Comment by refcell** [comment]
@Mergifyio queue

**Pull request merged**
