### PR TITLE
When in doubt, bump the timeout

### PR DESCRIPTION
**Pull request by trianglesphere**

### CODE REVIEW

**Comment by ajsutton** [comment]
We won't need to do this once https://github.com/ethereum-optimism/optimism/pull/7880 merges and I've got a second PR coming that should shave another few minutes off.  So I'd probably leave the timeout as-is for now.

**Review by tynes — APPROVED** [review]

**Comment by tynes** [comment]
Will defer to @ajsutton

**Comment by ajsutton** [comment]
We've got a bit of head room again even just with no cannon on HTTP:
image

So I think we should leave the timeout.  I'll get that other test improvement up today as well which should shave another couple of minutes off.

**Comment by trianglesphere** [comment]
That buffer looks decent & I'm fine closing this. I really like finding the rhyme, but I don't feel super strongly about it.

**Pull request closed without merging**
