### PR TITLE
feat: add .nvmrc

### PR DESCRIPTION
**Pull request by smartcontracts**
**Description**
Adds an `.nvmrc` file so that users know which node version to use when developing locally. Please note that you will still have to run `nvm use` in the root of this repository to install the correct node version.

### CODE REVIEW

**Comment by smartcontracts** [comment]
@elenadimitrova do you think we should document the need to run `nvm use` at the root?

**Comment by elenadimitrova** [comment]
@smartcontracts definitely add instruction to `nvm use` here https://github.com/ethereum-optimism/optimism/blob/regenesis/0.5.0/CONTRIBUTING.md#building-the-typescript-packages

**Comment by smartcontracts** [comment]
> @smartcontracts definitely add instruction to `nvm use` here https://github.com/ethereum-optimism/optimism/blob/regenesis/0.5.0/CONTRIBUTING.md#building-the-typescript-packages

Done

**Review by maurelian — APPROVED** [review]
Let's get that money.

**Pull request merged**
