### PR TITLE
[Issue-1682] Cleanup unused imports

### LINKED ISSUE #1682: Clean up unused imports in the integration tests
**Is your feature request related to a problem? Please describe.**
Our integration test files have a bunch of unused imports. For example, this import is not used:

https://github.com/ethereum-optimism/optimism/blob/214473692184dbc1f0953a1e6078a9ab318a109f/integration-tests/test/fee-payment.spec.ts#L7

**Describe the solution you'd like**
I would like to have someone review all integration tests and delete any unused imports. In vscode, you can see that an import is not used because it's greyed out:

**NOTE**: Please target the `regenesis/0.5.0` branch.

### PR DESCRIPTION
**Pull request by coreyar**
**Description**
Adds eslint rule to error on unused vars. This PR also fixes violations of that rule not only in the integration tests but in the whole project

**Additional context**

**Metadata**
- Fixes #1682

### CODE REVIEW

**Review by smartcontracts — APPROVED** [review]
Fantastic work, thank you!

**Comment by tynes** [comment]
Looks like the linting is failing, there are more unused imports

**Comment by coreyar** [comment]
> Looks like the linting is failing, there are more unused imports

Hmm ok let me check

**Comment by tynes** [comment]
Happy to merge once the additional linting errors are fixed. You can see them on github if you look at the files changed

**Comment by tynes** [comment]
Looks like there is now a merge conflict - do you mind rebasing to fix the conflict and then squashing all of the commits into a single commit?

**Comment by coreyar** [comment]
> Looks like there is now a merge conflict - do you mind rebasing to fix the conflict and then squashing all of the commits into a single commit?

Ahh I just saw this. Yes I can take care of this

**Comment by tynes** [comment]
Please squash your commits into a single commit and this will be good to merge

**Comment by smartcontracts** [comment]
Great work @coreyar, thank you!

**Pull request merged**
