### PR TITLE
Update to golang 1.20.7 and alpine 3.18

### PR DESCRIPTION
**Pull request by ajsutton**
**Description**

Updates docker images to use go 1.20.7 and use alpine 3.18 as a base.

### CODE REVIEW

**Comment by tynes** [comment]
I don't see a diff to the `go.mod` which is the source of truth for what version is used. It will still use an older version if a newer compiler version is installed because the `go.mod` is the source of truth

**Comment by ajsutton** [comment]
> I don't see a diff to the `go.mod` which is the source of truth for what version is used. It will still use an older version if a newer compiler version is installed because the `go.mod` is the source of truth

Today I learned... Will go change all the go.mod's I can find too.

**Comment by tynes** [comment]
Looks like some static analysis issues now

**Comment by tynes** [comment]
Also any reason to not do the latest version? 1.21.0?

**Comment by ajsutton** [comment]
> Also any reason to not do the latest version? 1.21.0?

Because go-libp2p doesn't work with 1.21 yet.

**Review by refcell — APPROVED** [review]
LGTM

**Review by tynes — APPROVED** [review]

**Review by roninjin10 — APPROVED** [review]

**Review by mslipper — APPROVED** [review]
Proto/Josh review only needed for a trivial test. Approving.

**Pull request merged**
