### PR TITLE
feat(dtl): hardcode bss hf1 index into the dtl

### PR DESCRIPTION
**Pull request by smartcontracts**
**Description**
Hardcodes the index of the first BSS hardfork into the DTL, depending on
the chain ID. This is easier than asking users to set an environment
variable each time.

### CODE REVIEW

**Comment by tynes** [comment]
I think there should be a logline that shows the detected chainid and the height at which the hardfork applies

**Comment by smartcontracts** [comment]
> I think there should be a logline that shows the detected chainid and the height at which the hardfork applies. This will make it very obvious for people running the software to know they are on an up to date version

Added a longline to the main service

**Comment by mslipper** [comment]
Looks like the verifier tests are failing?

**Review by mslipper — CHANGES_REQUESTED** [review]
Let's see if we can fix the verifier tests before merging.

**Review by mslipper — APPROVED** [review]

**Pull request merged**
