### PR TITLE
contracts: Rename OptimismPortal2 to L1ToL2MessagePasser

### PR DESCRIPTION
**Pull request by maurelian**
**Description**

This is controversial, so I'm just opening in draft for now to progress the conversation and see if I've missed any CI checks.

### CODE REVIEW

**Comment by tynes** [comment]
hmm

**Comment by tynes** [comment]
big diff bad

**Comment by smartcontracts** [comment]
Honestly I feel pretty strongly about *not* doing this because this is basically scope bloat for the sake of renaming a contract. Feels like a lot of extra work for relatively minimal benefit.

**Comment by mds1** [comment]
I do like this rename because it's more clear and aligns with the rest of the contract naming schemes, which makes things easier to understand. But it I agree it's a big bloaty change, which also spills over into the superchain-registry and superchain-ops repos, and likely other repos too. So it may not be worth it

Some other ideas:
- Move all the portal code into an `abstract L1ToL2MessagePasser` for clarity, but then have `contract OptimismPortal is L1ToL2MessagePasser {}` to avoid any renames or breaking changes.
- Only rename OptimismPortal2 to L1ToL2MessagePasser, keep OptimismPortal around, but update the implementation so it's just a pass through to L1ToL2MessagePasser, and deprecate it. I'm guessing having to update that address everywhere is also a big effort, but it gives us a path to start migrating other L1 contracts to new proxies so they're all consistent, if that's something we want to do.

**Pull request closed without merging**
