### PR TITLE
contracts-bedrock: L1CrossDomainMessenger single impl

### PR DESCRIPTION
**Pull request by tynes**
**Description**

See this [notion doc](https://oplabs.notion.site/External-Reviewing-the-Single-Implementation-Smart-Contract-Changes-a79827afc91c40f7ae13b6340ab84622) on how to review

### CODE REVIEW

**Comment by tynes** [comment]
Reverting someplace during deployment assertions

```
    ├─ [3026] ResolvedDelegateProxy::portal() [staticcall]
    │   ├─ [1213] AddressManager::getAddress(OVM_L1CrossDomainMessenger) [staticcall]
    │   │   └─ ← L1CrossDomainMessenger: [0x607C32116F0C70909C8b9b784EcF308bAB3797ce]
    │   ├─ [385] L1CrossDomainMessenger::portal() [delegatecall]
    │   │   └─ ← Proxy: [0xE6f51AED038F1735E0A4B8F0daAF8b6218Fb2C76]
    │   └─ ← Proxy: [0xE6f51AED038F1735E0A4B8F0daAF8b6218Fb2C76]
    └─ ← "EvmError: Revert"
```

**Review by Inphi — COMMENTED** [review]
LGTM. Going by the following checklist.
- [x] update natspec
- [x] migrate to reinitializer(2)
- [x] prohibit public immutables
- [x] ABI-stable getters for previous immutables
- [x] .storage-layout does not change existing identifiers
- [x] sentinels are zero-valued - N/A

I'm not sure what to look for in the `check-l2` CI task, so I'd appreciate another reviewer approves this before merging

**Review by refcell — APPROVED** [review]
- Changes follow the guidelines set in the notion doc.
- Verified the output of the `check-l2` script (ref below).
```
INFO [08-07|15:21:18.747] Checking predeploy                       name=L2CrossDomainMessenger address=0x4200000000000000000000000000000000000007
INFO [08-07|15:21:18.749] L2CrossDomainMessenger                   implementation=0xC0d3c0d3c0D3c0D3C0d3C0D3C0D3c0d3c0d30007
INFO [08-07|15:21:18.750] L2CrossDomainMessenger                   OTHERMESSENGER=0xEC33eA8182B68F36EBeEbb287ec4EFF0984ad711
INFO [08-07|15:21:18.750] L2CrossDomainMessenger                   l1CrossDomainMessenger=0xEC33eA8182B68F36EBeEbb287ec4EFF0984ad711
INFO [08-07|15:21:18.751] L2CrossDomainMessenger                   MESSAGE_VERSION=1
INFO [08-07|15:21:18.751] L2CrossDomainMessenger                   MIN_GAS_CALLDATA_OVERHEAD=16
INFO [08-07|15:21:18.752] L2CrossDomainMessenger                   RELAY_CONSTANT_OVERHEAD=200,000
INFO [08-07|15:21:18.753] L2CrossDomainMessenger                   MIN_GAS_DYNAMIC_OVERHEAD_DENOMINATOR=63
INFO [08-07|15:21:18.753] L2CrossDomainMessenger                   MIN_GAS_DYNAMIC_OVERHEAD_NUMERATOR=64
INFO [08-07|15:21:18.754] L2CrossDomainMessenger                   RELAY_CALL_OVERHEAD=40000
INFO [08-07|15:21:18.755] L2CrossDomainMessenger                   RELAY_RESERVED_GAS=40000
INFO [08-07|15:21:18.756] L2CrossDomainMessenger                   RELAY_GAS_CHECK_BUFFER=5000
INFO [08-07|15:21:18.756] L2CrossDomainMessenger version           version=1.5.0
```

**Comment by tynes** [comment]
Thank you for the review here!

**Comment by tynes** [comment]
@Mergifyio refresh

**Comment by tynes** [comment]
@refcell I'm going to simplify the code, will push a commit

**Review by refcell — APPROVED** [review]

**Comment by tynes** [comment]
Hit a race condition in the `op-chain-ops` tests, this one seems to be more common recently

**Pull request merged**
