### PR TITLE
feat: move interfaces to a new top-level folder

### PR DESCRIPTION
**Pull request by smartcontracts**
Moves all contract interfaces to a new top-level folder. Keeps things much cleaner and more sane for a future auto-generated interface system.

### CODE REVIEW

**Comment by tynes** [comment]
This is going to make a giant headache for open PRs that will need a rebase (standard L2 genesis)

**Review by maurelian — APPROVED** [review]
I scrolled through the whole diff!

**Comment by maurelian** [comment]
> This is going to make a giant headache for open PRs that will need a rebase (standard L2 genesis)

Going to leave my approval on, but applied the do-not-merge label to address this discussion. 

IMO we should not continue to disrupt dev momentum for the L2 standard genesis work which is in limbo and going into a new discovery/scoping phase next week.

**Comment by smartcontracts** [comment]
> IMO we should not continue to disrupt dev momentum for the L2 standard genesis work which is in limbo and going into a new discovery/scoping phase next week.

I'll push back on this. We have no guarantees about the timeline for the L2 genesis work and that PR has already blocked changes on the basis of rebasing for almost a month now.

**Comment by smartcontracts** [comment]
> This is going to make a giant headache for open PRs that will need a rebase (standard L2 genesis)

Standard L2 genesis is the only one that's really impacted by this and we have no idea how long it's going to take to be merged at this point. I feel strongly that we should bite the bullet and start being able to get work done on the contracts again. I can personally handle the rebasing process if others don't want to.

**Review by AmadiMichael — APPROVED** [review]

**Review by mslipper — APPROVED** [review]
ops changes lgtm

**Pull request merged**
