### PR TITLE
feat(ctb): preserve legacy ETH invariant

### PR DESCRIPTION
**Pull request by smartcontracts**
**Description**
Preserves the invariant in LegacyERC20ETH that balanceOf(x) is always the same as address(x).balance. balanceOf is the only function that was not being blocked and contracts may exist that rely on this behavior.

**Invariants**
Preserves the invariant that `LegacyERC20ETH.balanceOf(x) == address(x).balance`.

### CODE REVIEW

**Comment by mslipper** [comment]
I think this is important that we do this. One of Bedrock's guiding principles is backwards compatibility, so in the off chance someone is using this we should expose this functionality.

**Comment by tynes** [comment]
This makes sense. Its a bit weird that `totalSupply == 0` while `balanceOf(...) > 0` can be true.
Would be nice to trace everything and see if the `balanceOf` interface is called. Any usage of `transfer` or `transferFrom` will revert, which could happen after a call to `balanceOf`.
Unclear if this prevents bugs or adds bugs

**Comment by tynes** [comment]
@maurelian can you think of any issues with this?

**Comment by maurelian** [comment]
What invariants need to be preserved in the OVM_ETH contract? 
1. You currently cannot call any state changing methods.

**Pull request merged**
