### PR TITLE
contracts-bedrock: use underscore prefix on args in ChainAssertions

### PR DESCRIPTION
**Pull request by maurelian**

### CODE REVIEW

**Comment by clabby** [comment]
I cover this in my PR (#8240), which is already doing some refactors here :)

**Comment by mds1** [comment]
Per https://github.com/ethereum-optimism/optimism/blob/develop/docs/handbook/pr-guidelines.md#before-starting-prs, I do think it would be preferable to keep semgrep fixes as a separate PR, since that will make #8240's scope smaller and easier to review (assuming doing so doesn't make your rebases too complex due to refactors)

**Comment by refcell** [comment]
> Per https://github.com/ethereum-optimism/optimism/blob/develop/docs/handbook/pr-guidelines.md#before-starting-prs, I do think it would be preferable to keep semgrep fixes as a separate PR, since that will make #8240's scope smaller and easier to review (assuming doing so doesn't make your rebases too complex due to refactors)

It is, but OTOH at this point it's more of a chore to rebase ontop of this iiuc. Might as well go with #8240 in it's current state.

**Comment by maurelian** [comment]
Going to close this. I agree that #8240 would be easier to review if the changes were handled here, but also that we can skip it for now.

**Pull request closed without merging**
