### PR TITLE
Fix proxyd build

### PR DESCRIPTION
**Pull request by mslipper**
Adds musl headers and GCC to the proxyd build.

### CODE REVIEW

**Review by Inphi — APPROVED** [review]
LGTM. One note; buster is a larger baseimage than alpine. Not by much though.

**Comment by mslipper** [comment]
Yeah. I used buster slim for the output image to cut down on some size. Unless we pull libc into Alpine I don't see a way around this.

**Comment by tynes** [comment]
Our geth image runs in alpine - https://github.com/ethereum-optimism/optimism/blob/develop/ops/docker/Dockerfile.geth

Also other services with geth use alpine
- https://github.com/ethereum-optimism/optimism/blob/develop/ops/docker/Dockerfile.gas-oracle
- https://github.com/ethereum-optimism/optimism/blob/develop/ops/docker/Dockerfile.batch-submitter-service

Perhaps this is a versioning issue?

**Comment by tynes** [comment]
Upstream also uses alpine https://github.com/ethereum/go-ethereum/blob/master/Dockerfile

**Comment by mslipper** [comment]
Wow, well I was completely wrong. Fixed by adding musl headers to alpine.

**Review by tynes — APPROVED** [review]

**Pull request merged**
