### PR TITLE
Increase branch coverage 

### LINKED ISSUE #1555: Improve branch code coverage
Our reported branch code coverage on the ~experimental~ `develop` branch is currently at ~78% . Add tests to increase that as much as possible to 100%. It is difficult to say what number is optimal for us, so work on establishing a balance between coverage and effort required. 

Specifically we require that the following two libraries are code covered: `Lib_BytesUtils` and `Lib_RLPReader`

### PR DESCRIPTION
**Pull request by coolhill**
**Description**
Increase branch coverage for `Lib_BytesUtils`, `Lib_RLPReader` and more on `develop`. 

**Metadata**
- Fixes #1555

### CODE REVIEW

**Comment by coolhill** [comment]
branches that probably need no tests
```
contracts/chugsplash/L1ChugSplashProxy.sol
- require in setCode as stated as a comment probably cannot actually fail.

contracts/L1/messaging/L1StandardBridge.sol
contracts/L2/messaging/L2StandardBridge.sol
- Lib_PredeployAddresses.OVM_ETH is just a dead address?

contracts/L1/messaging/L1CrossDomainMessenger.sol
contracts/L2/messaging/L2CrossDomainMessenger.sol
- not necessary to break require

contracts/L1/rollup/CanonicalTransactionChain.sol
- require in enqueue as stated as a comment is just for debug information
- "duplicate" require in appendSequencerBatch

contracts/L1/rollup/ChainStorageContainer.sol
- onlyOwner modifier
- single argument version of setGlobalMetadata, push, deleteElementsAfterInclusive is not used

contracts/L2/predeploys/OVM_DeployerWhitelist.sol
contracts/L2/predeploys/WETH9.sol
- skipped

contracts/libraries/utils/Lib_Buffer.sol
- single argument version of push is not used

contracts/libraries/utils/Lib_MerkleTree.sol
- require cannot be reached
```

**Comment by coolhill** [comment]
`contracts/L1/rollup/CanonicalTransactionChain.sol`
- [L310](https://github.com/coolhill/optimism/blob/23fecaeb3a9712f42fb9b64238749546f17f6f7e/packages/contracts/contracts/L1/rollup/CanonicalTransactionChain.sol#L310) seems like it will be covered by [L296](https://github.com/coolhill/optimism/blob/23fecaeb3a9712f42fb9b64238749546f17f6f7e/packages/contracts/contracts/L1/rollup/CanonicalTransactionChain.sol#L296) but maybe I am mistaken.

`contracts/L1/messaging/L1CrossDomainMessenger.sol`
- as I understood it [L82](https://github.com/coolhill/optimism/blob/23fecaeb3a9712f42fb9b64238749546f17f6f7e/packages/contracts/contracts/L1/messaging/L1CrossDomainMessenger.sol#L82) cannot be reached since the function is of type initializer which has a similar require already
- how to test for xDomainMessageSender since the value only changes quickly at [L201](https://github.com/coolhill/optimism/blob/23fecaeb3a9712f42fb9b64238749546f17f6f7e/packages/contracts/contracts/L1/messaging/L1CrossDomainMessenger.sol#L201)  ?

`contracts/L2/predeploys/OVM_DeployerWhitelist.sol`
- what do you mean ignore this file? if I add it to the skiplist(.solcover.js) then many other tests will fail

`contracts/L1/rollup/StateCommitmentChain.sol`
- I see what you mean here, fixed it in https://github.com/ethereum-optimism/optimism/pull/1931/commits/23fecaeb3a9712f42fb9b64238749546f17f6f7e

**Comment by elenadimitrova** [comment]
>contracts/L1/rollup/CanonicalTransactionChain.sol
L310 seems like it will be covered by L296 but maybe I am mistaken.

They are different. L310 can throw if the `msg.data.length < nextTransactionPtr` by passing a large enough value for `numContexts` or by passing a larger `msg.data`. Not sure which one is easier. 

>contracts/L1/messaging/L1CrossDomainMessenger.sol
as I understood it L82 cannot be reached since the function is of type initializer which has a similar require already
how to test for xDomainMessageSender since the value only changes quickly at L201 ?

L82 can be reached if you call `L1CrossDomainMessenger.initialize(address(0))`

xDomainMessageSender you can leave for now. I'll try to get it covered using `smock` later.

>contracts/L2/predeploys/OVM_DeployerWhitelist.sol
what do you mean ignore this file? if I add it to the skiplist(.solcover.js) then many other tests will fail

If you add `./L2/predeploys/OVM_DeployerWhitelist.sol` to the `skipFiles` array in `.solcover.js` it will skip the file in coverage reports. No tests will fail as that config setting is about what gets included in the coverage calculations and not what tests are run.

**Review by elenadimitrova — APPROVED** [review]
🎉

**Pull request merged**
