### PR TITLE
cannon: use constant instead of magic value for solidity part

### PR DESCRIPTION
**Pull request by zhiqiangxu**
This is a follow-up PR for [this](https://github.com/ethereum-optimism/optimism/pull/12386) one, which does the same to the solidity part.

### CODE REVIEW

**Review by Inphi — COMMENTED** [review]
L:ooks good. Could you also bump the beta semver in MIPS.sol and MIPS2.sol? You'll have to also generate the semver-lock file using `just semver-lock`.

**Comment by zhiqiangxu** [comment]
> L:ooks good. Could you also bump the beta semver in MIPS.sol and MIPS2.sol? You'll have to also generate the semver-lock file using `just semver-lock`.

Done.

**Review by Inphi — APPROVED** [review]

**Comment by Inphi** [comment]
@zhiqiangxu Thanks. There's a merge conflict in the semver. Could you take a look?

**Comment by zhiqiangxu** [comment]
> @zhiqiangxu Thanks. There's a merge conflict in the semver. Could you take a look?

Done.

**Pull request merged**
