### PR TITLE
ci: Archive fuzz test data

### PR DESCRIPTION
**Pull request by mslipper**

### CODE REVIEW

**Comment by tynes** [comment]
Love the fast turnaround here (https://github.com/ethereum-optimism/optimism/pull/13320)

**Comment by mslipper** [comment]
Tests are failing due to the fuzz test issue fixed in https://github.com/ethereum-optimism/optimism/pull/13324.

**Review by axelKingsley — APPROVED** [review]
Approving because the idea is sound but I haven't directly confirmed that this command to keep the fuzz data works. the `find ...` command looks about right.

**Comment by mslipper** [comment]
I used this to fix the fuzzing bug in https://github.com/ethereum-optimism/optimism/pull/13324.

**Pull request merged**
