### PR TITLE
docker: update node version to 16

### PR DESCRIPTION
**Pull request by tynes**
**Description**
node.js version 16 is currently the lts version
so this commit updates each of the dockerfiles to
use node version 16

### CODE REVIEW

**Comment by smartcontracts** [comment]
Going to double check that we don't have any packages that rely on 14.

**Comment by smartcontracts** [comment]
Nvm I don't think we do. Approving...

**Review by smartcontracts — APPROVED** [review]
LGTM

**Comment by elenadimitrova** [comment]
We are on version 14 in the .nvmrc file though. Do we also need to up that @smartcontracts ?

**Pull request merged**
