### PR TITLE
deps: replace deprecated package with updated package

### PR DESCRIPTION
**Pull request by tynes**
**Description**

https://github.com/miguelmota/go-ethereum-hdwallet is no longer maintained and is using older versions of dependencies. There are dependencies clashing when trying to update code elsewhere in the codebase.

https://github.com/ethereum-optimism/go-ethereum-hdwallet is a fork with updated deps such that we can more easily update other deps in the codebase and drop old deps.

Fixes ENG-2980

### CODE REVIEW

**Comment by mslipper** [comment]
Can you move the fork into `ethereum-optimism`?

**Comment by tynes** [comment]
> Can you move the fork into `ethereum-optimism`?

Updated

**Review by trianglesphere — APPROVED** [review]
lgtm. Let's just remember to remove the replace statements in op-e2e/go.mod when we're done.

**Comment by tynes** [comment]
@protolambda I've rebased this PR after a recent `op-node` update

**Review by protolambda — APPROVED** [review]
Reminder to self: Need to remove the replace statements after the op-geth PR lands.

**Pull request merged**
