### PR TITLE
op-node: flexible L2 genesis generation

### PR DESCRIPTION
**Pull request by tynes**
**Description**

Allow for the `op-node` L2 genesis generation to use either
hardhat artifacts or the `.deploy` L1Deployments JSON file
that is created by the solidity deployment script. While adding
extra logic, this makes genesis generation much easier to be
consumed by the solidity scripts. It also sets up the ability
to deprecate the need for maintaining hardhat deploy style
artifacts. This will allow us to remove a lot of solidity code
and remove the need to call `sync()` to generate the artifacts.
The artifacts make less sense now, especially since it is planned
to have one set of implementation contracts for the entire superchain.
There isn't as much of a need to keep around artifacts for many
contracts separated by network when they are shared between
different L2s.

### CODE REVIEW

**Comment by ghost** [comment]
@tynes This should be really helpful but it would be great if we have some documents about using it.

**Comment by tynes** [comment]
> @tynes This should be really helpful but it would be great if we have some documents about using it.

@kaliubuntu0206 I added a description to the source code, we have docs [here](https://stack.optimism.io/docs/build/getting-started/#generate-the-l2-config-files)

**Review by trianglesphere — APPROVED** [review]
What's the reason for removing the legacy options here? Otherwise LGTM

**Comment by tynes** [comment]
> What's the reason for removing the legacy options here? Otherwise LGTM

We don't have any legacy artifacts at this point left in the monorepo and all new chains should be deployed with the solidity scripts instead of the hardhat deploy scripts. The solidity scripts create modern artifacts

**Pull request merged**
