### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by rdovgan**
**Pull Request Description:**

---

### Description

This PR addresses minor typos and enhances readability across various files in the project. The changes include corrections to spelling, grammar, and formatting inconsistencies.

### Changes Made

- Corrected spelling errors in comments and documentation.
- Improved grammar and clarity in code comments and documentation.
- Ensured consistent formatting of code snippets and documentation.

### Why is this change necessary?

Small corrections like these contribute to the overall professionalism and clarity of the project. They ensure that contributors and users can easily understand and engage with the codebase and documentation.

### Checklist

- [x] I have reviewed the changes to ensure they align with the project's style and conventions.
- [x] The changes do not alter the functionality of the code but only improve readability and correctness.
- [x] I have tested the changes locally to ensure they do not introduce any unintended side effects.
- [x] The commit messages follow the Conventional Commits format for clarity and consistency.

### Related Issue

This PR does not address any specific issue but focuses on general improvements across the project.

### Additional Notes

I followed the contribution guidelines outlined in the project's contributing guide and ensured adherence to the project's code of conduct.

### CODE REVIEW

**Review by trianglesphere — APPROVED** [review]

**Review by sebastianst — APPROVED** [review]

**Comment by rdovgan** [comment]
Updated PR and resolved conflict

**Review by refcell — APPROVED** [review]

**Review by nickbalestra — APPROVED** [review]

**Comment by rdovgan** [comment]
Resolved conflicts

**Review by protolambda — APPROVED** [review]

**Comment by rdovgan** [comment]
Can anyone merge this PR?

**Review by clabby — APPROVED** [review]

**Comment by rdovgan** [comment]
Updated code from the upstream

**Comment by rdovgan** [comment]
Resolved conflicts

**Review by tynes — APPROVED** [review]

**Comment by trianglesphere** [comment]
cc @0x00101010 @zhwrd needs op-conductor approval

**Review by zhwrd — APPROVED** [review]

**Pull request merged**
