### PR TITLE
Revert "Finish conductor rpc e2e tests (#8929)"

### PR DESCRIPTION
**Pull request by ajsutton**
**Description**

This reverts commit 8beb1d76e6984553b87de1db06b8a471d7eeb9a0.

The new test added is causing regular panics in CI:

```
--- FAIL: TestSequencerFailover_ConductorRPC (16.80s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x19a88ee]

goroutine 4686 [running]:
testing.tRunner.func1.2({0x1d15f20, 0x38d5cd0})
	/usr/local/go/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1548 +0x397
panic({0x1d15f20?, 0x38d5cd0?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/ethereum-optimism/optimism/op-node/node.(*OpNode).HTTPEndpoint(0x1ceb720?)
	/root/project/op-node/node/node.go:695 +0xe
github.com/ethereum-optimism/optimism/op-e2e.(*System).RollupEndpoint(...)
	/root/project/op-e2e/setup.go:301
github.com/ethereum-optimism/optimism/op-e2e.(*System).RollupClient(0xc00df12000, {0x0, 0x0})
	/root/project/op-e2e/setup.go:310 +0x145
github.com/ethereum-optimism/optimism/op-e2e.TestSequencerFailover_ConductorRPC(0xc000cccb60)
	/root/project/op-e2e/sequencer_failover_test.go:91 +0xc65
testing.tRunner(0xc000cccb60, 0x266a6e0)
	/usr/local/go/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1648 +0x3ad
exit status 2
```
https://app.circleci.com/pipelines/github/ethereum-optimism/optimism/43284/workflows/71c863d4-8784-4114-96d3-e0f81cc43f31/jobs/1922749/tests

### CODE REVIEW

**Comment by ajsutton** [comment]
FYI @0x00101010 this is reverting one of your commits.  I'm not sure what the conductor is returning but it's not matching up with the actual node name.  I wasn't ever expecting dynamic test data to be passed to `RollupClient` - it would be worth adding an assertion that the node name is what you expect before trying to get the client to avoid the panic.  But obviously need to work out why its not what you expect to stop the test failing.

**Comment by ajsutton** [comment]
I can't dig any deeper at the moment, but if you're stuck let me know and I'll see what I can do.  The only thing I've noticed so far is the wait periods seem pretty short - for wait conditions that "short circuit" (ie continue on as soon as the condition is met) the wait period should be at least 30 seconds as CI can be surprisingly slow.  However I don't think that's the problem here since the waits are passing.

**Review by mslipper — APPROVED** [review]

**Comment by 0x00101010** [comment]
> FYI @0x00101010 this is reverting one of your commits. I'm not sure what the conductor is returning but it's not matching up with the actual node name. I wasn't ever expecting dynamic test data to be passed to `RollupClient` - it would be worth adding an assertion that the node name is what you expect before trying to get the client to avoid the panic. But obviously need to work out why its not what you expect to stop the test failing.

Sorry for the inconvenience caused, I've identified the bugs and will re-submit the PR with the fixes

**Comment by 0x00101010** [comment]
Resubmitted with https://github.com/ethereum-optimism/optimism/pull/9320, fix explanation here: https://github.com/ethereum-optimism/optimism/pull/9320#discussion_r1475612319

**Pull request merged**
