### PR TITLE
fix[ops]: use host network configuration

### PR DESCRIPTION
**Pull request by ben-chain**
**Description**
@tynes spent some time with me yesterday debugging https://github.com/ethereum-optimism/optimism/issues/570.  It appears to be a networking bug in docker--using the host network fixed it.

**Additional context**
This is not necessarily a clean-looking solution, so this might just spur some discussion on how to solve the underlying network bug, but I was asked to open as a PR.

**Metadata**
- Fixes https://github.com/ethereum-optimism/optimism/issues/570

### CODE REVIEW

**Comment by ben-chain** [comment]
Requires an update to the URLs in `OptimismEnv` for integration to work -- converted to draft until then.

**Comment by K-Ho** [comment]
@ben-chain is there another PR blocking this?

**Comment by TransmissionsDev** [comment]
This is probs already known but the DTL seems to die near startup when using this config which causes l2geth to shutdown as well:

Screen Shot 2021-04-27 at 5 54 13 PM


Screen Shot 2021-04-27 at 5 53 44 PM

**Comment by tynes** [comment]
@TransmissionsDev I believe there is a bug in the latest version of docker for mac that is related to the docker networking not working correctly. Earlier versions of docker for mac are known to work

**Comment by TransmissionsDev** [comment]
> @TransmissionsDev I believe there is a bug in the latest version of docker for mac that is related to the docker networking not working correctly. Earlier versions of docker for mac are known to work

Interesting thanks for the heads up. Will try downgrading.

**Comment by ben-chain** [comment]
Yeah thanks for that @TransmissionsDev , I have that replicated on my machine--looking into it!

**Comment by TransmissionsDev** [comment]
@tynes Unfortunately I don't think I can downgrade, older versions of docker desktop don't seem to support Apple Silicon 😭

**Comment by platocrat** [comment]
fwiw, my version of Docker Desktop is 3.3.1 (63152).
My versions of `docker` and `docker-compose`:
```
Docker version 20.10.5, build 55c4c88
docker-compose version 1.29.0, build 07737305
```

I also only let Docker Desktop manage my `docker` and `docker-compose` versions.

**Comment by gakonst** [comment]
Closing as this does not seem like a change we'll be adopting.

**Comment by tynes** [comment]
@gakonst We need a real solution for this, thinking https://github.com/ethereum-optimism/optimism/issues/677 is the solution

**Pull request closed without merging**
