### PR TITLE
feat: Add dai to indexer

### PR DESCRIPTION
**Pull request by roninjin10**
We had this commented out before.   I could not find a good reason why.  It's been commented out since genesis https://github.com/ethereum-optimism/optimism/commit/08385220de46c8abf3ef63605e86e90fb481ce50

### CODE REVIEW

**Comment by roninjin10** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #5740** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/5740" target="_blank">Graphite</a> 
    * **PR #5741** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/5741" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/optimism/5741?utm_source=stack-comment).

**Comment by tynes** [comment]
Generally looks good to me

**Review by tarunkhasnavis — APPROVED** [review]
lgtm!

**Review by hamdiallam — APPROVED** [review]
strange it was commented out. It's not commented out on L1

**Pull request merged**
