### PR TITLE
chore(proxyd): update not allowed status code to -32601

### PR DESCRIPTION
**Pull request by danyalprout**
**Description**

**As this is a breaking change, it may not be worth merging -- however I figured it was worth opening for discussion.**

This PR updates the not allowed status code from `-32001` to `-32601`. This brings proxyd inline with the geth [not found error status](https://github.com/ethereum-optimism/op-geth/blob/6aa2348118138a4f7021208ffaf8582d73169ba1/rpc/errors.go#L88) and is more consistent with other RPC endpoints.

It's also appears to be more consistent with most of RPC providers. I sent `debug_getRawBlock` requests to several public Optimism RPC endpoints and noted the responses below.

| RPC                                         | Status |
|---------------------------------------------|--------|
| https://optimism.gateway.tenderly.co        | -32601 |
| https://1rpc.io/op                          | -32601 |
| https://optimism-rpc.publicnode.com         | -32601 |
| https://optimism.llamarpc.com               | -32603 |
| https://optimism-mainnet.public.blastapi.io | -32601 |
| https://mainnet.optimism.io                 | -32001 |
| https://optimism.drpc.org                   | 32601  |
| https://rpc.ankr.com/optimism               | -32601 |

**Tests**

Updated the existing integration test responses.

### CODE REVIEW

**Review by roninjin10 — APPROVED** [review]
I support this change but it will need approval from devops

**Comment by trianglesphere** [comment]
We would also need to update https://github.com/ethereum-optimism/optimism/blob/d5b1b7541c0ff0e175772a28e35d0032be1fa1fc/op-service/sources/types.go#L328, but I'm supportive of this idea

**Comment by danyalprout** [comment]
Thanks for the feedback 🙏 

@trianglesphere taking a look at that code it appears to [already check](https://github.com/ethereum-optimism/optimism/blob/d5b1b7541c0ff0e175772a28e35d0032be1fa1fc/op-service/sources/types.go#L332) for the updated status code `-32601`. Which I think should result in the correct check.

Just wanted to confirm there's nothing else we need to change there.

**Comment by felipe-op** [comment]
lgtm, but since this customer-facing change may break protocol I also would like to have a +1 from devrel and node teams before merging

**Review by felipe-op — APPROVED** [review]

**Review by trianglesphere — APPROVED** [review]

**Comment by sbvegan** [comment]
Okay this makes sense to me. Before I approve it, let me check with the team and see if there's some second order effects I'm not considering.

**Review by sbvegan — APPROVED** [review]

**Pull request merged**
