### PR TITLE
op-node: Document metrics

### PR DESCRIPTION
**Pull request by mslipper**
Adds a library in `op-service` to act as a drop-in replacement for `promauto.With` that makes metrics self-documenting. The library is hooked up to the `op-node`. Docs can be generated by running `op-node doc metrics`. Both JSON and Markdown output formats are supported.

I made this to start addressing some of the concerns we've been seeing around sync time, and experiment with ways to make maintaining our documentation easier. RPC metrics are critical to debugging sync performance issues, so it's important that we make it as simple as possible for node operators to get started collecting them.

Example output for the Markdown format is below:

|                       METRIC                        |                                           DESCRIPTION                                            |    LABELS    |   TYPE    |
|-----------------------------------------------------|--------------------------------------------------------------------------------------------------|--------------|-----------|
| op_node_default_info                                | Pseudo-metric tracking version and config info                                                   | version      | gauge     |
| op_node_default_up                                  | 1 if the op node has finished starting up                                                        |              | gauge     |
| op_node_default_rpc_server_requests_total           | Total requests to the RPC server                                                                 | method       | counter   |
| op_node_default_rpc_server_request_duration_seconds | Histogram of RPC server request durations                                                        | method       | histogram |
| op_node_default_rpc_client_requests_total           | Total RPC requests initiated by the opnode's RPC client                                          | method       | counter   |
| op_node_default_rpc_client_request_duration_seconds | Histogram of RPC client request durations                                                        | method       | histogram |
| op_node_default_rpc_client_responses_total          | Total RPC request responses received by the opnode's RPC client                                  | method,error | counter   |
| op_node_default_l1_source_cache_size                | L1 Source cache cache size                                                                       | type         | gauge     |
| op_node_default_l1_source_cache_get                 | L1 Source cache lookups, hitting or not                                                          | type,hit     | counter   |
| op_node_default_l1_source_cache_add                 | L1 Source cache additions, evicting previous values or not                                       | type,evicted | counter   |
| op_node_default_l2_source_cache_size                | L2 Source cache cache size                                                                       | type         | gauge     |
| op_node_default_l2_source_cache_get                 | L2 Source cache lookups, hitting or not                                                          | type,hit     | counter   |
| op_node_default_l2_source_cache_add                 | L2 Source cache additions, evicting previous values or not                                       | type,evicted | counter   |
| op_node_default_derivation_idle                     | 1 if the derivation pipeline is idle                                                             |              | gauge     |
| op_node_default_pipeline_resets_total               | Count of derivation pipeline resets events                                                       |              | counter   |
| op_node_default_last_pipeline_resets_unix           | Timestamp of last derivation pipeline resets event                                               |              | gauge     |
| op_node_default_unsafe_payloads_total               | Count of unsafe payloads events                                                                  |              | counter   |
| op_node_default_last_unsafe_payloads_unix           | Timestamp of last unsafe payloads event                                                          |              | gauge     |
| op_node_default_derivation_errors_total             | Count of derivation errors events                                                                |              | counter   |
| op_node_default_last_derivation_errors_unix         | Timestamp of last derivation errors event                                                        |              | gauge     |
| op_node_default_sequencing_errors_total             | Count of sequencing errors events                                                                |              | counter   |
| op_node_default_last_sequencing_errors_unix         | Timestamp of last sequencing errors event                                                        |              | gauge     |
| op_node_default_publishing_errors_total             | Count of p2p publishing errors events                                                            |              | counter   |
| op_node_default_last_publishing_errors_unix         | Timestamp of last p2p publishing errors event                                                    |              | gauge     |
| op_node_default_unsafe_payloads_buffer_len          | Number of buffered L2 unsafe payloads                                                            |              | gauge     |
| op_node_default_unsafe_payloads_buffer_mem_size     | Total estimated memory size of buffered L2 unsafe payloads                                       |              | gauge     |
| op_node_default_refs_number                         | Gauge representing the different L1/L2 reference block numbers                                   | layer,type   | gauge     |
| op_node_default_refs_time                           | Gauge representing the different L1/L2 reference block timestamps                                | layer,type   | gauge     |
| op_node_default_refs_hash                           | Gauge representing the different L1/L2 reference block hashes truncated to float values          | layer,type   | gauge     |
| op_node_default_refs_seqnr                          | Gauge representing the different L2 reference sequence numbers                                   | type         | gauge     |
| op_node_default_refs_latency                        | Gauge representing the different L1/L2 reference block timestamps minus current time, in seconds | layer,type   | gauge     |
| op_node_default_l1_reorg_depth                      | Histogram of L1 Reorg Depths                                                                     |              | histogram |
| op_node_default_transactions_sequenced_total        | Count of total transactions sequenced                                                            |              | gauge     |
| op_node_default_p2p_peer_count                      | Count of currently connected p2p peers                                                           |              | gauge     |
| op_node_default_p2p_stream_count                    | Count of currently connected p2p streams                                                         |              | gauge     |
| op_node_default_p2p_gossip_events_total             | Count of gossip events by type                                                                   | type         | counter   |
| op_node_default_p2p_bandwidth_bytes_total           | P2P bandwidth by direction                                                                       | direction    | gauge     |
| op_node_default_sequencer_building_diff_seconds     | Histogram of Sequencer building time, minus block time                                           |              | histogram |
| op_node_default_sequencer_building_diff_total       | Number of sequencer block building jobs                                                          |              | counter   |
| op_node_default_sequencer_sealing_seconds           | Histogram of Sequencer block sealing time                                                        |              | histogram |
| op_node_default_sequencer_sealing_total             | Number of sequencer block sealing jobs                                                           |              | counter   |

### CODE REVIEW

**Review by protolambda — COMMENTED** [review]
This is really neat, is there anything that's blocking this for review (it's in draft mode)?

**Comment by mslipper** [comment]
I'm good to ship this! Just need to add the temporary `replace` statements to make the build pass.

**Comment by protolambda** [comment]
>  Just need to add the temporary replace statements to make the build pass.

Because of the op-service changes? Should we merge the op-service changes, make an op-service release, and then merge the op-node changes?

**Comment by mslipper** [comment]
Never mind may have just been a flake.

**Review by tynes — APPROVED** [review]
I tried this locally and can confirm that it works. Slight nit at no godoc for the factory code but looks good to me

**Pull request merged**
