### PR TITLE
api: estimate gas logging

### PR DESCRIPTION
**Pull request by tynes**
**Description**
This PR will add the gas used into the logline for `eth_estimateGas` so that we can see how much gas transactions are using

### CODE REVIEW

**Comment by gakonst** [comment]
@tynes what's the status of this? Is this a feature we want on master? Can imagine it'd generate a lot of redundant logs.

**Comment by tynes** [comment]
Lets tag this as "Do not merge", this branch is useful for debugging the problems we have been seeing recently when `gasPrice` is not set to 0.

We have determined that 2 instances of the `eth_estimateGas` bug were due to user failure, in particular not setting the `from`. We haven't confirmed that it is a user problem on the side of the Synthetix oracle, and we still see the logline `gas required exceeds allowance (%d) or always failing transaction` in the production logs.

We forked geth before the revert messages would be passed back through the RPC, see https://github.com/ethereum/go-ethereum/pull/21083/

> Can imagine it'd generate a lot of redundant logs.

This adds no additional loglines, just adds a single additional value to a logline that already exists

**Comment by tynes** [comment]
@K-Ho I have rebased and added an additional commit on top of this PR. It does 2 things:
- logs the estimated gas amount which will differentiate always failing txs from txs that are actually out of gas 27ccb560ad70ad3b13a04fc4f1485302e168e067
- logs the internal variables of the estimate gas equation and add error wrappers to know exactly where the error is happening 9c4242811bcebda9a46e02512aa69dd240a92845

**Comment by tynes** [comment]
The transaction fees on L2 are currently overpriced on Kovan and underpriced on Mainnet. @K-Ho can you provide an update?

Maybe we do want the commits that add the updated logs? 2f6b0ecb78a423315a9c6a83958153255b3295e5 is now part of https://github.com/ethereum-optimism/optimism/pull/519, so that will be removed from this branch when it gets rebased again
This branch is continued to be used for debugging

**Comment by tynes** [comment]
Going to close this because it hasn't been used in awhile

**Pull request closed without merging**
