### PR TITLE
Lower local rollup timestamp refresh

### PR DESCRIPTION
**Pull request by K-Ho**
**Description**
Currently, when doing a local `docker-compose up`, the `ROLLUP_TIMESTAMP_REFRESH` is not set, so it defaults to 3 minutes. This means that the `block.timestamp` and `block.number` will only update once ever 3 minutes when testing locally. This PR lowers that to 500ms.

### CODE REVIEW

**Review by snario — APPROVED** [review]
What motivated this?

**Review by tynes — CHANGES_REQUESTED** [review]
@snario We should try to approve after we are sure all tests are working

Having it so low creates a race condition, I think that we should up it until the race condition goes away. I think `10s` should be good

**Comment by K-Ho** [comment]
> What motivated this?

Motivated by Synthetix's tests which rely on `block.timestamp` - if we only update it every 3 minutes, their tests will take forever

**Review by platocrat — APPROVED** [review]

**Review by tynes — APPROVED** [review]

**Review by tynes — CHANGES_REQUESTED** [review]
Could you add a changeset to this for `ops`?

**Review by tynes — APPROVED** [review]

**Pull request merged**
