### PR TITLE
fix: update Dockerfile.packages

### PR DESCRIPTION
**Pull request by smartcontracts**
We recently updated ci-builder so this needs to be updated too.

### CODE REVIEW

**Review by Inphi — APPROVED** [review]
any plans to deprecate ci-builder if it's no longer used for build tooling?

**Comment by smartcontracts** [comment]
> any plans to deprecate ci-builder if it's no longer used for build tooling?

I believe so cc @mslipper

**Comment by tynes** [comment]
Where do we use `Dockerfile.packages` now?

**Comment by smartcontracts** [comment]
> Where do we use `Dockerfile.packages` now?

We removed it in another PR

**Pull request closed without merging**
