### PR TITLE
contracts-bedrock: Bindings script to prevent Circleci breakage

### PR DESCRIPTION
**Pull request by refcell**
**Overview**

Adds a simple `bindings` script inside `packages/contracts-bedrock` to generate contract bindings in `op-bindings`.

### CODE REVIEW

**Comment by tynes** [comment]
Hmm what exactly is this fixing?

**Comment by refcell** [comment]
> Hmm what exactly is this fixing?

Just adds a bindings script to the package.json to easily generate bindings after changing contracts without having to jump from `packages/contracts-bedrock` to `op-bindings`.

Not necessary, just for convenience.

**Comment by tynes** [comment]
> > Hmm what exactly is this fixing?
> 
> Just adds a bindings script to the package.json to easily generate bindings after changing contracts without having to jump from `packages/contracts-bedrock` to `op-bindings`.
> 
> Not necessary, just for convenience.

Ah got it, not opposed to having this merged :)

**Review by tynes — APPROVED** [review]

**Review by tynes — APPROVED** [review]

**Comment by refcell** [comment]
@mergifyio requeue

**Comment by refcell** [comment]
@mergifyio requeue

**Review by tynes — APPROVED** [review]

**Pull request merged**
