### PR TITLE
Add forge and output oracle

### PR DESCRIPTION
**Pull request by maurelian**
This is a PR on a new feature branch to be used for migrating the L2OutputOracle contract into the monorepo. 

It makes changes to some of the config, such as the contracts package.json and relevant ignore files.
As for contracts, it does not yet touch any of the pre-existing ones.

### CODE REVIEW

**Comment by tynes** [comment]
I think we need a `git submodule update --install` as part of `yarn install`

**Comment by mslipper** [comment]
CI is failing - I think we need to exclude the Forge test files from Hardhat compilation.

**Comment by maurelian** [comment]
> CI is failing - I think we need to exclude the Forge test files from Hardhat compilation.

I think it's OK to have hh build them, as long as the submodules are installed per @tynes suggestion.

**Comment by tynes** [comment]
Looks like a linting error:

```
/root/project/packages/contracts/.eslintrc.js
  6:10  warning  Insert `,`  prettier/prettier
```

**Comment by tynes** [comment]
The docker build is now failing because of the post install hook since the `.git` isn't copied into the docker image, I think a way around this would be to do `git submodule update --init || exit 0`

```
#17 71.45 Command: git submodule update --init
``

**Pull request closed without merging**
