### PR TITLE
feat(ctb): use Ownable for ProxyAdmin

### PR DESCRIPTION
**Pull request by smartcontracts**
**Description**
Has ProxyAdmin use Ownable instead of Owned to make sure we're only using one library for ownership.

### CODE REVIEW

**Review by maurelian — APPROVED** [review]

**Review by tynes — APPROVED** [review]

**Comment by mslipper** [comment]
Can you update the storage snapshot @smartcontracts ?

**Comment by smartcontracts** [comment]
@mergifyio requeue

**Comment by tynes** [comment]
I'd like to rebase this on top of https://github.com/ethereum-optimism/optimism/pull/3916 once its merged

**Comment by tynes** [comment]
Going to need to update the indexer tests as well

```
bedrock_test.go:42: 
        	Error Trace:	/root/project/indexer/integration_tests/bedrock_test.go:42
        	Error:      	Received unexpected error:
        	            	ProxyAdmin: storage layout entry for _owner not found
        	Test:       	TestBedrockIndexer
```

**Comment by smartcontracts** [comment]
> Going to need to update the indexer tests as well
> 
> ```
> bedrock_test.go:42: 
>         	Error Trace:	/root/project/indexer/integration_tests/bedrock_test.go:42
>         	Error:      	Received unexpected error:
>         	            	ProxyAdmin: storage layout entry for _owner not found
>         	Test:       	TestBedrockIndexer
> ```

Do you know where this is getting "owner" from?

**Pull request merged**
