### PR TITLE
maintenance: standardize license usage

### LINKED ISSUE #860: Duplicate LICENSE.txt within all packages
**Is your feature request related to a problem? Please describe.**
We currently only supply a license at the top level of this monorepo. Since people might want to use the underlying packages individually, we should also attach a copy of the license to each individual package.

**Describe the solution you'd like**
Add a copy of our LICENSE.txt file to each package that doesn't currently have it:
* `smock`
* `message-relayer`
* `batch-submitter`
* `common-ts`

### PR DESCRIPTION
**Pull request by smartcontracts**
**Description**
Standardizes usage of our MIT license so that we:
1. Have a copy of our license within each sub-package
2. Use the correct author name and license in all package.json files.

**Metadata**
- Fixes #860

### CODE REVIEW

**Comment by tynes** [comment]
Can you rename all of the `LICENSE.txt`s to just `LICENSE`? This is usually how projects do it

- https://github.com/NLnetLabs/unbound/blob/master/LICENSE
- https://github.com/kubernetes/kubernetes/blob/master/LICENSE

**Review by tynes — CHANGES_REQUESTED** [review]
Rename and i'll approve

**Comment by smartcontracts** [comment]
> Can you rename all of the LICENSE.txts to just LICENSE? This is usually how projects do it

Problem with just `LICENSE` is that files without an extension often don't display correctly on windows. I'm pretty sure windows file explorer doesn't display these files at all without some extra effort. Plenty of projects use the `.txt` extension, don't think it makes a huge difference.

**Comment by smartcontracts** [comment]
From GitHub docs: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#determining-the-location-of-your-license

Screen Shot 2021-05-13 at 12 14 43 PM

**Review by tynes — APPROVED** [review]

**Pull request merged**
