### PR TITLE
contracts-bedrock: delete mainnet deployments

### PR DESCRIPTION
**Pull request by tynes**
**Description**

As part of https://github.com/ethereum-optimism/optimism/commit/6b1aa1e7de5d094954b6866f5605078b1ad81914
for some reason the `mainnet` directory was not deleted. This commit
deletes that directory as well. The source of truth for the deployments
is now in the `superchain-registry` repo.

When new contracts are deployed, their contract addresses can be found
there. Specific releases of smart contracts will contain the exact ABIs
for the deployed contracts at a release. These releases can be found
with git tags in the ethereum-optimism github repo.

### CODE REVIEW

**Comment by tynes** [comment]
Not sure why this is failing, will need to investigate

**Comment by mslipper** [comment]
@tynes the `deployments` directory also gets deleted with this PR, which is making the `devnet-allocs` job fail.

**Comment by tynes** [comment]
> @tynes the `deployments` directory also gets deleted with this PR, which is making the `devnet-allocs` job fail.

Thanks for the comment, pushed a commit that fixes this.

Eventually should deprecate the concept of `deployments` completely and instead have the files all outputted to configurable locations

**Comment by tynes** [comment]
I addressed the issue with this PR and it now passes as expected

**Review by mds1 — APPROVED** [review]
> Specific releases of smart contracts will contain the exact ABIs
for the deployed contracts at a release

Is this the plan? The [existing release](https://github.com/ethereum-optimism/optimism/releases/tag/op-contracts%2Fv1.2.0-rc.1) that @maurelian created does not include any artifacts

**Comment by tynes** [comment]
> > Specific releases of smart contracts will contain the exact ABIs
> > for the deployed contracts at a release
> 
> Is this the plan? The [existing release](https://github.com/ethereum-optimism/optimism/releases/tag/op-contracts%2Fv1.2.0-rc.1) that @maurelian created does not include any artifacts

The [commit hash](https://github.com/ethereum-optimism/optimism/tree/856c08bf84d9aa829d1e764fc8e9a37d41960ba0) does include the ABIs committed into the repo, this is what I meant in that statement. I wouldn't be opposed to including the JSON itself in the tarball on the tag page (didn't download it so idk what is in there) but doing so should be easy for devs to consume to build bindings

**Pull request merged**
