### PR TITLE
feat(op-challenger): Rollup RPC Challenger Flag

### PR DESCRIPTION
**Pull request by refcell**
**Description**

Introduces a `--rollup-rpc` flag to the challenger for the `output_cannon` trace type done in #7273.

Notice, the naming follows the flag convention in the `op-proposer` called `--rollup-rpc` as opposed
to `--l2-consensus`. If this alternative naming is intentional, can change it.

**Metadata**

Fixes https://github.com/ethereum-optimism/client-pod/issues/40

### CODE REVIEW

**Comment by refcell** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #7273** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/7273" target="_blank">Graphite</a> 
    * **PR #7274** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/7274" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/optimism/7274?utm_source=stack-comment).

**Review by trianglesphere — APPROVED** [review]

**Review by Inphi — COMMENTED** [review]
I don't see the new config being used. Is there a follow up PR to this?

**Comment by refcell** [comment]
> I don't see the new config being used. Is there a follow up PR to this?

**Comment by refcell** [comment]
> I don't see the new config being used. Is there a follow up PR to this?

Yes, this adds the flag that will be used to construct the output trace provider in https://github.com/ethereum-optimism/optimism/pull/7272

If you look at that pr, it dials the rpc rollup node with a given url, which we will need to bring in from the flag.

**Review by Inphi — APPROVED** [review]

**Pull request merged**
