### PR TITLE
cannon: Fix the error usage in cannon

### PR DESCRIPTION
**Pull request by wissyLeeei**
Fix some error usage in cannon ⚡️

### CODE REVIEW

**Review by ajsutton — APPROVED** [review]
Approved, but for the record I don't think these kinds of changes are worth making. Both forms work perfectly well and there's no reason to be concerned about the tiny performance different in these cases.

**Comment by wissyLeeei** [comment]
The auto merge seems not working.

**Comment by ajsutton** [comment]
Ah sorry about that, I didn't notice the test flake.  Could you rebase this on top of the latest develop to fix the merge conflict please?

**Comment by wissyLeeei** [comment]
Sure, rebased now @ajsutton

**Review by ajsutton — APPROVED** [review]

**Pull request merged**
