### PR TITLE
fix: reorg for clear proxy usage

### LINKED ISSUE #898: Ensure addresses of implementation contracts are not published in documentation
**Is your feature request related to a problem? Please describe.**

Related to #547. 

We should review our public docs, and ensure that we do not have any references to implementation contracts, especially gateway/bridge contracts.

IIRC, the Gateway and Messenger contracts were the only ones using a Proxy upgradability model.

### PR DESCRIPTION
**Pull request by platocrat**
**Description**
Fixes #898 by adding a secondary table for proxied contracts and a note above the new table, for each network in the [`optimism/packages/contracts/deployments/README.md`](https://github.com/ethereum-optimism/optimism/blob/master/packages/contracts/deployments/README.md)

### CODE REVIEW

**Comment by tynes** [comment]
This file is autogenerated so it should not be edited manually. If you want to change it, you need to update the script that generates it

**Comment by smartcontracts** [comment]
Script here: https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/scripts/generate-markdown.js

**Review by smartcontracts — CHANGES_REQUESTED** [review]
Change should be made by editing the script that generates this file, located here: https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts/scripts/generate-markdown.js

**Comment by platocrat** [comment]
woops, didn't mean to close this

**Comment by platocrat** [comment]
I think we're good now

**Comment by smartcontracts** [comment]
Hmmm. I think the following might be a bit easier to follow:

1. Put the proxies back in the primary list
2. Remove the implementation contracts from the primary list
3. Put the implementation contracts inside of an html comment in the markdown so we can still see them but they aren't displayed publicly, like:

```md
<!--
Implementation addresses. DO NOT use these addresses directly. Use their proxied counterparts seen above.

... addresses go here
-->
```

**Review by smartcontracts — APPROVED** [review]

**Pull request merged**
