### PR TITLE
feat(ctb): DisputeGameFactory Deploy Scripts

### PR DESCRIPTION
**Pull request by refcell**
**Description**

Adds deploy scripts for the `DisputeGameFactory` that are only run
on the devnet (as matched by the deploy config l1 chain id).

**Metadata**

Fixes CLI-4093

### CODE REVIEW

**Comment by refcell** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #6028** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/6028" target="_blank">Graphite</a> 
    * **PR #6029** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/6029" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/optimism/6029?utm_source=stack-comment).

**Comment by refcell** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #6028** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/6028" target="_blank">Graphite</a> 
    * **PR #6029** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/6029" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/optimism/6029?utm_source=stack-comment).

**Comment by tynes** [comment]
This will need a rebase on `develop` once https://github.com/ethereum-optimism/optimism/pull/6028 is merged

**Review by clabby — APPROVED** [review]
LGTM

**Review by tynes — APPROVED** [review]

**Pull request merged**
