### PR TITLE
Update L2StandardTokenFactory deployment artefact and script

### PR DESCRIPTION
**Pull request by elenadimitrova**
The standard L2 ERC20 Token factory: `OVM_L2StandardTokenFactory` was deployed to:

`0x50EB44e3a68f1963278b4c74c6c343508d31704C` Optimism Kovan
`0x2e985AcD6C8Fa033A4c5209b0140940E24da7C5C` Optimism Mainnet

Here we add the deployment artefact to source and also update the deployment script to the one actually used in deployment.

### CODE REVIEW

**Comment by tynes** [comment]
Did you deploy the contract with `npx hardhat deploy`? It looks like the file was refactored away from using the hardhat deploy scheme

**Comment by tynes** [comment]
I understand that the hardhat deploy syntax is a bit much, but I'm curious how the artifact was generated without using the `deploy` function if this refactored script is the thing that was used to deploy

**Comment by elenadimitrova** [comment]
The artifacts are generated from `hardhat compile` not from `deploy` which probably just runs `compile` before it deploys.
On the other point, I had problems running the previous version of the script and updated it, thought it's best to have the script that was actually used in the deployment. Also the script matches their documentation here https://hardhat.org/tutorial/deploying-to-a-live-network.html I couldn't get the other one to work.

**Comment by tynes** [comment]
I'm ok with merging this with the deploy script non standard relative to the others, we also technically do not need a changeset as this artifact is not pulled in and exported here: https://github.com/ethereum-optimism/optimism/blob/7de8269bfb2a1ca42381e9955676c6ab42ecd968/packages/contracts/src/contract-data.ts#L123

**Review by tynes — APPROVED** [review]

**Pull request merged**
