### PR TITLE
feat: ban deposits interop

### PR DESCRIPTION
**Pull request by 0xDiscotech**
**Description**

Added benchmark for the `setValuesEcotone()` and `setValuesIsthmus()` functions.

**Additional context**

https://github.com/ethereum-optimism/optimism/pull/11362#pullrequestreview-2226031139

### CODE REVIEW

**Comment by tynes** [comment]
To be backwards compatible, we should follow this document: https://github.com/ethereum-optimism/design-docs/blob/main/smart-contract-feature-development.md

This would mean we create a L1BlockInterop contract (we may already have one)

**Comment by tynes** [comment]
Did you mean to make this just a benchmark PR? If so this looks good to me

**Comment by 0xDiscotech** [comment]
> Did you mean to make this just a benchmark PR? If so this looks good to me

Yes! The idea is to add it that branch, so it can be reviewed on this PR: https://github.com/ethereum-optimism/optimism/pull/11362
I had to push it from our repo because I don't have permission to push directly. But the idea is that @skeletor_spaceman merges it into his branch the solidity files have the requested changes :)

**Comment by 0xDiscotech** [comment]
> This would mean we create a L1BlockInterop contract (we may already have one)

Yes, this was also pushed to that same branch. The `L1BlockInterop` already exists so we basically added the new functions on it!

But of course, if something is wrong or missing, let us know so we can push the changes

**Comment by tynes** [comment]
> > This would mean we create a L1BlockInterop contract (we may already have one)
> 
> Yes, this was also pushed to that same branch. The `L1BlockInterop` already exists so we basically added the new functions on it!
> 
> But of course, if something is wrong or missing, let us know so we can push the changes

Ah ok, apologies if i misread something!

Thank you for breaking this up into a small PR, i mistook this as for onto develop

**Review by tynes — APPROVED** [review]

**Review by skeletor-spaceman — APPROVED** [review]

**Pull request merged**
