### PR TITLE
fix: update wallet.sh script

### PR DESCRIPTION
**Pull request by barnabasbusa**
This PR will enable a user to pipe the output of wallet.sh directly into env file, without having to remove the first line (otherwise the env var will be invalid).

### CODE REVIEW

**Review by tynes — APPROVED** [review]

**Comment by tynes** [comment]
@barnabasbusa This needs to be rebased as the `bedrock-markdown` CI job has been removed. The other failures are flakes or based on old CI

**Comment by barnabasbusa** [comment]
should it be rebased on develop branch? Is this branch no longer maintained?

**Comment by tynes** [comment]
> should it be rebased on develop branch? Is this branch no longer maintained?

Yes it should be rebased on `develop`, everything happens on `develop` these days

**Comment by barnabasbusa** [comment]
Would be cool to mention this in the [guide](https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup#build-the-optimism-monorepo). Probably worth updating the guide to reference the default develop branch.

**Pull request merged**
