### PR TITLE
avoid pointless propose when op-batcher is lagging behind sequencing window

### PR DESCRIPTION
**Pull request by zhiqiangxu**
when `syncStatus.UnsafeL2.L1Origin.Number >= syncStatus.SafeL2.L1Origin.Number+rollupConfig.SeqWindowSize`, `op-node` is deriving empty batch, it's a waste of gas to continue proposing when this happens.

### CODE REVIEW

**Comment by geoknee** [comment]
@zhiqiangxu can you explain more why you think it is pointless to propose when the sequencing window has expired?

**Comment by zhiqiangxu** [comment]
> @zhiqiangxu can you explain more why you think it is pointless to propose when the sequencing window has expired?

Because when this happens, op-batcher most likely won't be able to publish all `(safe l2 block, unsafe l2 block]` in time, so it's pointless to propose output root, which is the result of executing `(safe l2 block, unsafe l2 block]`.

In other words, it's useless to propose execution result when the corresponding execution data is unavailable.

**Comment by ajsutton** [comment]
The output root proposal must be from a safe block, so even if the sequencing window has expired it is still valid to publish output roots. Since withdrawals can be initiated from deposit transactions such output roots may be required to prove those withdrawals against as well.

Also, the difference in L1 origin between safe and unsafe blocks isn't the right measure to determine if the sequencing window has elapsed - it's possible that the sequencer just hasn't caught up with processing already submitted batches and its safe head is lagging behind.

**Comment by zhiqiangxu** [comment]
@ajsutton thanks for correcting my assumption! I overlooked the `FetchCurrentBlockNumber` function, which only returns safe or finalized block number, not the latest unsafe block number. And "withdrawals can be initiated from deposit transactions" is a great reason to continue proposing even if the sequencing window is expired.

**Pull request closed without merging**
