### PR TITLE
refactor: remove redundant `IERC165` check

### PR DESCRIPTION
**Pull request by neutiyoo**
**Description**

The `supportsInterface` function in the `OptimismMintableERC721` contract includes redundant codes with `type(IERC165).interfaceId`. 

[OptimismMintableERC721.sol#L134-L146](https://github.com/ethereum-optimism/optimism/blob/1afd173e324fd55442f15075a30314e2497176ee/packages/contracts-bedrock/contracts/universal/OptimismMintableERC721.sol#L134-L146) 
```solidity
    function supportsInterface(bytes4 _interfaceId)
        public
        view
        override(ERC721Enumerable, IERC165)
        returns (bool)
    {
        bytes4 iface1 = type(IERC165).interfaceId;
        bytes4 iface2 = type(IOptimismMintableERC721).interfaceId;
        return
            _interfaceId == iface1 ||
            _interfaceId == iface2 ||
            super.supportsInterface(_interfaceId);
    }
```

`bytes4 iface1 = type(IERC165).interfaceId;` and `_interfaceId == iface1` are unnecessary. It's because `OptimismMintableERC721` inherits `ERC165` and `super.supportsInterface(_interfaceId);` is being used.

[OpenZeppelin ERC721Enumerable.sol#L30-L32](https://github.com/OpenZeppelin/openzeppelin-contracts/tree/6bd6b76d1156e20e45d1016f355d154141c7e5b9/contracts/token/ERC721/extensions/ERC721Enumerable.sol#L30-L32)
```solidity
    function supportsInterface(bytes4 interfaceId) public view virtual override(IERC165, ERC721) returns (bool) {
        return interfaceId == type(IERC721Enumerable).interfaceId || super.supportsInterface(interfaceId);
    }
```

[OpenZeppelin ERC721.sol#L52-L57](https://github.com/OpenZeppelin/openzeppelin-contracts/tree/6bd6b76d1156e20e45d1016f355d154141c7e5b9/contracts/token/ERC721/ERC721.sol#L52-L57)
```solidity
    function supportsInterface(bytes4 interfaceId) public view virtual override(ERC165, IERC165) returns (bool) {
        return
            interfaceId == type(IERC721).interfaceId ||
            interfaceId == type(IERC721Metadata).interfaceId ||
            super.supportsInterface(interfaceId);
    }
```

[OpenZeppelin ERC165.sol#L26-L28](https://github.com/OpenZeppelin/openzeppelin-contracts/tree/6bd6b76d1156e20e45d1016f355d154141c7e5b9/contracts/utils/introspection/ERC165.sol#L26-L28)
```solidity
    function supportsInterface(bytes4 interfaceId) public view virtual override returns (bool) {
        return interfaceId == type(IERC165).interfaceId;
    }
```

Therefore, the unnecessary codes can be safely removed without affecting the functionality of the contract.

NOTE: this change costs 
- `0.3%` more gas for `test_finalizeBridgeERC721_alreadyExists_reverts` (`29128` -> `29218`) 
- `0.04%` more gas for `test_finalizeBridgeERC721_succeeds` (`168970` -> `169045`)
-  `0.63%` less gas for `test_createOptimismMintableERC721_succeeds` (`2336687` -> `2321842`)

If this redundant `type(IERC165).interfaceId` check is intended, 
adding comment would be helpful for developers as the code can be more straightforward with comment.

**Tests**

This PR includes `supportsInterface` test for the following interfaces:
- `IOptimismMintableERC721`
- `IERC721Enumerable`
- `IERC721`
- `IERC165`

**Invariants**

**Additional context**

**Metadata**

**TODOs**

- [ ] Author or reviewer has added an entry to the [current release notes draft][RND], if appropriate.

[RND]: https://www.notion.so/oplabs/ded30107ceec41c88817e60322aa8d0a?v=b4a22cedb85a46a38c9be14e7c984953&pvs=4 "Release Notes"

### CODE REVIEW

**Comment by neutiyoo** [comment]
Gas snapshot diff

```
Diff in "L2ERC721Bridge_Test::test_finalizeBridgeERC721_alreadyExists_reverts()": consumed "(gas: 29203)" gas, expected "(gas: 29128)" gas 
Diff in "L2ERC721Bridge_Test::test_finalizeBridgeERC721_succeeds()": consumed "(gas: 169045)" gas, expected "(gas: 168970)" gas 
Diff in "OptimismMintableERC721Factory_Test::test_createOptimismMintableERC721_succeeds()": consumed "(gas: 2320442)" gas, expected "(gas: 2336687)" gas 
```

**Comment by tynes** [comment]
Thank you for the fix here. I would be willing to merge this if there is a test explicitly for the IERC165 interface

**Comment by neutiyoo** [comment]
Sure, I have included `supportsInterface` test for the following interfaces:
- `IOptimismMintableERC721`
- `IERC721Enumerable`
- `IERC721`
- `IERC165`

**Comment by tynes** [comment]
@neutiyoo I'm going to take over this PR to get it merged, thank you for your contribution!

**Pull request closed without merging**
