### PR TITLE
op-batcher/proposer: Increase sendTx timeout

### PR DESCRIPTION
**Pull request by trianglesphere**
**Description**

This will hopefully help with some of the send issues we've been seeing.
I'd like to wait a release cycle or two to include this so I can track down
other issues, but long term I think this is the right thing to do.

### CODE REVIEW

**Comment by refcell** [comment]
Why not just put these behind config variables with default values?

**Comment by refcell** [comment]
Can clamp the values in a runtime validation as well to require code changes for signification changes

**Comment by trianglesphere** [comment]
> Why not just put these behind config variables with default values?

Worth doing in the future once we have better tracking on where txns are (in mempool or if they never hit the mempool). For now we need these changes to be rolled out to increase stability.

**Review by refcell — APPROVED** [review]
LGTM

**Review by sebastianst — APPROVED** [review]
Also am in favor of putting this timeout into the TxMgrConfig soon, but should help as a quick fix.

**Pull request merged**
