### PR TITLE
fix: linter error failing ci

### PR DESCRIPTION
**Pull request by annieke**
**Description**
Noticed the failure in my other PR: https://github.com/ethereum-optimism/optimism/pull/735/checks?check_run_id=2511003570 Ran lint:fix in base repository and this was the fix.

**Additional context**
Any idea why tests passed before merging?

**Metadata**
- Fixes #[Link to Issue]

### CODE REVIEW

**Review by karlfloersch — APPROVED** [review]
LGTM! I did the same in my PR https://github.com/ethereum-optimism/optimism/pull/760 😄

**Comment by karlfloersch** [comment]
Oh wait unit tests are failing huh

**Comment by annieke** [comment]
> Oh wait unit tests are failing huh

@karlfloersch yes just asked in dev and @elenadimitrova is looking!

**Comment by tynes** [comment]
We have an error with `codechecks`

```
Run yarn codechecks
yarn run v1.22.10
$ /home/runner/work/optimism/optimism/node_modules/.bin/codechecks
CodeChecks Client v.0.1.10
https://codechecks.io

Executing 1 codechecks files
Error occured:  Provider should never be in fork mode and not in PR mode!
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by tynes** [comment]
Not exactly sure why codechecks was failing but we did get CI passing again on master so closing this

**Comment by maurelian** [comment]
It might be that the failure was caused by the diff in `yarn.lock` (prior to [this commit](https://github.com/ethereum-optimism/optimism/pull/760/commits/00462bd662c406fe657a5e089d51446e79dfc742#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de))?

**Pull request closed without merging**
