### PR TITLE
contracts-bedrock: forge-std v1.8.1

### PR DESCRIPTION
**Pull request by tynes**
**Description**

Updates to latest `forge-std` release to get access to the latest
cheatcodes with a nice API.

https://github.com/foundry-rs/forge-std/releases/tag/v1.8.1

### CODE REVIEW

**Review by protolambda — APPROVED** [review]
TYVM

**Review by Inphi — APPROVED** [review]

**Comment by tynes** [comment]
Massive amounts of compiler warnings, i think its because its going from app layer assertions to native assertions

**Comment by tynes** [comment]
This slightly reduced build time

2.39 on current branch
2.43 on develop

**Comment by tynes** [comment]
Maybe I am smol brain but https://github.com/foundry-rs/forge-std/pull/503#issuecomment-1930357988 isn't just working 🤔

**Comment by tynes** [comment]
The `OptimismPortal2` failing tests:

```
  [19128] OptimismPortal2_Test::test_initialize_succeeds()
    ├─ [489] 0xD64C5B1F2952CBC28Bd79EB02d3065BbA2696E3A::cfg() [staticcall]
    │   └─ ← [Return] DeployConfig: [0x9568d36E291c2C4c34fa5593fcE73715abEf6F9c]
    ├─ [2445] DeployConfig::superchainConfigGuardian() [staticcall]
    │   └─ ← [Return] 0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc
    ├─ [5166] OptimismPortalProxy::disputeGameFactory() [staticcall]
    │   ├─ [189] OptimismPortal::disputeGameFactory() [delegatecall]
    │   │   └─ ← [Revert] EvmError: Revert
    │   └─ ← [Revert] EvmError: Revert
    └─ ← [Revert] EvmError: Revert
```

Not sure why this would happen, looks like now its calling the portal and not the portal2?

edit: this was because the storage layout of the deploy config changed, so i removed the need to use a magic slot to set the value

**Pull request merged**
