### PR TITLE
feat: Add audits folder

### PR DESCRIPTION
**Pull request by maurelian**
**Description**

Adds our previous audits. 

Naming convention for the files is inspired by the [argent-wallet](https://github.com/argentlabs/argent-contracts/commit/f3a7ff9910951c652f4aec15c91e958776581a17#diff-2b294007c2df8c561200b0aa20c6f6ed67d7c5da7ee8487d94b15e73d8c65fee) repo, but references the components in scope rather than releases. This is necessary because the audits are generally not focused on the full system, and cannot all be tracked to a specific release. If desired, the OZ audit could be labeled as `regenesis/0.4.0`.

Fixes ENG-1712

### CODE REVIEW

**Review by elenadimitrova — COMMENTED** [review]
The idea of using the release number as the first text in the name is so that these are ordered chronologically which makes it easier to check the latest ones. Perhaps we should switch the naming to [yyyy_mm - Org - Scope] so 
"ECDSA Wallet - Dapphub - Nov2020.pdf" -> "2020_11 - Dapphub - ECDSA Wallet.pdf"

**Comment by tynes** [comment]
nit: spaces in filenames

**Comment by smartcontracts** [comment]
> nit: spaces in filenames

+1, I'd rather not deal with unexpected headaches as a result of having spaces in file names. Can just replace the spaces with underscores or something.

**Comment by maurelian** [comment]
OK, it's now using this format: `2020_11-Dapphub-ECDSA_Wallet.pdf`. 

The convention being `-` separates 'sections', `_` is a 'space'.

**Review by elenadimitrova — APPROVED** [review]

**Review by tynes — APPROVED** [review]

**Pull request merged**
