### PR TITLE
op-e2e: Adjust for updated op-geth API changes

### PR DESCRIPTION
**Pull request by ajsutton**
**Description**

Apply changes in the op-geth api resulting from https://github.com/ethereum-optimism/op-geth/pull/72

**Metadata**

Fix CLI-3647

### CODE REVIEW

**Comment by protolambda** [comment]
Update: we need to update monorepo go mod, dockerfiles and circleci to Go 1.19 before this can be merged. (about time, Go 1.20 is already out too). @ajsutton is looking into this :pray:

**Comment by ajsutton** [comment]
Updated only the bedrock docker images to go 1.19.  There are some non-bedrock things like l2geth that are still using go 1.18 in docker images. I'm inclined to leave them alone or update in a separate PR, but happy to update here if that's the usual pattern.

**Review by protolambda — APPROVED** [review]

**Comment by mslipper** [comment]
Failing op-chain-ops tests are cause for concern. Will pull this branch and see what's going on.

**Comment by ajsutton** [comment]
> Failing op-chain-ops tests are cause for concern. Will pull this branch and see what's going on.

Yeah it's an interesting one - they're passing for me locally.

**Comment by mslipper** [comment]
It's a rare data race in the migration code - unrelated to this PR. Pushing a fix now.

**Comment by mslipper** [comment]
https://github.com/ethereum-optimism/optimism/pull/5211 has the fix.

**Comment by ajsutton** [comment]
@mergify dequeue

**Comment by ajsutton** [comment]
@mergify unqueue

**Comment by ajsutton** [comment]
@mergify requeue

**Comment by ajsutton** [comment]
@mergify refresh

**Pull request merged**
