### PR TITLE
op-alt-da: fix some wrong spelling in alt-da

### PR DESCRIPTION
**Pull request by tanvirman**
💗

### CODE REVIEW

**Review by tynes — APPROVED** [review]
❤️

**Comment by tanvirman** [comment]
@tynes GM Sir, the merge bot was broken. 💗

**Comment by tynes** [comment]
> @tynes GM Sir, the merge bot was broken. 💗

Can you rebase this please? It will fix CI

**Comment by tanvirman** [comment]
> > @tynes GM Sir, the merge bot was broken. 💗
> 
> Can you rebase this please? It will fix CI

Done : )

**Comment by smartcontracts** [comment]
Hi, apologies for the delay here. I believe these have been fixed upstream. Closing this PR for now.

**Pull request closed without merging**
