### PR TITLE
fix: typos in documentation files

### PR DESCRIPTION
**Pull request by leopardracer**
This pull request contains changes to improve clarity, correctness and structure.

**Description correction:**
Corrected `proccessed` to `processed`
Corrected `transfered` to `transferred` x2.
Corrected `suprechain` to `superchain`.

Please review the changes and let me know if any additional changes are needed.

### CODE REVIEW

**Comment by mslipper** [comment]
/ci authorize https://github.com/ethereum-optimism/optimism/pull/13319/commits/e4ffd0d7ecf0891baf022d0b35798a281c6d6047

**Comment by leopardracer** [comment]
> /ci authorize https://github.com/ethereum-optimism/optimism/pull/13319/commits/e4ffd0d7ecf0891baf022d0b35798a281c6d6047

how to fix?

**Comment by mslipper** [comment]
@leopardracer please rebase

**Comment by mslipper** [comment]
/ci authorize https://github.com/ethereum-optimism/optimism/pull/13319/commits/59fbe0b03df7158db48bee5d8c7f903522166555

**Review by smartcontracts — APPROVED** [review]

**Pull request merged**
