### PR TITLE
feat(op-service):Persist RethDB instance in the global variable

### PR DESCRIPTION
**Pull request by Nickqiaoo**
A solution for https://github.com/ethereum-optimism/optimism/issues/8225, but persist the instance in the rust code.

### CODE REVIEW

**Comment by Nickqiaoo** [comment]
A better way is export a new init rust function to set the global variable, call the init function in NewRethDBReceiptsFetcher in Go.But the current solution can already solve the problem of repeated initialization.

**Comment by clabby** [comment]
This LGTM, nice idea. We need to re-enable the `rethdb-reader` tests in CI, will approve once we've re-enabled and rebased on `develop` 👍

**Comment by Nickqiaoo** [comment]
@clabby Hi! I see that this PR is going to be closed, can it be merged?🥹

**Comment by clabby** [comment]
> @clabby Hi! I see that this PR is going to be closed, can it be merged?🥹

Apologies for the delay here! Once #9692 is merged, we can rebase this and get it in :)

**Comment by clabby** [comment]
h/t @sebastianst, I think we should take a slightly different direction here. Right now, even though the `op-node` only needs 1 DB, the Go API allows for creating multiple `RethDBReceiptsFetcher`s. With the DB instance being a static global, each instance of the `RethDBReceiptsFetcher` would re-use the same DB instance after it was first initiated. Can we export an `open_db_read_only` function from the library and store it in the Go struct, so that each receipts fetcher holds on to a single instance of the DB?

**Comment by sebastianst** [comment]
Thanks @Nickqiaoo for working on this! And thanks @clabby yes a DB instance stored inside the `RethDBReceiptsFetchers` would be cleaner, to give better encapsulation and theoretically allow the creation of multiple readers for different db backends. Because that's what the API currently allows. I think it's also described like this in the original ticket at https://github.com/ethereum-optimism/optimism/issues/8225.

**Comment by Nickqiaoo** [comment]
> h/t @sebastianst, I think we should take a slightly different direction here. Right now, even though the `op-node` only needs 1 DB, the Go API allows for creating multiple `RethDBReceiptsFetcher`s. With the DB instance being a static global, each instance of the `RethDBReceiptsFetcher` would re-use the same DB instance after it was first initiated. Can we export an `open_db_read_only` function from the library and store it in the Go struct, so that each receipts fetcher holds on to a single instance of the DB?

Instance reuse is indeed a problem, I'll do it.

**Comment by sebastianst** [comment]
@Nickqiaoo are you still working on this?

**Comment by Nickqiaoo** [comment]
Sorry, i'am a little busy recently.I will do it this week.🫡

**Comment by Nickqiaoo** [comment]
> @Nickqiaoo are you still working on this?

Sorry, i'am a little busy recently.I will do it this week.🫡

**Comment by Nickqiaoo** [comment]
@sebastianst @clabby Hi, I create a new PR here https://github.com/ethereum-optimism/optimism/pull/9904

**Pull request closed without merging**
