### PR TITLE
Add dual integration tests to SNX test suite

### PR DESCRIPTION
**Pull request by K-Ho**
**Description**
Adds "dual" integration tests (deposits and withdraws) to the external SNX test suite workflow

Fixes OP-1128

### CODE REVIEW

**Comment by tynes** [comment]
Will be good to merge once we see it pass here: https://github.com/ethereum-optimism/optimism/actions/runs/1023991800

**Comment by tynes** [comment]
It ran out of memory, I think this needs to be split up into different tasks that run after each other

**Comment by K-Ho** [comment]
> It ran out of memory, I think this needs to be split up into different tasks that run after each other

looked like it didn't even get past spinning the Optimism stack up, re-running now

**Comment by tynes** [comment]
@K-Ho - Is this still useful?

**Comment by tynes** [comment]
@K-Ho Could you provide an update that includes:
1 - how to take advantage of this functionality?
2 - is this still useful?

**Comment by tynes** [comment]
@K-Ho Any updates on this?

**Comment by K-Ho** [comment]
@elenadimitrova is taking this over - she was getting issues running these tests (as was I) and is debugging with Synthetix in their discord

**Pull request closed without merging**
