### PR TITLE
fix(ctb): `LibKeccak` version bump

### PR DESCRIPTION
**Pull request by clabby**
## Overview

Bumps the version of `lib-keccak` in `contracts-bedrock` to [`0115edbbc60b5f702392caafc3a142061e6142fa`](https://github.com/ethereum-optimism/lib-keccak/commit/0115edbbc60b5f702392caafc3a142061e6142fa), which contains [a fix](https://github.com/ethereum-optimism/lib-keccak/pull/2) for a memory allocation edge case.

### CODE REVIEW

**Comment by clabby** [comment]
Current dependencies on/for this PR:
* `develop`
  * **PR #9167** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/9167?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/optimism/9167?utm_source=stack-comment).

**Review by refcell — APPROVED** [review]

**Comment by Ezra-Labs** [comment]
Hi, not sure what happened here, but I have again gone through the rollup tutorial again (will probably do several more times), and on the step for pnpm build, hitting a snag where the files in this specific folder aren't present after the git clone.

End of Terminal log for pnpm build:

       Error: 
       failed to resolve file: "/Users/davidowens/ent2/optimism/packages/contracts-bedrock/lib/clones-with-immutable-args/src/ClonesWithImmutableArgs.sol": No such file or directory (os error 2); check configured remappings.
           --> "/Users/davidowens/ent2/optimism/packages/contracts-bedrock/src/dispute/DisputeGameFactory.sol"
               "@cwia/ClonesWithImmutableArgs.sol"
        ELIFECYCLE  Command failed with exit code 1.
       
       

 ——————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for 8 projects (1m)
 
    ✔    2/3 succeeded [2 read from cache]
 
    ✖    1/3 targets failed, including the following:
         - nx run @eth-optimism/contracts-bedrock:build
 
   View structured, searchable error logs at https://nx.app/runs/1iSJIRlEeh

 ELIFECYCLE  Command failed with exit code 1.

**Comment by Ezra-Labs** [comment]
That specific folder is currently empty locally. After two attempts.

**Comment by clabby** [comment]
> That specific folder is currently empty locally. After two attempts.

Try to `cd` into `packages/contracts-bedrock` and `forge install` 😄

**Comment by Ezra-Labs** [comment]
done, no change.

"       > forge build
       
       Error: 
       failed to resolve file: "/Users/davidowens/ent2/optimism/packages/contracts-bedrock/lib/clones-with-immutable-args/src/ClonesWithImmutableArgs.sol": No such file or directory (os error 2); check configured remappings.
           --> "/Users/davidowens/ent2/optimism/packages/contracts-bedrock/src/dispute/DisputeGameFactory.sol"
               "@cwia/ClonesWithImmutableArgs.sol"
        ELIFECYCLE  Command failed with exit code 1.
       
       

 ——————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for 8 projects (3s)
 
    ✔    2/3 succeeded [2 read from cache]
 
    ✖    1/3 targets failed, including the following:
         - nx run @eth-optimism/contracts-bedrock:build
 
   View structured, searchable error logs at https://nx.app/runs/qHrAIGPiJk

 ELIFECYCLE  Command failed with exit code 1."

Ive gone through this tutorial several times in several directories in same manner, this is a new error not seen before.

**Comment by jin2255** [comment]
hi @Ezra-Labs 
did you fix the error, or same yet?
I've got same issue

**Pull request merged**
