### PR TITLE
Create a setup script for the integration tests

### LINKED ISSUE #1683: Create a setup script for the integration tests
**Is your feature request related to a problem? Please describe.**
We currently do not have a test setup script in the `integration-tests` package. As a result, we have to do things like this within multiple test scripts:

https://github.com/ethereum-optimism/optimism/blob/214473692184dbc1f0953a1e6078a9ab318a109f/integration-tests/test/fee-payment.spec.ts#L1-L3

I would prefer that we just use a setup script like we use in the `contracts` package:

https://github.com/ethereum-optimism/optimism/blob/214473692184dbc1f0953a1e6078a9ab318a109f/packages/contracts/test/setup.ts#L1-L10

You can see that we then just import `expect` from the setup script:

https://github.com/ethereum-optimism/optimism/blob/214473692184dbc1f0953a1e6078a9ab318a109f/packages/contracts/test/contracts/L1/rollup/CanonicalTransactionChain.spec.ts#L1

**Describe the solution you'd like**
See solution above. Please put the script inside `integration-tests/test/shared/setup.ts` and update the tests to import `expect` from the setup script instead of from `chai` directly.

**NOTE**: Please target the `regenesis/0.5.0` branch.

### PR DESCRIPTION
**Pull request by barrasso**
**Description**
Adds a test setup script, `shared/setup.ts`, in the `integration-tests` package.

**Additional context**
Updates the tests to import from the setup script instead of from chai and ethereum-waffle directly.

**Metadata**
- Closes #1683

### CODE REVIEW

**Comment by smartcontracts** [comment]
Haha, glad someone is finally picking up these issues! So nice to see this code get deleted :sweat_smile:

**Review by smartcontracts — APPROVED** [review]

**Review by tynes — APPROVED** [review]

**Comment by smartcontracts** [comment]
@barrasso would you mind just quickly rebasing this on top of the latest version of develop?

**Comment by barrasso** [comment]
> @barrasso would you mind just quickly rebasing this on top of the latest version of develop?

Done!

**Comment by smartcontracts** [comment]
Running CI, then let's get this merged!

**Pull request merged**
