### PR TITLE
test: improve test coverage for aliasing

### LINKED ISSUE #2054: Improve test coverage for address aliasing utils
This issue is part of a series of issues intended to get the test coverage of `core-utils` up to 100%. 

We use an address aliasing scheme to prevent certain attack vectors where a contract on L1 could impersonate a contract on L2 and vice versa. As part of this, we maintain utilities for clients to be able to compute the aliased version of a given contract address. [The utilities can be found here](https://github.com/ethereum-optimism/optimism/blob/develop/packages/core-utils/src/alias.ts). We're almost at 100% test coverage for this file but a few lines still need to be tested. [You can find a coverage report for this file here](https://app.codecov.io/gh/ethereum-optimism/optimism/blob/develop/packages/core-utils/src/alias.ts).

The goal of this issue is to add tests that cover the lines not covered within the linked coverage report. Should be pretty straightforward!

### PR DESCRIPTION
**Pull request by RasenGUY**
**Description**
This commit improves the test coverage for address aliasing to 100% in packages/core-utils/alias.spec.ts

**Additional context**
- added two additional error messages to check against

**Metadata**
- Fixes #2054

### CODE REVIEW

**Comment by RasenGUY** [comment]
I closed the other pr and opened this new one, as I had to figure out how to properly keep up to date the develop branch on my local machine. I updated the commit message as requested before and rebased against develop. hopefully this works. Mind My noobishness, this is my first time contributing.

**Comment by smartcontracts** [comment]
No problem @RasenGUY! Thank you :-) running the integration tests now

**Comment by RasenGUY** [comment]
> No problem @RasenGUY! Thank you :-) running the integration tests now

I'l take a stab at other similar issues, if that's ok with you guys ?

**Comment by smartcontracts** [comment]
> > No problem @RasenGUY! Thank you :-) running the integration tests now
> 
> I'l take a stab at other similar issues, if that's ok with you guys ?

Of course! You're welcome to tackle as many issues as you'd like :-) Let me know if you ever need any assistance

**Review by smartcontracts — APPROVED** [review]

**Pull request merged**
