### PR TITLE
op-node: Remove unused field in `ChannelBank`

### PR DESCRIPTION
**Pull request by palango**
**Description**

Remove an unused field in the `ChannelBank`

**Tests**

Adapted tests, field was partially set to `nil` already.

### CODE REVIEW

**Review by ajsutton — APPROVED** [review]
LGTM thanks.  But seems CI hit some flaky tests and it's run in the celo org so I can't trigger a rerun.  Are you able to kick it please?

**Comment by palango** [comment]
> LGTM thanks. But seems CI hit some flaky tests and it's run in the celo org so I can't trigger a rerun. Are you able to kick it please?

I've re-run the tests and rebased as well, but the `contracts-bedrock-tests-heavy-fuzz-modified` test keeps timing out. Is there a trick to get that one green?

**Comment by ajsutton** [comment]
hmm, too long with no output. That suggests it may be trying to do heavy fuzzing of every test instead of just what changed.  It's doing a `git diff origin/develop...HEAD` to find what changed so maybe on your fork try pushing the latest `develop` to match the `ethereum-optimism` fork?

cc @smartcontracts who has been working in this area lately. Any ideas here?

**Comment by palango** [comment]
Updating `develop` in the fork seems to have done the trick.

**Pull request merged**
