### PR TITLE
Added a docker-compose file that doesn't take forever and a day

### PR DESCRIPTION
**Pull request by qbzzt**
**Description**

The current `docker-compose.yml` file requires you to compile and build the docker images. That may be fine for Optimism developers who need the latest and greatest, but people who want to integrate with us just need a system they can use. They'd be better served pulling the images from the docker hub. That is what this file does.

```sh
cd .../ops
docker-compose -f docker-compose-nobuild.yml up
```

And you get a system, relatively quickly (pulling still takes a long time, because it's so big).

Fixes OP-1110

### CODE REVIEW

**Comment by snario** [comment]
Is it possible for this to implemented in a way that does not copy the code from the other file but rather inherits it or in some way is linked by it?

**Comment by qbzzt** [comment]
> Is it possible for this to implemented in a way that does not copy the code from the other file but rather inherits it or in some way is linked by it?

Not trivially. I tried to just use the `--no-build` command line option, but it doesn't work for me. It immediately exists with:
```
ori@devenv-no-build:~/optimism/ops$ docker-compose up --no-build
WARNING: Some services (gas_oracle, integration_tests, replica, verifier) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
ERROR: Service 'builder' needs to be built, but --no-build was passed.
```

`docker-compose pull` doesn't work either:
```
ori@devenv-no-build:~/optimism/ops$ docker-compose pull
WARNING: Some services (gas_oracle, integration_tests, replica, verifier) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
ori@devenv-no-build:~/optimism/ops$ 
```

Setting the environment variables doesn't change these results.
```
export COMPOSE_DOCKER_CLI_BUILD=1
export DOCKER_BUILDKIT=1
```

I couldn't find any way to inherit code from the `docker-compose.yml` file, unless we use a github action, which I'd rather not do.

**Comment by tynes** [comment]
The integration tests seem to fail when I bring up the network in this way, I think that one of the `latest` images hasn't been pushed correctly

**Comment by qbzzt** [comment]
> The integration tests seem to fail when I bring up the network in this way, I think that one of the `latest` images hasn't been pushed correctly

I removed the integration tests service because:
1. I don't think David Dapp Developer needs it
2. They are ancient (4 months is a long time in this industry). 

Do we need the integration tests to work with `docker-compose-nobuild.yml`? If so, can somebody please update the image on https://hub.docker.com/r/ethereumoptimism/integration-tests?

**Comment by tynes** [comment]
Let me clarify - I brought up the whole system using the command that you posted above and then ran the integration tests myself against the network. It threw a bunch of errors, which leads me to belive that one of the containers that was pulled from dockerhub was not up to date. In particular, I think the deployer isn't up to date on dockerhub

**Comment by tynes** [comment]
This can be fixed by making sure that we are pushing `latest` for all of the images in the CI pipeline in the github actions. The reason as to why I think this is important is that we need to be sure that developers are testing against a system that fully works before telling them to develop that way

**Comment by qbzzt** [comment]
> This can be fixed by making sure that we are pushing `latest` for all of the images in the CI pipeline in the github actions. The reason as to why I think this is important is that we need to be sure that developers are testing against a system that fully works before telling them to develop that way

Good point. I don't have the ability to modify github actions on this repository, can you do it?

**Review by tynes — APPROVED** [review]

**Review by K-Ho — APPROVED** [review]

**Pull request closed without merging**
