### PR TITLE
ci-builder: add just, update foundry version, optimize image

### PR DESCRIPTION
**Pull request by tynes**
**Description**

- Adds `just` to the `ci-builder` because it is used as part of `superchain-ops`
- Updates to a more modern version of foundry to fix build issues (for some reason having issues building older versions?)
- Uses nvm to use the correct version of node.js

### CODE REVIEW

**Review by protolambda — APPROVED** [review]

**Comment by protolambda** [comment]
Sorry to scope-creep this PR with additional changes, but improving things when we change them is the best way to catch up with some of the CI / testing tech-debt we have.

I stripped down the ci-builder image, so it's no longer 2.0 GB.

Just doing `RUN rm -rf <something>` in the final stage alone is not enough, as each layer is part of the image; removals have to be in the same `RUN` as the addition, to clean up.

Moved more into stages to. A big isuse (~200 MB) was the go mod cache becoming part of the image.

Also dropped `musl coreutils g++-x86-64-linux-gnu libc6-dev-amd64-cross` since I don't think we need them there explicitly, and they add significant weight too. Do we really need them?

Image estimate:
```
 80 MB base image
200 MB /root/.nvm/versions/node/vX.Y.Z
  8 MB gotestsum
 14 MB mockery
 60 MB geth
 17 MB abigen
 13 MB svm
214 MB /usr/local/go
 70 MB /usr/local{forge,cast,anvil}
 42 MB echidna
 32 MB pnpm and yarn
133 MB python 3.11
 17 MB perl
 47 MB codecov
 22 MB svm install output
 42 MB binutils and capstone etc.
 99 MB gcc
```
Unortunately it looks like the minimum is about ~1.1 GB
I got it down to 1.3 GB, there is still a bunch of random config / system files that are tricky to remove / filter with copy from stage to stage.

**Comment by tynes** [comment]
I am rebuilding this to ensure that it works

**Comment by tynes** [comment]
I am having issues building the image after [972d50e](https://github.com/ethereum-optimism/optimism/pull/7641/commits/972d50e7c18ae820715a64bd04aa245fd2c6818e)

**Comment by protolambda** [comment]
```
[+] Building 533.1s (45/45) FINISHED                                                                                                                                                                                                                                                                               docker:default
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                                            0.0s
 => => transferring context: 173B                                                                                                                                                                                                                                                                                            0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                                                         0.0s
 => => transferring dockerfile: 4.87kB                                                                                                                                                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/library/python:3.11.4-slim-bullseye                                                                                                                                                                                                                                               0.6s
 => [internal] load metadata for ghcr.io/crytic/echidna/echidna:v2.0.4                                                                                                                                                                                                                                                       1.5s
 => [internal] load metadata for docker.io/library/debian:bullseye-slim                                                                                                                                                                                                                                                      0.7s
 => [internal] load build context                                                                                                                                                                                                                                                                                            0.0s
 => => transferring context: 110B                                                                                                                                                                                                                                                                                            0.0s
 => CACHED [echidna-test 1/1] FROM ghcr.io/crytic/echidna/echidna:v2.0.4@sha256:e5351bd4d40b89523854d526d620595ccf63b91a3020861130e3372660cafafd                                                                                                                                                                             0.0s
 => CACHED [go-build  1/10] FROM docker.io/library/debian:bullseye-slim@sha256:9bec46ecd98ce4bf8305840b021dda9b3e1f8494a0768c407e2b233180fa1466                                                                                                                                                                              0.0s
 => CACHED [stage-3  1/18] FROM docker.io/library/python:3.11.4-slim-bullseye@sha256:40319d0a897896e746edf877783ef39685d44e90e1e6de8d964d0382df0d4952                                                                                                                                                                        0.0s
 => CACHED [rust-build  2/10] WORKDIR /opt                                                                                                                                                                                                                                                                                   0.0s
 => [rust-build  3/10] RUN apt-get update &&   apt-get install -y curl build-essential git clang lld curl                                                                                                                                                                                                                   72.4s
 => [go-build  2/10] RUN apt-get update && apt-get install -y curl ca-certificates                                                                                                                                                                                                                                          10.0s
 => [go-build  3/10] RUN curl -sL https://go.dev/dl/go1.21.1.linux-amd64.tar.gz -o go1.21.1.linux-amd64.tar.gz &&   tar -C /usr/local/ -xzvf go1.21.1.linux-amd64.tar.gz                                                                                                                                                     3.9s
 => [go-build  4/10] COPY ./.abigenrc ./.abigenrc                                                                                                                                                                                                                                                                            0.1s
 => [go-build  5/10] RUN go install github.com/ethereum/go-ethereum/cmd/abigen@$(cat .abigenrc)                                                                                                                                                                                                                             14.3s
 => [go-build  6/10] COPY ./.gethrc ./.gethrc                                                                                                                                                                                                                                                                                0.1s
 => [go-build  7/10] RUN go install github.com/ethereum/go-ethereum/cmd/geth@$(cat .gethrc)                                                                                                                                                                                                                                 22.1s
 => [go-build  8/10] RUN go install gotest.tools/gotestsum@latest                                                                                                                                                                                                                                                            6.3s
 => [go-build  9/10] RUN go install github.com/vektra/mockery/v2@v2.28.1                                                                                                                                                                                                                                                     6.9s
 => [go-build 10/10] RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.2                                                                                                                                                                                                                             10.3s
 => [rust-build  4/10] RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh &&   chmod +x ./rustup.sh &&   ./rustup.sh -y                                                                                                                                                                               9.9s
 => [stage-3  2/18] COPY --from=go-build /usr/local/go /usr/local/go                                                                                                                                                                                                                                                         1.6s
 => [stage-3  3/18] COPY --from=go-build /go/bin/gotestsum /go/bin/gotestsum                                                                                                                                                                                                                                                 0.1s
 => [stage-3  4/18] COPY --from=go-build /go/bin/mockery /go/bin/mockery                                                                                                                                                                                                                                                     0.1s
 => [stage-3  5/18] COPY --from=go-build /go/bin/mockery /go/bin/golangci-lint                                                                                                                                                                                                                                               0.1s
 => [stage-3  6/18] COPY --from=go-build /go/bin/abigen /usr/local/bin/abigen                                                                                                                                                                                                                                                0.3s
 => [stage-3  7/18] COPY --from=go-build /go/bin/geth /usr/local/bin/geth                                                                                                                                                                                                                                                    0.2s
 => [rust-build  5/10] RUN source $HOME/.profile && cargo install just                                                                                                                                                                                                                                                      28.7s
 => [rust-build  6/10] RUN source $HOME/.profile && cargo install svm-rs                                                                                                                                                                                                                                                    17.5s
 => [rust-build  7/10] COPY ./.foundryrc ./.foundryrc                                                                                                                                                                                                                                                                        0.1s
 => [rust-build  8/10] RUN git clone https://github.com/foundry-rs/foundry.git ./foundry   && cd foundry && git checkout $(cat ../.foundryrc)                                                                                                                                                                                4.8s
 => [rust-build  9/10] WORKDIR /opt/foundry                                                                                                                                                                                                                                                                                  0.1s
 => [rust-build 10/10] RUN source $HOME/.profile &&   cargo build --release &&   strip /opt/foundry/target/release/forge &&   strip /opt/foundry/target/release/cast &&   strip /opt/foundry/target/release/anvil                                                                                                          321.7s
 => [stage-3  8/18] COPY --from=rust-build /root/.cargo/bin/svm /usr/local/bin/svm                                                                                                                                                                                                                                           0.1s 
 => [stage-3  9/18] COPY --from=rust-build /root/.cargo/bin/just /usr/local/bin/just                                                                                                                                                                                                                                         0.1s 
 => [stage-3 10/18] COPY --from=rust-build /opt/foundry/target/release/forge /usr/local/bin/forge                                                                                                                                                                                                                            0.1s 
 => [stage-3 11/18] COPY --from=rust-build /opt/foundry/target/release/cast /usr/local/bin/cast                                                                                                                                                                                                                              0.1s 
 => [stage-3 12/18] COPY --from=rust-build /opt/foundry/target/release/anvil /usr/local/bin/anvil                                                                                                                                                                                                                            0.1s 
 => [stage-3 13/18] COPY --from=echidna-test /usr/local/bin/echidna-test /usr/local/bin/echidna-test                                                                                                                                                                                                                         0.2s 
 => [stage-3 14/18] COPY .nvmrc .nvmrc                                                                                                                                                                                                                                                                                       0.1s
 => [stage-3 15/18] RUN /bin/sh -c set -eux;   apt-get update;   apt-get install -y --no-install-recommends bash curl openssh-client git build-essential ca-certificates jq gnupg binutils-mips-linux-gnu;   curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash;   . /root/.bashrc && nvm ins  58.5s
 => [stage-3 16/18] RUN echo "downloading pnpm and yarn" && . /root/.bashrc && npm i -g pnpm && npm i -g yarn@1 && pnpm --version && yarn --version                                                                                                                                                                          3.4s 
 => [stage-3 17/18] RUN svm install 0.5.17 &&   svm install 0.8.15                                                                                                                                                                                                                                                           5.8s 
 => [stage-3 18/18] RUN echo "downloading and verifying Codecov uploader" &&   curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import &&   curl -Os "https://uploader.codecov.io/latest/linux/codecov" &&   curl -Os "https://uploader.codecov.io/latest/linux/  2.8s 
 => exporting to image                                                                                                                                                                                                                                                                                                       4.6s 
 => => exporting layers                                                                                                                                                                                                                                                                                                      4.6s 
 => => writing image sha256:51efc615b580519c168d2ab821854504d0f00ceef133a8bdf96c6dd3638552e1                                                                                                                                                                                                                                 0.0s 
 => => naming to docker.io/library/ci-builder  
```
It builds, let's ship it

**Pull request merged**
