### PR TITLE
MT Cannon: add mips mul/div tests

### LINKED ISSUE #12458: MTCannon: Create mul/div opcodes tests
This is a sub task of the https://github.com/ethereum-optimism/optimism/issues/12032

### PR DESCRIPTION
**Pull request by GrapeBaBa**
**Description**

This PR add mips mul/div tests

**Tests**

**Additional context**

**Metadata**

- Fixes #12458

### CODE REVIEW

**Comment by GrapeBaBa** [comment]
@Inphi @mbaxter can you help re trigger  the CI, lint and test already passed in my local env

**Comment by Inphi** [comment]
> @Inphi @mbaxter can you help re trigger the CI, lint and test already passed in my local env

@GrapeBaBa  Done. Could you rebase on the latest develop to fix the flaky tests.

**Comment by GrapeBaBa** [comment]
@Inphi Aleady rebased but still got lint error, I tried `make lint-go` locally and no errors.

**Review by Inphi — APPROVED** [review]
Thanks!

**Pull request merged**
