### PR TITLE
feat(ctb): make Proxy inheritable

### LINKED ISSUE #5274: Make Proxy.sol inheritable
**Problem**
I'd love to inherit from [`Proxy.sol`](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/contracts/universal/Proxy.sol) in a custom proxy that I'm writing. However, the functions that I want to override don't have the `virtual` keyword :(

**Solution**
Ideally, a couple minor changes for the functions `upgradeTo` and `upgradeToAndCall`:
* Add the `virtual` keyword, which would allow me to override these functions.
* Change the visibility of these functions from `external` to `public`. This lets me call `super.upgradeTo/super.upgradeToAndCall`.

Bullet point 2 isn't strictly necessary since I don't _need_ to call `super.upgradeTo/super.upgradeToAndCall`. It'd just make my code cleaner.

**Alternative**
The alternative is that I copy and paste `Proxy.sol` into my own file, but it'd keep my codebase cleaner if I could just inherit from Optimism's. Also, it's worth mentioning that OpenZeppelin's`TransparentUpgradeableProxy` has this same limitation, so that's a no-go.

**Additional context**
@smartcontracts said to open an issue for this. I'm happy to make a PR with these changes!

### PR DESCRIPTION
**Pull request by smartcontracts**
**Description**
Makes the Proxy contract inheritable by making external functions into (public virtual) functions. Does not impact generated bytecode or gas snapshot.

**Metadata**

- Fixes #5274

### CODE REVIEW

**Comment by tynes** [comment]
not opposed to this, another improvement would be to move the 1967 constants into the `Constants.sol` file and then we can have unit tests asserting that the values are correct and have portability in the other places these values are used

**Comment by smartcontracts** [comment]
Yeah that's a good suggestion. Could you make an issue for it? Could be a good first issue for someone to tackle.

**Comment by tynes** [comment]
> Yeah that's a good suggestion. Could you make an issue for it? Could be a good first issue for someone to tackle.

https://github.com/ethereum-optimism/optimism/issues/5300

**Comment by maurelian** [comment]
https://github.com/ethereum-optimism/optimism/pull/5329

**Review by maurelian — APPROVED** [review]

**Review by tynes — APPROVED** [review]

**Comment by tynes** [comment]
Looks like slither is failing due to something not interesting

```
Low level call in Proxy.upgradeToAndCall(address,bytes) (contracts/universal/Proxy.sol#98-109):
	- (success,returndata) = _implementation.delegatecall(_data) (contracts/universal/Proxy.sol#106)
```

**Comment by trianglesphere** [comment]
> Looks like slither is failing due to something not interesting
> 
> ```
> Low level call in Proxy.upgradeToAndCall(address,bytes) (contracts/universal/Proxy.sol#98-109):
> 	- (success,returndata) = _implementation.delegatecall(_data) (contracts/universal/Proxy.sol#106)
> ```

We really should be fixing or silencing these alerts

**Pull request merged**
