### PR TITLE
add OwnerUpdated and CodeUpdated events

### PR DESCRIPTION
**Pull request by rajivpo**
**Description**
- added `CodeUpdated` and `OwnerUpdated` events

**Additional context**
It could be nice for easily tracking implementation and/or owner changes. I did not add a `StorageUpdated` event as I imagined that it could be noisy (assumption being that frequency of implementation and/or owner changes is << frequency of storage changes).

**Metadata**

### CODE REVIEW

**Comment by maurelian** [comment]
Thanks for this! 

I think this is a good change, but there are just a couple things we should think about here:

1. but it might be some time before we replace the [one existing instance](https://etherscan.io/address/0x99C9fc46f92E8a1c0deC1b1747d010903E884bE1#code) of a ChugSplash proxy that we currently have running. On the one hand, I'm a bit concerned about potential consequences arising from having source code that differs from the deployed code<sup>[1](#1)</sup>. On the other hand, we have already prettified that contract, and updated the solidity version. 

2. The `experimental` branch is inactive, and should probably be deleted unless we are keeping it around for some specific purpose (cc @snario)?


<a name="1">1</a>: The worst case I can imagine is someone writing a tool that depends on these events. We can probably mitigate that risk with a comment in the code.

**Comment by tynes** [comment]
We are now working off of `regenesis/0.5.0`, apologies for the confusion

**Comment by rajivpo** [comment]
I agree that a comment could help clarify the differences between source and deployed code if others are comfortable with differences existing. If these changes would be of interest, I'm happy to fix the branch and file a new PR with the relevant base.

**Comment by maurelian** [comment]
> I agree that a comment could help clarify the differences between source and deployed code if others are comfortable with differences existing.

WDYT @smartcontracts ?

**Comment by tynes** [comment]
I do generally think that this is a good idea, I do believe that we are already code frozen so unlikely that this will be getting in

**Comment by smartcontracts** [comment]
> I do generally think that this is a good idea, I do believe that we are already code frozen so unlikely that this will be getting in

100% agreed.

**Comment by rajivpo** [comment]
Understood. I will close this for the time being, but it's a simple enough change if it is to be revisited in the future 😄

**Pull request closed without merging**
