### PR TITLE
chore: Add yarn-deduplicate script to deduplicate along with github action

### PR DESCRIPTION
**Pull request by roninjin10**
This will help keep our node moduels smaller and avoid some issues yarn has from time to time. 

https://optimism-workspace.slack.com/archives/CQZ0U9FAN/p1656513572407569

### CODE REVIEW

**Comment by roninjin10** [comment]
This technically changes any package that depends on the packages I changed but I didn't include a changeset.   not sure how to handle it since I'm not entirely sure which packages changed.

**Comment by tynes** [comment]
Unsure if the actual deps used will be changed that go into the builds, we could add changesets for each typescript package just in case

**Comment by smartcontracts** [comment]
Pretty sure this will change deps, so let's do a patch release of every TS package

**Comment by roninjin10** [comment]
Ok I’ll bump packages.   I think I can add yarn deduplicate as a post install task too so nobody needs to remember to do it.

**Review by tynes — APPROVED** [review]

**Comment by tynes** [comment]
@roninjin10 I pushed a commit that adds changesets, ready to merge with another approval

**Review by mslipper — APPROVED** [review]

**Review by smartcontracts — APPROVED** [review]

**Pull request merged**
