### PR TITLE
contracts-bedrock: delete state diff json

### PR DESCRIPTION
**Pull request by tynes**
**Description**

Removes the `deploy.json` state diff artifact. We don't necessarily
need to commit the state diff of the deploy script to the repo. We
should utilize the state diff of the deploy script when doing major
refactors of the deploy script to ensure that no bugs are being
introduced.

Adding in CI checks that the artifact has been updated is too much
overhead and not really worth the benefit. Certain changes to the deploy
script would result in huge diffs to the artifact without it being
particularly legible. This tooling is more useful for `superchain-ops`
where we should have every single storage slot diff fully accounted for.

### CODE REVIEW

**Review by refcell — COMMENTED** [review]
The circleci job will need to be updated?

**Comment by refcell** [comment]
Concretely, remove: https://github.com/ethereum-optimism/optimism/blob/develop/.circleci/config.yml#L473-L484

**Comment by tynes** [comment]
> Concretely, remove: https://github.com/ethereum-optimism/optimism/blob/develop/.circleci/config.yml#L473-L484

yes good call

**Comment by tynes** [comment]
> > Concretely, remove: https://github.com/ethereum-optimism/optimism/blob/develop/.circleci/config.yml#L473-L484
> 
> yes good call

follow up - no need to make a diff here

**Review by refcell — APPROVED** [review]

**Pull request merged**
