### PR TITLE
contracts-bedrock: deprecate deployments

### PR DESCRIPTION
**Pull request by tynes**
**Description**

There is no reason to keep the legacy hardhat deploy artifacts
around anymore. It just adds complexity to the codebase. With the
advent of the superchain, it no longer makes sense to hold on to
these artifacts here. The contract addressses now live in the superchain-registry.
The legacy abis live in git history or release tags.

For what its worth, the `deployments` directory is already out of date
and the superchat registry should be considered the source of truth.

Deleting these files will reduce the size of a cloned repo.

The entire `deployments` directory is not yet fully removed because
it is used to write the `.deploy` artifact after the forge deployment
script runs. This will also change in the future but do not want to
make too large of changes at once.

The `.deploy` file will be configurable where it is written to
and it will interoperate well with the `superchain-registry` repo.

### CODE REVIEW

**Comment by roninjin10** [comment]
We might need to remove some references to this too. I can check in a bit

**Comment by tynes** [comment]
> We might need to remove some references to this too. I can check in a bit

We would need to do an npm release here and then have other code update the dep version for this to break things

**Comment by roninjin10** [comment]
True. We might want to hold off on adding a changeset and releasing this package until the next breaking changes happen unless we were ok bumping the version a major version now

**Review by roninjin10 — APPROVED** [review]

**Comment by tynes** [comment]
> True. We might want to hold off on adding a changeset and releasing this package until the next breaking changes happen unless we were ok bumping the version a major version now

We haven't been doing releases of the contracts through npm for a long time. Our future plans involve doing releases via git tags available on github

**Comment by roninjin10** [comment]
Nice! These NPM packages are moving out of the monorepo soon as well

**Review by clabby — APPROVED** [review]

**Pull request merged**
