### PR TITLE
fix test for "unexpected EOF"

### PR DESCRIPTION
**Pull request by zhiqiangxu**
The old test didn't test what it's supposed to test, to see this, just comment out [this line](https://github.com/ethereum-optimism/optimism/blob/3c34770c555642dddf3b0f123a0a9d0257aa6bd1/op-preimage/hints_test.go#L86) and it still passes.

The root cause is that both hint writer and reader are reading the same `Buffer` object. This PR fixes this issue.

## Summary by CodeRabbit

- **Refactor**
	- Improved the test case for detecting "unexpected EOF" in hint processing by enhancing synchronization and data flow.
- **Chores**
	- Simplified error severity classification by removing an unused severity level.

### CODE REVIEW

**Review by ajsutton — CHANGES_REQUESTED** [review]
If you debug both versions of the test, they wind up reaching https://github.com/ethereum-optimism/optimism/blob/aa6d64ea798a0937fc418fbf504fa9255e72aa21/op-preimage/hints.go#L58 and its unable to read the full data so returns `ErrUnexpectedEOF` which is the condition we're aiming for.

The test passes even when removing the single byte read from the test case because the HintWriter is actually reading a single byte (correctly - it's used as part of thread handling in the protocol).  It's still worth the test reading a byte to ensure it winds up shorter in case the writer behaviour changes in future.

So we can keep the test simple and single threaded as it is still covering the behaviour we want.

**Comment by zhiqiangxu** [comment]
> because the HintWriter is actually reading a single byte (correctly - it's used as part of thread handling in the protocol)

Yeah I'm aware of this acknowledge protocol:)

But the difference between the 2 tests is that in the later case, `b.Read(make([]byte, 1))` is necessary to make it fail. It looks like it was trying to manually causing short read by reading one byte and was not expecting hint writer and reader are stepping on each other's foot when using the same `Buffer` object.

**Comment by ajsutton** [comment]
The difference is just that in the current version 2 bytes get read - one by the writer and one by the test. So you can delete either of them and still get the unexpected EOF.  In the new version the buffer isn't shared so the writer isn't reading a byte and so the test has to.  Either way it's setting up the same condition we want to test where there isn't enough data in the buffer which is all that matters.  We don't need to add complexity to the test because it's already testing what it intends to.

**Comment by zhiqiangxu** [comment]
There is some controversy, but since it is just a test, I rolled back the changes.

**Pull request closed without merging**
