### PR TITLE
op-batcher: Concurrently send transactions

### PR DESCRIPTION
**Pull request by trianglesphere**
**Description**

This is a simple hack to enable significantly higher throughput for lattice with op-craft.

**Tests**

I tested this locally by modifying the max tx size argument in the op-e2e tests & confirming that I see expected transaction sending behavior (by looking at the logs).

**Metadata**
- Fixes ENG-2898

### CODE REVIEW

**Review by protolambda — APPROVED** [review]

**Comment by tynes** [comment]
We are guaranteed that the transactions will never revert if they make it into the mempool since there is no code at the account we are sending to. If we decide to add a contract that does the owner management instead of being able to dynamically + deterministically change the batch sender in the op-node, there is some complexity regarding reverted transactions, ie how do you know to resend the same batch if it happens to revert?

**Comment by trianglesphere** [comment]
> If we decide to add a contract that does the owner management instead of being able to dynamically + deterministically change the batch sender in the op-node, there is some complexity regarding reverted transactions, ie how do you know to resend the same batch if it happens to revert?

There probably is, but we're ignoring it for now. This is only getting applied to the lattice branch and won't be brought into our production environment

**Comment by trianglesphere** [comment]
@mslipper

**Comment by trianglesphere** [comment]
Turning into a draft to hide this until opcraft is over or we actually need this.

**Comment by trianglesphere** [comment]
no longer needed.

**Pull request closed without merging**
