### PR TITLE
wip: remove message relayer

### PR DESCRIPTION
**Pull request by smartcontracts**
**WIP**
Hoping that removing this image will reduce the frequency of cases in which CI runs out of memory.

**Description**
Removes the message relayer docker image from `ops`.

### CODE REVIEW

**Comment by tynes** [comment]
I think we should still leave in the dockerfile, just set the replicas field to 0 in the docker-compose file

**Comment by smartcontracts** [comment]
> I think we should still leave in the dockerfile, just set the replicas field to 0 in the docker-compose file

TBH I was going to completely remove the `message-relayer` code if I could get away with it. Seems like CI is passing without it so that's good.

**Comment by tynes** [comment]
> > I think we should still leave in the dockerfile, just set the replicas field to 0 in the docker-compose file
> 
> TBH I was going to completely remove the `message-relayer` code if I could get away with it. Seems like CI is passing without it so that's good.

The message relayer is still useful for local development right? Removing it will break many people's tests that depend on it

**Comment by smartcontracts** [comment]
> > > I think we should still leave in the dockerfile, just set the replicas field to 0 in the docker-compose file
> > 
> > 
> > TBH I was going to completely remove the `message-relayer` code if I could get away with it. Seems like CI is passing without it so that's good.
> 
> The message relayer is still useful for local development right? Removing it will break many people's tests that depend on it

Hmmm ya I guess the correct way to do this is to announce the change in advance with tooling in place for people to switch over. I'll start a discussion about it tomorrow.

**Pull request closed without merging**
