### PR TITLE
contracts-bedrock, ci: remove slither

### PR DESCRIPTION
**Pull request by tynes**
**Description**

Remove the committed in `slither-report.json` since it is not being used
as part of code review. Also remove running it as part of CI. We can
choose to add it back when we have the time for somebody to own making
it a first class tool, but since we haven't triaged the database yet
it only adds noise to PRs by adding extra diff and extra overhead by
forcing a regeneration of the report.

It hasn't found any issues in our code and our other checks are much
better at finding issues in the code.

Leaving the slither commands in the `package.json` for now but if we
do not commit to using slither in a way that is very helpful for us
in 6 months or so, then we should just remove the commands as well.

Maybe we can adopt a way of using slither where it is used before
doing releases of contracts or before going to audit. Having the diff
as part of code review is not super helpful for code reviewers.
It just adds noise in the current form.

### CODE REVIEW

**Review by mds1 — APPROVED** [review]
I'm ok with this since we aren't using it right now.

Linking to https://github.com/ethereum-optimism/security-pod/issues/67#issuecomment-1896089792 where I suggest (once someone has the time) also removing our custom slither scripts and using [slither-action](https://github.com/crytic/slither-action) instead. This is a github action—which is why we did not use it—and it posts findings on PRs and adds them to the repo Security tab, so the UX/triage process is much nicer.

Since there were no initial findings in my [triage](https://github.com/ethereum-optimism/client-pod/issues/327#issuecomment-1866618332), we probably can start off by ignoring all findings, then incrementally addressing things on PRs.

All that to say—if we're onboard with the github action instead, we can remove our slither shell scripts in this PR too

**Comment by tynes** [comment]
I am definitely on board with the github action, we do have some github actions for releases already

**Review by trianglesphere — APPROVED** [review]

**Comment by mslipper** [comment]
This would help reduce the size of the ci-builder image as well.

**Comment by mslipper** [comment]
Seeing `reference is not a tree` errors which implies that CCI has some bug parsing the merge queue. Sending up an empty commit to try and fix the issue.

**Pull request merged**
