### PR TITLE
fix(l2g): startup deadlock

### PR DESCRIPTION
**Pull request by smartcontracts**
**Description**
Fixes a deadlock that can occur in l2geth.

### CODE REVIEW

**Comment by feld** [comment]
This fixes my node that wouldn't sync anymore

**Comment by smartcontracts** [comment]
Multiple users have confirmed that this fixes a startup deadlock.

**Comment by trianglesphere** [comment]
@smartcontracts @tynes bump

**Comment by trianglesphere** [comment]
@smartcontracts @tynes bump

**Comment by Inphi** [comment]
Could you provide some context? How does this fix the deadlock?

**Comment by smartcontracts** [comment]
> Could you provide some context? How does this fix the deadlock?

So basically the flow of what's happening here is:
1. Transaction is applied but transaction index is not updated
2. Node recognizes this and tries to reset the transaction index
3. Node already has the block in question and the code deleted in this PR tries to skip applying the block again
4. Since the block never gets applied again there's a deadlock

**Comment by Inphi** [comment]
Oh I see, the short-circuit prevents the new block event from being emitted and the `SyncService.applyTransaction` waits for that event before returning. 
One thing to note is if the block being re-applied isn't the head/latest block, then no new chain event gets emitted. So you'd still have a deadlock. Is this scenario possible, say when applying transactions in a batch?

**Comment by protolambda** [comment]
@smartcontracts can you help answer the question above? Changes LGTM otherwise

**Comment by smartcontracts** [comment]
> Oh I see, the short-circuit prevents the new block event from being emitted and the `SyncService.applyTransaction` waits for that event before returning. One thing to note is if the block being re-applied isn't the head/latest block, then no new chain event gets emitted. So you'd still have a deadlock. Is this scenario possible, say when applying transactions in a batch?

I'm pretty certain that it's always the case that the block/transaction index is only ever off by one, so it's the latest block being re-applied.

**Review by Inphi — APPROVED** [review]
LGTM

**Comment by bimlas** [comment]
@smartcontracts  @Inphi 

Is this merged or not? If yes, which release contains it?

**Pull request closed without merging**
