### PR TITLE
all: use errors.New() which has no param instead of fmt.Errorf()

### PR DESCRIPTION
**Pull request by tomdever**
**Description**

fmt.Errorf() with no param should be replace by errors.New()

**Tests**

N/A

**Additional context**

N/A

**Metadata**

- use errors.New which has no param instead of fmt.Errorf

### CODE REVIEW

**Review by trianglesphere — APPROVED** [review]

**Review by sebastianst — DISMISSED** [review]

**Comment by clabby** [comment]
Couple missed `fmt.Errorf`s found w/ `rg "fmt\.Errorf\(\"[^\"]*\"\)"`:

```
op-proposer/proposer/driver.go
215:            return nil, false, fmt.Errorf("L2OutputOracle contract not set, cannot fetch next output info")

op-bootnode/bootnode/entrypoint.go
93:             return fmt.Errorf("failed to start the RPC server")

op-service/sources/reth_db.go
56:             return nil, fmt.Errorf("Error fetching receipts from Reth Database.")

op-chain-ops/upgrades/l1.go
201:            return fmt.Errorf("Messenger address doesn't match config")
205:            return fmt.Errorf("OtherBridge address doesn't match config")
285:            return fmt.Errorf("Messenger address doesn't match config")
289:            return fmt.Errorf("OtherBridge address doesn't match config")
508:            return fmt.Errorf("Bridge address doesn't match config")
586:            return fmt.Errorf("L2OutputOracle address doesn't match config")
590:            return fmt.Errorf("SystemConfig address doesn't match config")

op-node/rollup/derive/engine_controller.go
147:            return BlockInsertTemporaryErr, fmt.Errorf("engine is in progess of p2p sync")
177:            return nil, BlockInsertPrestateErr, fmt.Errorf("cannot complete payload building: not currently building a payload")

op-challenger/game/monitor_test.go
115:                    mockHeadSource.Sub().errChan <- fmt.Errorf("test error")

op-wheel/commands.go
157:            return fmt.Errorf("cannot unmarshal into nil value")

op-bindings/bindgen/remote_handlers.go
225:            return fmt.Errorf("no initialization bytecode provided for ETH deployment for comparison")

op-e2e/external_geth/main.go
34:             return fmt.Errorf("must supply a '--config <path>' flag")
```

Also added a semgrep rule for this @ https://semgrep.dev/playground/r/5rUd7e2/ethereum_optimism.golang_fmt_errorf_no_params

**Review by mslipper — CHANGES_REQUESTED** [review]
In order for us to merge this, please find _all_ instances of `fmt.Errorf` and replace them with `errors.New` and ensure that @clabby's new Semgrep rule above passes.

**Comment by tomdever** [comment]
> Couple missed `fmt.Errorf`s found w/ `rg "fmt\.Errorf\(\"[^\"]*\"\)"`:
> 
> ```
> op-proposer/proposer/driver.go
> 215:            return nil, false, fmt.Errorf("L2OutputOracle contract not set, cannot fetch next output info")
> 
> op-bootnode/bootnode/entrypoint.go
> 93:             return fmt.Errorf("failed to start the RPC server")
> 
> op-service/sources/reth_db.go
> 56:             return nil, fmt.Errorf("Error fetching receipts from Reth Database.")
> 
> op-chain-ops/upgrades/l1.go
> 201:            return fmt.Errorf("Messenger address doesn't match config")
> 205:            return fmt.Errorf("OtherBridge address doesn't match config")
> 285:            return fmt.Errorf("Messenger address doesn't match config")
> 289:            return fmt.Errorf("OtherBridge address doesn't match config")
> 508:            return fmt.Errorf("Bridge address doesn't match config")
> 586:            return fmt.Errorf("L2OutputOracle address doesn't match config")
> 590:            return fmt.Errorf("SystemConfig address doesn't match config")
> 
> op-node/rollup/derive/engine_controller.go
> 147:            return BlockInsertTemporaryErr, fmt.Errorf("engine is in progess of p2p sync")
> 177:            return nil, BlockInsertPrestateErr, fmt.Errorf("cannot complete payload building: not currently building a payload")
> 
> op-challenger/game/monitor_test.go
> 115:                    mockHeadSource.Sub().errChan <- fmt.Errorf("test error")
> 
> op-wheel/commands.go
> 157:            return fmt.Errorf("cannot unmarshal into nil value")
> 
> op-bindings/bindgen/remote_handlers.go
> 225:            return fmt.Errorf("no initialization bytecode provided for ETH deployment for comparison")
> 
> op-e2e/external_geth/main.go
> 34:             return fmt.Errorf("must supply a '--config <path>' flag")
> ```
> 
> Also added a semgrep rule for this @ https://semgrep.dev/playground/r/5rUd7e2/ethereum_optimism.golang_fmt_errorf_no_params

Thank you for figuring out. Now I have solved these, and checked through rg: `fmt\.Errorf\(\"[^\"]*\"\)`. 
The semgrep rule link shows: `The currently selected rule cannot be found. It might have been deleted. Try searching for a different rule.`. Can you help me to check by the rule?

**Comment by tomdever** [comment]
> In order for us to merge this, please find _all_ instances of `fmt.Errorf` and replace them with `errors.New` and ensure that @clabby's new Semgrep rule above passes.

Now I have replaced all `fmt.Errorf` which has no param, and replace with `errors.New`.  Then checked through rg: fmt\.Errorf\(\"[^\"]*\"\).
The semgrep rule link shows: The currently selected rule cannot be found. It might have been deleted. Try searching for a different rule.. Can you help me to check by the rule?

**Comment by ajsutton** [comment]
I'm going to close this - we don't gain anything by switching to `errors.New` and enforcing it going forward just adds friction to development.  And to get this merged we still need to coordinate a bunch of reviewers because it's cutting across so many areas of the codebase. Given it's not a priority for anyone I just can't see it getting across the line.  I appreciate the time you've put into this and sorry that we weren't clearer that this wasn't a priority for us earlier.

**Pull request closed without merging**
