### PR TITLE
use `CallContract` to detect tx failure early if gasLimit is specified

### PR DESCRIPTION
**Pull request by zhiqiangxu**
Currently if `gasLimit` is specified in `TxCandidate`, `EstimateGas` will be called, which does 2 jobs in one shot:
1. estimate the gas usage.
2. detect tx failure before actually sending it onchain.

But if `gasLimit` is specified, there's no such checking.

This PR adds a checking by `CallContract` if `gasLimit` is specified.

### CODE REVIEW

**Review by Inphi — APPROVED** [review]
Nice!

**Comment by zhiqiangxu** [comment]
@Inphi Looks like the CI failure is unrelated to this PR?

**Comment by Inphi** [comment]
@zhiqiangxu Could you try merging from the latest develop?

**Comment by zhiqiangxu** [comment]
> @zhiqiangxu Could you try merging from the latest develop?

Done.

**Pull request merged**
