### PR TITLE
[added] coverage for getMerkleTreeProof

### PR DESCRIPTION
**Pull request by rajivpo**
**Description**
- added coverage for the `getMerkleTreeProof` function in `packages/message-relayer/relay-tx.ts`

**Additional context**
Additional coverage increases total `message-relayer` package coverage from ~72% to 83%

**Metadata**

### CODE REVIEW

**Comment by tynes** [comment]
How exactly did you generate the test vectors? If you copied them from the output of calling the function, it only really checks that the functionality doesn't change in the future. I wonder if there are standard test vectors used elsewhere in the ethereum ecosystem that we can use here

**Comment by rajivpo** [comment]
> How exactly did you generate the test vectors? If you copied them from the output of calling the function, it only really checks that the functionality doesn't change in the future. I wonder if there are standard test vectors used elsewhere in the ethereum ecosystem that we can use here

Yep just got them from the output of the function (definitely hard to reason about just from looking at inputs and outputs). Will  definitely look for standard test vectors.

**Comment by tynes** [comment]
If there isn't anything obviously out there then this PR is fine to merge as is

**Comment by rajivpo** [comment]
not seeing anything super obvious from google searches but will definitely submit a new PR if I am able to find something 😄

**Comment by tynes** [comment]
Thank you for this PR!

**Pull request merged**
