### PR TITLE
repo: migrate away from pnpm

### PR DESCRIPTION
**Pull request by tynes**
**Description**

Migrate to just from pnpm. This is continued tech debt
cleanup away from `pnpm` and typescript that is no longer
used.

### CODE REVIEW

**Comment by tynes** [comment]
Flake again

```
Failing tests:
Encountered 4 failing tests in test/libraries/SafeCall.t.sol:SafeCall_Test
[FAIL. Reason: call not successful; counterexample: calldata=0x06087414000000000000000000000000000000000000000000000000000000000000096800000000000000000000000057fddb5bf9b1660898bef442fc60ee4924cf62260000000000000000000000000000000000000000000000009d68f67f5b1dd12c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000002fb2 args=[0x0000000000000000000000000000000000000968, 0x57fDDB5Bf9b1660898bEf442fC60ee4924CF6226, 11342586688382554412 [1.134e19], 0, 0x0000000000000000000000000000000000000000000000000000000000002fb2]] testFuzz_callWithMinGas_hasEnough_succeeds(address,address,uint64,uint64,bytes) (runs: 448, μ: 54852, ~: 55994)
[FAIL. Reason: call not successful; counterexample: calldata=0xe28f97dc000000000000000000000000000000000000000000000000000000000000096800000000000000000000000057fddb5bf9b1660898bef442fc60ee4924cf6226885cb69240a935d632d79c317109709ecfa91a80626ff3989d68f67f5b1dd12c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000002fb2 args=[0x0000000000000000000000000000000000000968, 0x57fDDB5Bf9b1660898bEf442fC60ee4924CF6226, 61678357398080765210293718086378416697372618187842506566286863523773954249004 [6.167e76], 0, 0x0000000000000000000000000000000000000000000000000000000000002fb2]] testFuzz_call_succeeds(address,address,uint256,uint64,bytes) (runs: 0, μ: 0, ~: 0)
[FAIL. Reason: send not successful; counterexample: calldata=0x49120505000000000000000000000000000000000000000000000000000000000000096800000000000000000000000057fddb5bf9b1660898bef442fc60ee4924cf62260000000000000000000000000000000000000000000000009d68f67f5b1dd12c2e6a736f6e000000000000000000000000000000000000000000000000000000 args=[0x0000000000000000000000000000000000000968, 0x57fDDB5Bf9b1660898bEf442fC60ee4924CF6226, 11342586688382554412 [1.134e19], 20994473528665075656206603645561177367371947869009395450918716214519590289408 [2.099e76]]] testFuzz_sendWithGas_succeeds(address,address,uint64,uint256) (runs: 0, μ: 0, ~: 0)
[FAIL. Reason: send not successful; counterexample: calldata=0x33717fe3000000000000000000000000000000000000000000000000000000000000096800000000000000000000000057fddb5bf9b1660898bef442fc60ee4924cf6226885cb69240a935d632d79c317109709ecfa91a80626ff3989d68f67f5b1dd12c args=[0x0000000000000000000000000000000000000968, 0x57fDDB5Bf9b1660898bEf442fC60ee4924CF6226, 61678357398080765210293718086378416697372618187842506566286863523773954249004 [6.167e76]]] testFuzz_send_succeeds(address,address,uint256) (runs: 0, μ: 0, ~: 0)
```

**Comment by tynes** [comment]
> Flake again
> 
> ```
> Failing tests:
> Encountered 4 failing tests in test/libraries/SafeCall.t.sol:SafeCall_Test
> [FAIL. Reason: call not successful; counterexample: calldata=0x06087414000000000000000000000000000000000000000000000000000000000000096800000000000000000000000057fddb5bf9b1660898bef442fc60ee4924cf62260000000000000000000000000000000000000000000000009d68f67f5b1dd12c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000002fb2 args=[0x0000000000000000000000000000000000000968, 0x57fDDB5Bf9b1660898bEf442fC60ee4924CF6226, 11342586688382554412 [1.134e19], 0, 0x0000000000000000000000000000000000000000000000000000000000002fb2]] testFuzz_callWithMinGas_hasEnough_succeeds(address,address,uint64,uint64,bytes) (runs: 448, μ: 54852, ~: 55994)
> [FAIL. Reason: call not successful; counterexample: calldata=0xe28f97dc000000000000000000000000000000000000000000000000000000000000096800000000000000000000000057fddb5bf9b1660898bef442fc60ee4924cf6226885cb69240a935d632d79c317109709ecfa91a80626ff3989d68f67f5b1dd12c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000002fb2 args=[0x0000000000000000000000000000000000000968, 0x57fDDB5Bf9b1660898bEf442fC60ee4924CF6226, 61678357398080765210293718086378416697372618187842506566286863523773954249004 [6.167e76], 0, 0x0000000000000000000000000000000000000000000000000000000000002fb2]] testFuzz_call_succeeds(address,address,uint256,uint64,bytes) (runs: 0, μ: 0, ~: 0)
> [FAIL. Reason: send not successful; counterexample: calldata=0x49120505000000000000000000000000000000000000000000000000000000000000096800000000000000000000000057fddb5bf9b1660898bef442fc60ee4924cf62260000000000000000000000000000000000000000000000009d68f67f5b1dd12c2e6a736f6e000000000000000000000000000000000000000000000000000000 args=[0x0000000000000000000000000000000000000968, 0x57fDDB5Bf9b1660898bEf442fC60ee4924CF6226, 11342586688382554412 [1.134e19], 20994473528665075656206603645561177367371947869009395450918716214519590289408 [2.099e76]]] testFuzz_sendWithGas_succeeds(address,address,uint64,uint256) (runs: 0, μ: 0, ~: 0)
> [FAIL. Reason: send not successful; counterexample: calldata=0x33717fe3000000000000000000000000000000000000000000000000000000000000096800000000000000000000000057fddb5bf9b1660898bef442fc60ee4924cf6226885cb69240a935d632d79c317109709ecfa91a80626ff3989d68f67f5b1dd12c args=[0x0000000000000000000000000000000000000968, 0x57fDDB5Bf9b1660898bEf442fC60ee4924CF6226, 61678357398080765210293718086378416697372618187842506566286863523773954249004 [6.167e76]]] testFuzz_send_succeeds(address,address,uint256) (runs: 0, μ: 0, ~: 0)
> ```

Neither @mds1 or I can repro this locally

**Review by protolambda — APPROVED** [review]
:tada:

**Comment by tynes** [comment]
```
Encountered 2 failing tests in test/libraries/SafeCall.t.sol:SafeCall_Test
[FAIL. Reason: send not successful; counterexample: calldata=0x4912050500000000000000000000000065636569766564000000000000000000000000010000000000000000000000005f65cd7d792e9746ef82929d60de9a1c526f93a500000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000063 args=[0x6563656976656400000000000000000000000001, 0x5F65cD7D792E9746EF82929D60de9a1C526f93A5, 255, 99]] testFuzz_sendWithGas_succeeds(address,address,uint64,uint256) (runs: 434, μ: 51898, ~: 52264)
[FAIL. Reason: send not successful; counterexample: calldata=0x33717fe300000000000000000000000065636569766564000000000000000000000000010000000000000000000000005f65cd7d792e9746ef82929d60de9a1c526f93a500000000000000000000000001000000000000000000000000000000000000ff args=[0x6563656976656400000000000000000000000001, 0x5F65cD7D792E9746EF82929D60de9a1C526f93A5, 5708990770823839524233143877797980545530986751 [5.708e45]]] testFuzz_send_succeeds(address,address,uint256) (runs: 0, μ: 0, ~: 0)
```

**Review by clabby — APPROVED** [review]
Heroic, gg

**Comment by samlaf** [comment]
Hey guys, docs here https://docs.optimism.io/chain/testing/dev-node#install-dependencies will need to be updated. What's the new way to install dependencies?

**Comment by mds1** [comment]
Thanks for flagging the required documentation updates @samlaf

The general pattern is that commands of the form `pnpm foo`/`pnpm foo:bar` are now of the form `just foo`/`just foo-bar`, located in `justfile`s in the repo (though some may have changed names slightly). This requires having [just](https://just.systems/man/en/) installed.

**Pull request merged**
