### PR TITLE
txmgr: call `EstimateGas` correctly for blob tx

### PR DESCRIPTION
**Pull request by zhiqiangxu**
`SimpleTxManager` is a generic tool for sending tx used by various components, and the candidate tx may be a blob tx.

This PR makes `EstimateGas` work correctly for blob tx.

### CODE REVIEW

**Review by geoknee — COMMENTED** [review]
Thanks @zhiqiangxu. Are you able to add or modify unit tests for this?

**Comment by zhiqiangxu** [comment]
Is there an example for such test? 

It needs to be like:

1. Prepare a contract that's requiring tx blob(e.g., revert if no blob)
2. Do estimation to call it.


Without this PR it should revert.

**Comment by geoknee** [comment]
> Is there an example for such test?
> 
> It needs to be like:
> 
> 1. Prepare a contract that's requiring tx blob(e.g., revert if no blob)
> 2. Do estimation to call it.
> 
> Without this PR it should revert.

I don't think we need to go to those lengths. I was thinking we could trigger the code path in question inside this test or variant of it where the `candidate.GasLimit = 0`: 
https://github.com/ethereum-optimism/optimism/blob/2526dc09a747bfe3cdd5ab86e1d9b7a4bd6b1769/op-service/txmgr/txmgr_test.go#L590-L612

Then we would need to assert that the gas limit is estimated high enough. If you run the test with and without your changes, I think you would expect different gas in each case -- this helps to understand the nature of the bug here.

**Comment by zhiqiangxu** [comment]
Sorry I don't quite understand how's your plan to test it.

The original implementation doesn't carry the blob hash over when estimating, but it doesn't necessarily lead to higher or lower gas IMO.

**Comment by geoknee** [comment]
Ah yes I think you are right, the transaction will be charged for blobGas but this is independent of the regular gas estimated in `backend.EstimateGas`.  But this then begs the question, what difference does it make to put the blob information inside the call to `EstimateGas`? Is it not working correctly already?

**Comment by zhiqiangxu** [comment]
> Ah yes I think you are right, the transaction will be charged for blobGas but this is independent of the regular gas estimated in `backend.EstimateGas`. But this then begs the question, what difference does it make to put the blob information inside the call to `EstimateGas`? Is it not working correctly already?

Yeah it will not work for a contract that's requiring tx blob(e.g., revert if no blob) or any contract that's making use of blobs.

It's quite hard to simulate it in unit test, but I'm quite confident it's a correct change.

**Review by geoknee — APPROVED** [review]

**Comment by geoknee** [comment]
I see, the gas estimation could completely in that corner case. On reflection it doesn't seem worth the effort to add any more tests for this.

**Pull request merged**
