### PR TITLE
fix: start the batch submitter properly

### PR DESCRIPTION
**Pull request by gakonst**
fixes bug introduced in https://github.com/ethereum-optimism/optimism/pull/538/commits/933880d443538d413f8bac6488e34b3339078ad5

### CODE REVIEW

**Review by annieke — APPROVED** [review]
oop

**Review by ben-chain — APPROVED** [review]
Thank you @gakonst !! <3

**Comment by snario** [comment]
Removed ability for administrators to merge pull requests before **integration** job passes. My bad.

**Comment by snario** [comment]
Looks like this hit the flickering test #430.

**Pull request merged**
