### PR TITLE
devnet: Convert devnet-allocs to Anvil

### PR DESCRIPTION
**Pull request by mslipper**
Converts devnet-allocs to use Anvil rather than dev mode Geth. This should both be faster than dev mode geth, as well as more reliable since there's an issue with devnet geth hanging during builds.

### CODE REVIEW

**Comment by tynes** [comment]
We should be able to delete `.gethrc` and any refs, see `git grep -rin gethrc`

**Comment by mslipper** [comment]
Ok - after profiling this the speed is the same as devnet Geth, mostly because the devnet-allocs step builds the contracts. However, I still think this should help a lot with the problems we're seeing with allocs hanging so I'm still in favor of merging.

**Comment by mslipper** [comment]
> We should be able to delete .gethrc and any refs, see git grep -rin gethrc

This just removes Geth for the devnet allocs - we still use it elsewhere in the devnet, so we can't remove `.gethrc`.

**Review by ajsutton — APPROVED** [review]

**Comment by tynes** [comment]
> > We should be able to delete .gethrc and any refs, see git grep -rin gethrc
> 
> This just removes Geth for the devnet allocs - we still use it elsewhere in the devnet, so we can't remove `.gethrc`.

Are you sure that we need the geth binary around for anything else? I added it for generating the allocs. We need a docker image for the devnet, not the raw binary

**Comment by mslipper** [comment]
@tynes we read it from within CI builder to install the right Geth version, which includes things like abigen.

**Pull request merged**
