### PR TITLE
l2geth: Add commands to initialize from a URL, and dump the current chainstate

### PR DESCRIPTION
**Pull request by mslipper**
This PR adds two commands to l2geth:

- `geth init <url> <genesisHash>`, which will download a remote genesis JSON file, compare its hash to the one specified on the CLI, then reinitialize the chain config.
- `geth dump-chain-cfg`, which will dump the current chain config to stdout.

These commands will make it easier for us to adopt the upcoming gas schedule hardfork.

Fixes: ENG-1906

### CODE REVIEW

**Comment by tynes** [comment]
Do you mind adding a changeset for this?

**Comment by mslipper** [comment]
My bad. Changeset added.

**Review by tynes — APPROVED** [review]

**Comment by tynes** [comment]
Looks like a linting error needs to be fixed, but the functionality looks good to me

**Comment by mslipper** [comment]
Cool, will fix the lint error then merge.

**Pull request merged**
