### PR TITLE
INF-22 integrate op-signer client with op-proposer

### PR DESCRIPTION
**Pull request by zhwrd**

### CODE REVIEW

**Comment by zhwrd** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #4724** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/4724" target="_blank">Graphite</a> 
    * **PR #4725** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/4725" target="_blank">Graphite</a> 
      * **PR #4726** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/4726" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/optimism/4726?utm_source=stack-comment).

**Comment by zhwrd** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #4724** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/4724" target="_blank">Graphite</a> 
    * **PR #4725** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/4725" target="_blank">Graphite</a> 
      * **PR #4726** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/4726" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/optimism/4726?utm_source=stack-comment).

**Comment by mslipper** [comment]
Code LGTM. I took a look at the conflicts, it looks like the proposer cleanup PR introduces some API incompatibilities with the way the signer is getting passed around. Will approve once conflicts are resolved.

**Review by trianglesphere — APPROVED** [review]
lgtm

**Pull request merged**
