### PR TITLE
op-batcher: Sanity check block for non-empty transactions

### PR DESCRIPTION
**Pull request by Inphi**

### CODE REVIEW

**Comment by tynes** [comment]
This is technically a hard fork

**Comment by Inphi** [comment]
How so? Without the check, op-batcher will panic if there aren't any transactions.

**Comment by ajsutton** [comment]
Given we access the first transaction in the block immediately after this to check its a deposit transaction, I'd expect batches with no transactions to already be rejected, just with a much less clear message.

Would be good if we can write a test for this though - running it without this extra check should reproduce the panic and with it would then return an error.

**Review by ajsutton — APPROVED** [review]
LGTM but will need a review from proto or Josh anyway. Given this is in the the derivation code does it trigger a reset of the code freeze period?

**Comment by Inphi** [comment]
Technically (or not) it shouldn't. Because the `BlockToBatch` function is only used by the batcher. I'm unsure if the batcher is also subject to the code freeze.

**Review by protolambda — APPROVED** [review]

**Pull request merged**
