### PR TITLE
fix: ensure hardhat does not fail if no input sources provided

### PR DESCRIPTION
**Pull request by snario**
Implementing proposed fix from https://github.com/ethereum-optimism/optimism/issues/674.

### CODE REVIEW

**Comment by snario** [comment]
ERC20-Example failed unit tests.

```
  1) ERC20 smart contract
       when using a deployed contract instance
         "before all" hook for "should assigns initial balance":
     Error: missing response (requestBody="{\"method\":\"eth_accounts\",\"params\":[],\"id\":46,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":9545}, url="http://127.0.0.1:9545", code=SERVER_ERROR, version=web/5.1.0)
      at Logger.makeError (/home/runner/work/optimism/optimism/node_modules/@ethersproject/logger/lib/index.js:180:21)
      at Logger.throwError (/home/runner/work/optimism/optimism/node_modules/@ethersproject/logger/lib/index.js:189:20)
      at /home/runner/work/optimism/optimism/node_modules/@ethersproject/web/lib/index.js:213:36
      at step (/home/runner/work/optimism/optimism/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.throw (/home/runner/work/optimism/optimism/node_modules/@ethersproject/web/lib/index.js:14:53)
      at rejected (/home/runner/work/optimism/optimism/node_modules/@ethersproject/web/lib/index.js:6:65)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by snario** [comment]
Will need to revisit this later, unclear why the test above is failing.

**Review by smartcontracts — APPROVED** [review]
LGTM

**Comment by smartcontracts** [comment]
Dismissed my previous review - needs changeset so this can be propagated into an `npm` release.

**Review by smartcontracts — CHANGES_REQUESTED** [review]
Requesting a changeset

**Review by gakonst — APPROVED** [review]

**Pull request merged**
