### PR TITLE
added internal and external imports separation within integration tests

### LINKED ISSUE #2017: Separate internal and external imports within integration tests
**Is your feature request related to a problem? Please describe.**
I have a habit of separating internal and external imports inside of TypeScript files. This makes it very easy to see which utilities are being pulled in from external dependencies. Our goal should be to eventually replace many of our external dependencies with simple functions of our own (for security reasons), so it's ideal to be able to quickly see when there are unnecessary external imports. Some of our integration tests currently have this, but others do not. It should be easy to standardize the remaining files around this pattern.

**Describe the solution you'd like**
Standardize all of the TypeScript files within `integration-tests/tests` around the pattern described above. Here's an example of how to organize the imports:

https://github.com/ethereum-optimism/optimism/blob/e634bf2ca62b895db678531c4488aa2d2e2e1a2c/integration-tests/test/basic-l1-l2-communication.spec.ts#L1-L12

Note the `/* Imports: External */` and `/* Imports: Internal */` comments that define the two sections. External imports first, then internal imports. Also note that `import { expect } from './shared/setup'` should always be at the top of the file. See here for an example of a file where the imports need to be cleaned up:

https://github.com/ethereum-optimism/optimism/blob/e634bf2ca62b895db678531c4488aa2d2e2e1a2c/integration-tests/test/native-eth-ovm-calls.spec.ts#L1-L10

This should be:

```ts
import { expect } from './shared/setup' 

/* Imports: External */
import { BigNumber, Contract, ContractFactory, Wallet } from 'ethers' 
import { ethers } from 'hardhat' 

/* Imports: Internal */
import { 
  fundUser, 
  encodeSolidityRevertMessage, 
  gasPriceForL2, 
} from './shared/utils' 
import { OptimismEnv } from './shared/env' 
```

### PR DESCRIPTION
**Pull request by lucadonnoh**
**Description**
Separated internal and external imports in integration tests

**Additional context**
Some comments where missing, others were wrong (Internal and External switched)

**Metadata**
- Fixes #2017

### CODE REVIEW

**Comment by smartcontracts** [comment]
Unfortunately I'm having issues seeing the integration test error on my current wifi. Going to take another look at this later tonight.

**Comment by indeavr** [comment]
I would also recommend we add a sorting order to eslint:

current: 
```json5
'import/order': 'off'
```
New: 
```json5
'import/order': [
      1,
      {
        groups: [
          'external',
          'builtin',
          'internal',
          'sibling',
          'parent',
          'index',
        ],
        'newlines-between': 'always',
      },
    ],
```
The `groups` property defines the order :)

**Comment by smartcontracts** [comment]
> I would also recommend that we enforce this order in eslint (top level - .eslintrc.js):
> 
> current:
> 
> ```js
> 'import/order': 'off'
> ```
> 
> New:
> 
> ```js
> 'import/order': [
>       1,
>       {
>         groups: [
>           'external',
>           'builtin',
>           'internal',
>           'sibling',
>           'parent',
>           'index',
>         ],
>         'newlines-between': 'always',
>       },
>     ],
> ```
> 
> The `groups` property defines the order :)

Whoa! I didn't know this was a thing we could do. I'll make an issue for this :-)

**Comment by smartcontracts** [comment]
@lucadonnoh looks like this just needs a quick rebase to fix the merge conflicts. Great work as usual!

**Comment by lucadonnoh** [comment]
sorry for the mess, i'm just learning how to contribute to a repo! 😅

**Comment by smartcontracts** [comment]
Haha, no worries @lucadonnoh. Just let me know if you need any help!

**Comment by tynes** [comment]
This unfortunately now has merge conflicts and needs to be fixed

**Comment by mslipper** [comment]
This is already complete - closing for now.

**Pull request closed without merging**
