### PR TITLE
Fix op-proposer & withdrawals logic

### PR DESCRIPTION
**Pull request by trianglesphere**
**Description**
A clear and concise description of the features you're adding in this pull request.

Includes some test changes, some utility changes, and some op-proposer changes.

Fixes ENG-2227

### CODE REVIEW

**Comment by trianglesphere** [comment]
Ok, some of the flakiness (I think) is due to it running a proof against the block that the withdrawal was in. I think this should be valid, but it works better if I go another submission window into the future.

**Comment by trianglesphere** [comment]
With logging, still happens when the block for of the tx is prior to the proof block. Looking into some other things now
```
joshua@opti op-e2e % go test . -v -run Withdrawals -count=10  
=== RUN   TestWithdrawals
Withdrawal included in block 7
Getting proof for block  8
--- PASS: TestWithdrawals (19.37s)
=== RUN   TestWithdrawals
Withdrawal included in block 7
Getting proof for block  8
--- PASS: TestWithdrawals (17.99s)
=== RUN   TestWithdrawals
Withdrawal included in block 7
Getting proof for block  8
--- PASS: TestWithdrawals (20.00s)
=== RUN   TestWithdrawals
Withdrawal included in block 7
Getting proof for block  8
--- PASS: TestWithdrawals (18.00s)
=== RUN   TestWithdrawals
Withdrawal included in block 7
Getting proof for block  8
    system_test.go:795: 
        	Error Trace:	system_test.go:795
        	Error:      	Expected nil, but got: &fmt.wrapError{msg:"failed to validate storage proof 0: failed to verify proof: proof node 0 (hash 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421) missing", err:(*fmt.wrapError)(0x14006e307c0)}
        	Test:       	TestWithdrawals
--- FAIL: TestWithdrawals (16.97s)
=== RUN   TestWithdrawals
Withdrawal included in block 7
Getting proof for block  8
--- PASS: TestWithdrawals (18.02s)
=== RUN   TestWithdrawals
Withdrawal included in block 8
Getting proof for block  8
    system_test.go:795: 
        	Error Trace:	system_test.go:795
        	Error:      	Expected nil, but got: &fmt.wrapError{msg:"failed to validate storage proof 0: failed to verify proof: proof node 0 (hash 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421) missing", err:(*fmt.wrapError)(0x1400586fec0)}
        	Test:       	TestWithdrawals
--- FAIL: TestWithdrawals (16.98s)
=== RUN   TestWithdrawals
Withdrawal included in block 7
Getting proof for block  8
--- PASS: TestWithdrawals (18.02s)
=== RUN   TestWithdrawals
Withdrawal included in block 7
Getting proof for block  8
--- PASS: TestWithdrawals (19.99s)
=== RUN   TestWithdrawals
Withdrawal included in block 8
Getting proof for block  8
    system_test.go:795: 
        	Error Trace:	system_test.go:795
        	Error:      	Expected nil, but got: &fmt.wrapError{msg:"failed to validate storage proof 0: failed to verify proof: proof node 0 (hash 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421) missing", err:(*fmt.wrapError)(0x1400800aee0)}
        	Test:       	TestWithdrawals
--- FAIL: TestWithdrawals (15.98s)
```

**Comment by trianglesphere** [comment]
I think I got this resolved by switching over to doing the L2 checks on the verifier, not the sequencer.

**Comment by maurelian** [comment]
Going to steal this commit onto #2707.

**Pull request closed without merging**
