### PR TITLE
Draft:  Add ERC721 token

### PR DESCRIPTION
**Pull request by platocrat**
**Description**
A draft to add the ERC-721 standard to the `contracts` package.

**Additional context**
Working with Discord user @fracek

### CODE REVIEW

**Comment by tynes** [comment]
@platocrat instead of merging develop into this branch like in https://github.com/ethereum-optimism/optimism/pull/1313/commits/bd6fb9ed29afc5257b8b7ace3e5461a268721318, we are trying to keep a cleaner git history by using a rebasing workflow. If you are planning on continuing work on this PR, could you drop that commit and instead rebase onto develop?

**Comment by platocrat** [comment]
> @platocrat instead of merging develop into this branch like in [bd6fb9e](https://github.com/ethereum-optimism/optimism/commit/bd6fb9ed29afc5257b8b7ace3e5461a268721318), we are trying to keep a cleaner git history by using a rebasing workflow. If you are planning on continuing work on this PR, could you drop that commit and instead rebase onto develop?

Sorry about that 😅

**Comment by platocrat** [comment]
I just merged @fracek's changes against my repo so that i could @fracek as a participant in this PR :)

**Comment by fracek** [comment]
I pushed a new set of changes:

* I created a new bridge for ERC 721 tokens. My rationale is to make it easier to deploy them on OP since I don't know how feasible it is to change the standard bridge.
* The `L2StandardERC72`1 contract supports `ERC721` only, no extensions like `ERC721Metadata`. The idea is that developers should use the L1 contract to get the token metadata since it may have custom logic. The L2 token only represents ownership.
* ERC721 `safeTransferFrom` fails if the receiver is a smart contract that doesn't support the `ERC721Holder` interface. Since the transfer is now a two step process I'm worried that the NFT becomes unrecoverable.

**Comment by maurelian** [comment]
Thanks for your hard work here @platocrat and @fracek. 
I just pushed this with a rebase on `develop`, and fixed some simple linter errors.
We're starting work on a spec to better understand what an MVP bridge would require, this looks like a good start for an impl to build on.

**Comment by maurelian** [comment]
A few questions we're thinking about, and I'm curious if you have and thoughts about them:

1. How to handle minting of tokens on the L2 NFT contract, while ensuring that there are no collisions with existing IDs on the L1 contract. 
2. How to go about pass the `tokenURI` metadata from L1 to L2 on deposit (if at all)? 
    - ie. does it need to be included in the `_data` that's passed across, or should we just assume that the data can/should remain on L1 and can be referenced there by any front-end interfaces?

**Comment by fracek** [comment]
>  1. How to handle minting of tokens on the L2 NFT contract, while ensuring that there are no
> collisions with existing IDs on the L1 contract.

I think only the bridge should be able to mint tokens, and it only mints when users deposit into OP. Since tokens are burned on withdrawal to L1, I don't think it's possible to have collisions.

> 2. How to go about pass the `tokenURI` metadata from L1 to L2 on deposit (if at all)?
>        
>  * ie. does it need to be included in the `_data` that's passed across, or should we just assume that the data can/should remain on L1 and can be referenced there by any front-end interfaces?

IMHO L2 tokens should only represent ownership of the original L1 tokens. Applications that need to display the NFT should query data from L1. Some NFTs (like the [DVD Logo](https://opensea.io/assets/0x68a65e7968fbacd2387dad316918da69a7011608/1) NFT) have a token URI that changes every block and so if we simply passed the `tokenURI` on deposit we would get the wrong behavior.

**Comment by fracek** [comment]
I think the main insight is that what I propose is a L1 -> L2 bridge since the "canonical" token is on L1.
 I start with the assumption that it's not possible to mirror ERC-721 tokens between networks since the original ERC-721 may have custom behavior (like the DVD logo I linked above).
I basically consider an NFT as "ownership" + "other stuff", where "other stuff" is usually the token metadata but sometimes it's code (or something else, it could be anything). Ownership on the other hand is easy and so we can bridge it on L2.

**Comment by maurelian** [comment]
> I think the main insight is that what I propose is a L1 -> L2 bridge [0] since the "canonical" token is on L1.

Agree, that is a powerful simplifying assumption and might be an OK starting place, but I think we need to do a bit more research talking to projects about their needs. 

I wouldn't want to get into a situation where we launch this an MVP, then find out they want to mint on L2, but people have already started moving their tokens into a non-compatible ERC721 implementation on L2.

I'll do my best to keep you updated here.

**Comment by tynes** [comment]
Any updates on this PR? Is it being actively developed?

**Comment by maurelian** [comment]
> Any updates on this PR? Is it being actively developed?

@tynes: No, doesn't look like it. 

@platocrat @fracek: I promised to keep you updated. So FYI we've deprioritized this project, but I expect we'll pick it back up in a couple weeks. We really appreciate your contributions, and my preference would be for these commits to be included as I think it's a great foundation that we can build on.

I'll reach out then, but for now will close this just to keep the PR list clean. 🦾

**Pull request closed without merging**
