### PR TITLE
ci-builder: bump go tool versions

### PR DESCRIPTION
**Pull request by sebastianst**
**Description**

Updates some go tooling in ci-builder.

**Additional context**

The mockery version in ci-builder failed for me locally when I tried to generate a new mock in https://github.com/ethereum-optimism/optimism/pull/12069, so taking the opportunity to update some tooling.

### CODE REVIEW

**Review by Inphi — APPROVED** [review]
Looks good. Is there a ci check that makes sure the mocks were generated correctly? It'll be good to have that in, though that can be done in another PR.

**Review by axelKingsley — APPROVED** [review]
There's three changes here:
* golangci-lint command line update to include "run"
* updated versions for `ci-builder`, `golangci-lint`, `mockery`, `gotestsum` and `v4`.
* Updated mocks from the new mockery.

The only thing I can't say for certain is the particular version numbers selected -- how did you determine these versions (or auto update)?

**Comment by sebastianst** [comment]
> Looks good. Is there a ci check that makes sure the mocks were generated correctly? It'll be good to have that in, though that can be done in another PR.

@Inphi yes, these checks exist. In fact, ci would fail hadn't I updated the mocks 🚀

**Comment by sebastianst** [comment]
> The only thing I can't say for certain is the particular version numbers selected -- how did you determine these versions (or auto update)?

I manually selected the latest versions of each tool @axelKingsley

**Comment by Inphi** [comment]
> > Looks good. Is there a ci check that makes sure the mocks were generated correctly? It'll be good to have that in, though that can be done in another PR.
> 
> @Inphi yes, these checks exist. In fact, ci would fail hadn't I updated the mocks 🚀 

How did ci pass before when the mocks were first broken? Are the checks run on a schedule?

**Comment by sebastianst** [comment]
> How did ci pass before when the mocks were first broken? Are the checks run on a schedule?

I first updated the ci-builder Docker file on this branch, then released it based on this WIP branch, then once published, bumped the version on this branch. So during the intermediary stage, CI was actually broken.

**Pull request merged**
