### PR TITLE
ctb: Add an assert for unreachable condition

### PR DESCRIPTION
**Pull request by maurelian**
**Description**

Adds another assertion to explicitly identify an invariant which was previously implicit.

**Tests**

No new tests. Since the condition is unreachable it will require a more advanced testing setup than we currently have to check this properly.

### CODE REVIEW

**Review by smartcontracts — APPROVED** [review]

**Review by tynes — APPROVED** [review]

**Comment by tynes** [comment]
Looks like a linting error
```
contracts/universal/CrossDomainMessenger.sol

║ Line     │ Column   │ Type     │ Message                                                │ Rule ID              ║
╟──────────┼──────────┼──────────┼────────────────────────────────────────────────────────┼──────────────────────╢
║ 30       │ 5        │ warning  │ Variable name must be in mixedCase                     │ var-name-mixedcase   ║
║ 100      │ 5        │ warning  │ Variable name must be in mixedCase                     │ var-name-mixedcase   ║
║ 107      │ 5        │ warning  │ Variable name must be in mixedCase                     │ var-name-mixedcase   ║
║ 291      │ 2        │ error    │ Line length must be no more than 100 but current       │ max-line-length      ║
║          │          │          │ length is 101.                                         │                      ║
```

**Comment by tynes** [comment]
@maurelian This needs a rebase and should build fine in CI now that a fix for the build cache was merged

**Comment by tynes** [comment]
I haven't seen this flake before

```
    system_test.go:301: 
        	Error Trace:	/root/project/op-e2e/system_test.go:301
        	Error:      	Should not be zero, but was 0
        	Test:       	TestFinalize
        	Messages:   	must have finalized L2 block
```

**Comment by maurelian** [comment]
@mergify_io reset

**Comment by maurelian** [comment]
@mergify reset

**Comment by maurelian** [comment]
@mergifyio reset

**Comment by maurelian** [comment]
@Mergifyio refresh

**Pull request merged**
