### PR TITLE
fix: decrease default ynatm retry timeout

### PR DESCRIPTION
**Pull request by smartcontracts**
**Description**
Our `ynatm` resubmission timeout was totally wrong. We were supplying a default resubmission interval of 1,000,000 ms = ~16.66 mins. Then we were multiplying by 1000 again:
https://github.com/ethereum-optimism/optimism/blob/68d8290bf0c86217a26afede41f4e62197b951ae/packages/batch-submitter/src/exec/run-batch-submitter.ts#L357

So if anything ever went wrong with the batch submission, we were waiting ~11.5 *days* to resubmit by default. Whoops. I believe this is the source of https://github.com/ethereum-optimism/optimism/issues/430

### CODE REVIEW

**Comment by smartcontracts** [comment]
Resubmission time here is set to 1 second by default now. I would recommend that we check whether this will conflict with production and make sure we're using the correct resubmission time in our production environment.

**Review by karlfloersch — APPROVED** [review]
Oh wow yeah that was very wrong. 

 LGTM! great catch!

Oh you should add a changeset @smartcontracts

**Comment by smartcontracts** [comment]
Does ops need changesets?

**Comment by tynes** [comment]
I wouldn't be opposed to versioning ops but I don't think we have been doing it - no big deal to not

**Comment by gakonst** [comment]
No changeset required!

**Pull request merged**
