### PR TITLE
Fix the deposits.md spec

### PR DESCRIPTION
**Pull request by bap2pecs**
I think the description at https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/contracts/L2/L1Block.sol#L42 makes more sense

### CODE REVIEW

**Review by trianglesphere — CHANGES_REQUESTED** [review]
Hey, I don't think we'll be bringing in this exact change.

The contracts definition is shorter, but does not capture the fact that the sequence number is different for every block in the epoch. It is very explicitly not "number of L2 blocks in the same epoch" but the "number of the specific L2 block inside the epoch".

**Comment by bap2pecs** [comment]
thanks @trianglesphere for the review! But I am still a bit confused about this field.

iiuc, the value in this predeploy contract will be changed in the first transaction in the first L2 block of the epoch. It will remain unchanged until the next epoch.

If this is correct, it represents a different thing as the "sequence number" you mentioned in

> the sequence number is different for every block in the epoch

**Comment by trianglesphere** [comment]
> first transaction in the first L2 block of the epoch

It is changed in the first transaction of every L2 block. Every L2 block has an [L1 attributes tx](https://github.com/ethereum-optimism/optimism/blob/develop/specs/glossary.md#l1-attributes-deposited-transaction)

**Comment by bap2pecs** [comment]
ah I see. thanks for the clarification @trianglesphere. closing out this PR.

**Pull request closed without merging**
