### PR TITLE
chore(bedrock): remove unused variables from utils

### PR DESCRIPTION
**Pull request by greenlucid**
**Description**

The issue referenced below is extremely concise on what's being solved.

**Tests**

No need, these variables were not used anywhere.

**Additional context**

This is a simple issue intended for newcomers into the repo.

**Metadata**
- Fixes [#3838](https://github.com/ethereum-optimism/optimism/issues/3838)

### CODE REVIEW

**Comment by greenlucid** [comment]
I got it wrong, disregard

**Comment by smartcontracts** [comment]
Oh wait shoot, `isHardhatNode` can't be deleted. You should be able to delete the others though.

**Comment by greenlucid** [comment]
Should've read the README, I just rushed through. Should be better now, although, I couldn't get this package to install, so I cannot run tests.
image

**Comment by smartcontracts** [comment]
@greenlucid for that package you'll need to build the monorepo. You can do that with `yarn build` at the root of the monorepo.

**Comment by maurelian** [comment]
Stale closing.

**Pull request closed without merging**
