### PR TITLE
ci: Add Mergify

### PR DESCRIPTION
**Pull request by mslipper**
This PR adds support for [Mergify](https://mergify.com), a tool that automates PR review. It uses a YAML file to define a set of review rules. The rules I've enabled for this repo are the following:

- Normally, PRs are auto merged after required checks pass and they have two or more approving reviews.
- PRs labeled with `SR-Risk` or `C-Protocol-Critical` can be auto-merged after a review from @maurelian or @tynes/@smartcontracts, respectively.
- PRs are squashed and merged to avoid lots of tiny commits. I've enabled that at the repo level.
- PRs labeled with `SR-Risk` receive a comment asking for additional info on the shape of the security risk intorduced by the PR.
- PRs that change l2geth Go code or DTL Typescript code automatically receive the `C-Protocol-Critical` label and request @tynes and @smartcontracts as reviewers.
- Otherwise, the bot requests 2 random members of the systems team to review.
- PRs with merge conflicts receive a comment asking for them to be resolved.

I've also removed `CODEOWNERS` since this replaces it.

### CODE REVIEW

**Comment by tynes** [comment]
why not delete codeowners or rename the file?

**Comment by mslipper** [comment]
> why not delete codeowners or rename the file?

It had been commented out previously to keep around the original list of owners. I'm not married to this either way.

**Review by tynes — APPROVED** [review]

**Comment by tynes** [comment]
> > why not delete codeowners or rename the file?
> 
> It had been commented out previously to keep around the original list of owners. I'm not married to this either way.

Ok i'm not super opinionated, I have a slight preference for deleting it because it will likely go stale if its commented out

**Comment by mslipper** [comment]
> > > why not delete codeowners or rename the file?
> > 
> > 
> > It had been commented out previously to keep around the original list of owners. I'm not married to this either way.
> 
> Ok i'm not super opinionated, I have a slight preference for deleting it because it will likely go stale if its commented out

FIxed.

**Pull request merged**
