### PR TITLE
Remove obsoleted integration tests

### PR DESCRIPTION
**Pull request by elenadimitrova**
Remove `read-proxy-event.spec.ts` and `erc20.spec.ts` tests as well as some obsoleted integration tests contracts.

Closes ENG-1327

### CODE REVIEW

**Comment by K-Ho** [comment]
Rather than removing, I'd rather just replace the single line of 
`npx hardhat --config ./hardhat.config.js test:integration:l2 --compile --deploy`
with 
`npx hardhat --config ./hardhat.config.js test:integration:dual --compile --deploy`

https://github.com/ethereum-optimism/optimism/pull/1261

**Review by smartcontracts — APPROVED** [review]
LGTM. I think it's fine to remove all of this.

**Comment by smartcontracts** [comment]
Errr ok I see the point about the `dual` SNX tests. Not 100% sure how I feel about it.

**Comment by elenadimitrova** [comment]
I tried the `test:integration:dual` run here https://github.com/ethereum-optimism/optimism/runs/3614189833?check_suite_focus=true and that errors with
```
Error: fee too low: 2350710000000, use at least tx.gasLimit = 1626714 and tx.gasPrice = 15000000
```
@K-Ho is it because they haven’t updated the gasPrice in their config to be non-zero and set to 15000000?

**Comment by smartcontracts** [comment]
I vote we just skip the SNX tests and figure out a new ticket for running external tests + figure out exactly which external tests we want to run

**Pull request merged**
