### PR TITLE
Define L1 Starting block via OwnershipTransferred rather than AddressSet

### PR DESCRIPTION
**Pull request by CAPtheorem**
1. In the current boot up of the system, the `ownable` AddressManger is deployed, there is an `OwnershipTransferred` event in block 1 (relatively or absolutely speaking) and then there are numerous `AddressSet` events in blocks 2... onwards (see below for condensed log). There are three considerations: (1) it might make sense to define `startingL1BlockNumber` to coincide with block 1 rather than block 2 of a standard deployment, (2) `OwnershipTransferred` is a *unitary* event, rather than `AddressSet`, which occurs multiple times, and (3) for unclear reasons, sometimes `AddressSet` events are not found, breaking the DTL (=`Unable to find appropriate L1 starting block number`), whereas the `OwnershipTransferred` event seems to be found more reliably. 
2. The proposed change addresses https://github.com/ethereum-optimism/optimism/issues/1126
3. Be advised that there is an even better solution to this, proposed by @tynes, https://github.com/ethereum-optimism/optimism/issues/1126#issuecomment-864450020.  

```
l1_chain_1           | eth_getLogs
dtl_1                | All events: [
dtl_1                |   {
dtl_1                |     blockNumber: 1,
dtl_1                |     address: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
dtl_1                |     topics: [
dtl_1                |       '0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0',
dtl_1                |     ],
dtl_1                |     event: 'OwnershipTransferred',
dtl_1                |     eventSignature: 'OwnershipTransferred(address,address)',
dtl_1                |   },
dtl_1                |   {
dtl_1                |     blockNumber: 2,
dtl_1                |     address: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
dtl_1                |     topics: [
dtl_1                |       '0x188466739ff00cc68bfb2367d23ae4b855264264fe1624caa8884399af23454c'
dtl_1                |     ],
dtl_1                |     event: 'AddressSet',
dtl_1                |     eventSignature: 'AddressSet(string,address)',
dtl_1                |   },
dtl_1                |   {
dtl_1                |     blockNumber: 3,
dtl_1                |     address: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
dtl_1                |     topics: [
dtl_1                |       '0x188466739ff00cc68bfb2367d23ae4b855264264fe1624caa8884399af23454c'
dtl_1                |     ],
dtl_1                |     event: 'AddressSet',
dtl_1                |     eventSignature: 'AddressSet(string,address)',
dtl_1                |   },
```

Fixes OP-893

### CODE REVIEW

**Comment by CAPtheorem** [comment]
Update: this PR may also fix some issues with the `verifier` and the sync-tests, `sync-verifier.spec.ts`, that are seen in certain system configurations. Confirming now.

**Review by smartcontracts — COMMENTED** [review]
Looks good to me! Would you mind adding a changeset? Just run `npx changeset` at the root and follow the prompts.

**Comment by tynes** [comment]
Note that the unit tests failing is a false alarm - codechecks fails for outside contributors.

**Review by tynes — APPROVED** [review]

**Review by tynes — CHANGES_REQUESTED** [review]
I cannot approve until there is a changeset, sorry

**Comment by CAPtheorem** [comment]
Sure; done.

**Review by snario — APPROVED** [review]

**Review by smartcontracts — APPROVED** [review]

**Pull request merged**
