### PR TITLE
maint: move existing interfaces to folders

### LINKED ISSUE #11684: EVM Engineering: move existing interfaces into subfolders
All interfaces will live inside `interface` subfolders within each main contracts package. For example, interfaces for L1 contracts will live inside `src/L1/interfaces`. We need to move all interfaces that do not currently conform to this pattern into their respective `interfaces` folders.

### PR DESCRIPTION
**Pull request by smartcontracts**
Moves any existing interfaces that are not already inside of their corresponding /interfaces folders into those folders.

Closes #11684

### CODE REVIEW

**Review by Inphi — COMMENTED** [review]
This looks good. Could we hold off on merging until https://github.com/ethereum-optimism/optimism/pull/11760 is merged? This is so we can tag an op-contracts/v1.6.0 release on a commit on develop.

**Comment by smartcontracts** [comment]
> This looks good. Could we hold off on merging until #11760 is merged? This is so we can tag an op-contracts/v1.6.0 release on a commit on develop.

My understanding of the release process is that we're supposed to tag `op-contracts/v1.6.0` off of a commit on top of `op-contracts/v1.6.0-rc.3` that removes the RC tags from all contracts. cc @mds1 just want to confirm if that understanding is correct.

Otherwise we'd always have this situation where contracts that are in the process of being approved by governance can't be touched by any other changes which would be a bit of a pain.

**Comment by Inphi** [comment]
> My understanding of the release process is that we're supposed to tag `op-contracts/v1.6.0` off of a commit on top of `op-contracts/v1.6.0-rc.3` that removes the RC tags from all contracts. cc @mds1 just want to confirm if that understanding is correct.

Going by this [section on contract releases](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/VERSIONING.md#release-process):

> Once governance approves the proposal, merge the proposal branch into develop and set the version of all contracts to the appropriate X.Y.Z after considering any changes made to develop since the release candidate was created.

It does imply that only non-breaking changes should be made to `develop` while there's a tentative release.
Perhaps for this change, since it's just a mechanical refactor, we should bump the `-beta` or `-rc` semver suffix rather than the minor version.

**Comment by mds1** [comment]
The official release gets tagged off the `proposal/op-contracts/v1.6.0` branch. We do this precisely because we can't guarantee no changes to develop throughout the governance cycle, like @smartcontracts mentioned above

> Once governance approves the proposal, merge the proposal branch into develop and set the version of all contracts to the appropriate X.Y.Z after considering any changes made to develop since the release candidate was created.

This part is just describing how to merge any changes from that branch back into develop

**Comment by mds1** [comment]
@Inphi @smartcontracts Let me know if this clears it up: https://github.com/ethereum-optimism/optimism/pull/11761

**Comment by Inphi** [comment]
> @Inphi @smartcontracts Let me know if this clears it up: #11761

That clarifies it. Thanks. We can merge this then. I was also a bit worried about losing track of tagged releases if we delete the `proposal/op-contracts/X` branch. However, github will apparently not prune the tagged commit.

**Review by Inphi — APPROVED** [review]

**Review by Abuchtela — COMMENTED** [review]
- [ ] merge #11749

**Comment by Java7981** [comment]
Gooooood 🎉 🎉

**Pull request merged**
