### PR TITLE
feat(ctb): remove DeployConfig

### PR DESCRIPTION
**Pull request by smartcontracts**
**Description**
Removes the DeployConfig contract. It seems this contract might've been reintroduced as part of a merge conflict. We don't need this contract anymore because all of the relevant structs are contained within the BaseSystemDictator contract.

### CODE REVIEW

**Review by maurelian — APPROVED** [review]

**Comment by tynes** [comment]
Looks like the bindings are breaking due to the ERC20 problem. Do we use 2 different ERC20 implementations? Perhaps we are importing one of our other contracts packages and it has a diff oz version as a dep?

**Comment by tynes** [comment]
This generally looks good to me, I'm assuming it will fix the build error about the shadowed declaration

**Comment by mslipper** [comment]
This is useful for the migration work in #3897, since I had to add a bunch of duplicate code to `DeployConfig`.

**Comment by mslipper** [comment]
I'll rebuild the `more` files.

**Review by mslipper — APPROVED** [review]

**Comment by smartcontracts** [comment]
@mergifyio requeue

**Comment by tynes** [comment]
```
Error: no supported bridge for token pair
    at CrossChainMessenger.getBridgeForTokenPair (/home/circleci/project/packages/sdk/src/cross-chain-messenger.ts:383:13)
```

This is a strange error to get and leads me to believe the deployment is being misconfigured somehow

**Review by tynes — CHANGES_REQUESTED** [review]
Why does this include changes to the go deps? It seems like its reverting something useful

**Comment by smartcontracts** [comment]
No clue, will revert that diff.

**Review by tynes — APPROVED** [review]

**Pull request merged**
