### PR TITLE
Cancel any inflight block building when stopping the sequencer, to av…

### PR DESCRIPTION
**Pull request by kahuang**
…oid intermediate state.

**Description**

Stop sequencer stops the sequencer,  but doesn't clear intermediate block building state (if already started). This means that if sequencer resumes later, but unsafe heads had been updated in the interim (because another sequencer was running instead), when you'd resume the sequencer it would start building on the previous payload, which could cause a huge reorg.

By cancelling intermediate block building state on stopping sequencer, you don't have this issue on resuming a sequencer.

**Tests**

Ran this on our conduit infra and tested stopping/resuming and verified we start building on the latest unsafe head, versus an old head.

**Additional context**

This is useful for dynamic sequencer election, for auto failover and 0 downtime deploys. You may have long lived sequencers that are started/stopped multiple times during a lifecycle!

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Review by trianglesphere — APPROVED** [review]
Thanks for the fix

**Comment by kahuang** [comment]
@mergifyio requeue

**Comment by kahuang** [comment]
@trianglesphere it seems like the failed checks were unrelated to my change (issues with missing commands and network issues)?

**Comment by trianglesphere** [comment]
@kahuang this is a weird error I haven't seen much before. Can you make sure that your PR has the latest develop merged in?

**Comment by trianglesphere** [comment]
@kahuang indexer test is also broken on develop. We'll have a fix in soon & then you can merge it in and it will work

**Comment by trianglesphere** [comment]
@kahuang develop is fixed now. If you merge it in CI should be passing again

**Comment by kahuang** [comment]
> @kahuang develop is fixed now. If you merge it in CI should be passing again

Done ty

**Pull request merged**
