### PR TITLE
fix(ct): bug in L2OutputOracle constructor

### PR DESCRIPTION
**Pull request by smartcontracts**
**Description**
Fixes a small bug in the L2OutputOracle constructor where an assertion
was being made about the wrong value. Unlikely that this would've caused
any significant issues but worth fixing anyway.

### CODE REVIEW

**Review by maurelian — APPROVED** [review]

**Comment by maurelian** [comment]
I approve this, but now that I think about it we really need to have the discipline of writing a test every time we fix a bug. even when it's a trivial one like this. would really appreciate if you'd be so kind as to oblige me on that.

**Comment by smartcontracts** [comment]
SGTM!

**Comment by smartcontracts** [comment]
> I approve this, but now that I think about it we really need to have the discipline of writing a test every time we fix a bug. even when it's a trivial one like this. would really appreciate if you'd be so kind as to oblige me on that.

Done

**Review by mslipper — APPROVED** [review]

**Comment by mslipper** [comment]
@smartcontracts mind updating the gas snapshot + bindings?

**Review by tynes — APPROVED** [review]

**Comment by tynes** [comment]
This needs code to handle the L1 genesis creation

**Comment by mslipper** [comment]
This is causing a bug somewhere:

```
Failed
=== RUN   TestBuildL1DeveloperGenesis
    layer_one_test.go:32: 
        	Error Trace:	/root/project/op-chain-ops/genesis/layer_one_test.go:32
        	Error:      	Received unexpected error:
        	            	no code found for L2OutputOracle
        	Test:       	TestBuildL1DeveloperGenesis
--- FAIL: TestBuildL1DeveloperGenesis (0.01s)
```

**Comment by mslipper** [comment]
This is breaking tests because the Geth simulated backend that deploys the contracts on L1 in the devnet sets the block timestamp to zero. We can fix this, but it'll require changes in `op-geth`.

**Pull request merged**
