### PR TITLE
feat: add CreateX preinstall

### LINKED ISSUE #11556: Interop: CreateX Preinstall Implementation
Implement CreateX Preinstall, as defined in this [PR](https://github.com/ethereum-optimism/specs/pull/341)

### PR DESCRIPTION
**Pull request by agusduha**
**Description**

Add [CreateX](https://github.com/pcaversaccio/createx) as a Preinstall for future usage.

**Tests**

Test that the preinstall and it's code exist.

**Additional context**

The bytecode was taken from https://optimistic.etherscan.io/address/0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed#code

**Metadata**

- Closes https://github.com/ethereum-optimism/optimism/issues/11556

### CODE REVIEW

**Comment by tynes** [comment]
This looks like its good to merge? I don't think there is any chain specific information in the bytecode?

**Comment by mds1** [comment]
> I don't think there is any chain specific information in the bytecode?

Correct, there is not. So agreed this PR is good to merge, unless there is some reason it's in draft

**Review by tynes — APPROVED** [review]
Confirming the address and bytecode match

**Review by pcaversaccio — COMMENTED** [review]
I would recommend adding a test that the `keccak256` hash of the `CreateX` runtime bytecode equals `0xbd8a7ea8cfca7b4e5f5041d7d4b17bc317c5ce42cfbc42066a00cf26b43eb53f`.

**Pull request merged**
