### PR TITLE
fix(ctb): Output Bisection Alphabet VM

### PR DESCRIPTION
**Pull request by refcell**
**Description**

Creates a temporary, new Alphabet VM (`AlphabetVM2`) to be used in output bisection by supplying the prestate l2 block number as the `bytes32` encoded the local context. This is needed for the output bisection game test actors @clabby is building and also leaves fault dispute game tests to be backwards compatible that use the original alphabet vm.

**Metadata**

Makes progress on https://github.com/ethereum-optimism/client-pod/issues/254

### CODE REVIEW

**Comment by refcell** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #8362** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/8362?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/optimism/8362?utm_source=stack-comment).

**Review by clabby — APPROVED** [review]
LGTM pending CI - will be integrating this with the actor tests in the actor test PR, so any discrepancies in desired behavior can be resolved there. Currently nothing is dependent on this contract, so can merge to unblock that work 😄

**Comment by refcell** [comment]
CI Passing here, just too many items in the merge queue i believe

**Comment by refcell** [comment]
Planning to look into the flaky test after getting some work done today.

**Pull request merged**
