### PR TITLE
GasPriceOracle.sol: small fix

### PR DESCRIPTION
**Pull request by cutecups**
**Description**

small fixed on the comment.

### CODE REVIEW

**Comment by tynes** [comment]
If you could rebase this and get it to pass the `contracts-bedrock-checks`, that would be great

**Comment by cutecups** [comment]
@tynes Hi I rebased it, but it's hard to find what make the contracts-bedrock-checks fail, I guess maybe I change the comment and the file hash is mismatching with some config? And tips for this?

**Comment by cutecups** [comment]
@tynes Hi Tynes, I think it's good to pass the contracts-bedrock-checks now, the version and hash has been changed to the right.

**Comment by smartcontracts** [comment]
Hi, sorry for the delay here, can you rebase this PR? thank you!

**Comment by cutecups** [comment]
> Hi, sorry for the delay here, can you rebase this PR? thank you!

Sure, done : )

**Review by smartcontracts — APPROVED** [review]

**Comment by smartcontracts** [comment]
Thanks!

**Pull request merged**
