### PR TITLE
ci(Mergify): configuration update

### PR DESCRIPTION
**Pull request by OptimismBot**
This change has been made by @OptimismBot from Mergify config editor.

### CODE REVIEW

**Review by zhwrd — APPROVED** [review]

**Comment by trianglesphere** [comment]
@mergify enqueue

**Comment by trianglesphere** [comment]
@Mergifyio queue

**Comment by trianglesphere** [comment]
@mergify queue

**Comment by donatocayurin** [comment]
❤️🙏

**Pull request merged**
