### PR TITLE
Fix typos in dastate.go

### PR DESCRIPTION
**Pull request by karlb**
Just typo fixes in comments. Since I code with a spell-check turned on, the highlighting gets a bit distracting.

### CODE REVIEW

**Review by tynes — APPROVED** [review]

**Comment by Gmanboy** [comment]
Hi there I think the most of the fix in op-alt-da was fixed in PR #12038 @tynes @karlb

**Review by axelKingsley — APPROVED** [review]

**Comment by tynes** [comment]
This looks like it needs a rebase to pass CI, sorry about that @karlb

**Comment by karlb** [comment]
> This looks like it needs a rebase to pass CI, sorry about that @karlb

No problem, done.

**Comment by tynes** [comment]
Thank you @karlb!

**Pull request merged**
