### PR TITLE
op-chain-ops: Remove inconsistent ownership config fields

### PR DESCRIPTION
**Pull request by mslipper**
Removes inconsistent ownership config fields. The SystemDictator uses `finalSystemOwner`, L2 was still using legacy fields like `l2CrossDomainMessengerOwner`. This PR puts everything on L1 behind `finalSystemOwner`, and everything on L2 behind `proxyAdminOwner`.

### CODE REVIEW

**Comment by mslipper** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #4198** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/4198" target="_blank">Graphite</a> 
    * **PR #4199** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/4199" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/optimism/4199?utm_source=stack-comment).

**Comment by tynes** [comment]
I do not believe this is correct as the `finalOwner` will be a multisig on L1 but we do not control the same account on L2.
See: https://github.com/ethereum-optimism/optimism/blob/de172b11d3597df4c5db03875fc80ada8c9aa103/packages/contracts-bedrock/contracts/deployment/SystemDictator.sol#L372

We can consolidate the L2 `ProxyAdminOwner` and the `L2CrossDomainMessengerOwner` into a single config but it must be different than the L1 `finalOwner`

**Comment by mslipper** [comment]
Ah, nice catch. I combined the L2XDM owner with the ProxyAdminOwner so we can maintain separate ownership fields on L1 and L2.

**Comment by trianglesphere** [comment]
@mslipper you need to update a couple more configs b/c the devnet is failing.

**Comment by mslipper** [comment]
On it.

**Comment by tynes** [comment]
Operationally, I think having the owner of the L2 proxy admin also own the L2xdm makes sense as well as the L1 final owner own the L1xdm

**Comment by tynes** [comment]
```
CRIT [12-04|21:09:21.998] Application failed                       message="invalid deploy config: FinalSystemOwner cannot be address(0)"
```

**Comment by tynes** [comment]
Will approve contingent on devnet passing

**Comment by tynes** [comment]
Something is off with the deploy script

```
Setting ProxyAdmin owner to MSD
Please transfer AddressManager owner to MSD
MSD address: 0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE
```

**Review by protolambda — COMMENTED** [review]
LGTM, but depending on ongoing configuration changes / migration you may want to merge it at your own will rather than mergify.

**Review by tynes — APPROVED** [review]
The naming makes it not clear without greater context but looks good to me

**Comment by tynes** [comment]
Renaming `ProxyAdminOwner` so that it contextually makes sense would be a good addition to this PR but its going to create a lot of churn. It would reduce chances of confusing our future selves as the config name is now misleading. Perhaps `l1FinalSystemOwner` and `l2FinalSystemOwner` or something like that is more appropriate

**Pull request merged**
