### PR TITLE
Backport Granite Mainnet Release to v1.9.0

### PR DESCRIPTION
**Pull request by Inphi**
This PR contains a cherry-picked commit to fix incompatibilities with recent superchain-registry depedency.
The second commit is what you should be more attentive to.

This is based on the op-geth release tag `v1.101315.3-granite-mainnet`, which is itself a backport of the mainnet release onto `v1.101315.3` (refer to this [diff](https://github.com/ethereum-optimism/op-geth/compare/v1.101315.3...v1.101315.3-granite-mainnet?expand=1) for the changes)

### CODE REVIEW

**Comment by ajsutton** [comment]
I take it all the alt-da changes is to preserve compatibility with changes in the superchain-registry?

**Comment by Inphi** [comment]
> I take it all the alt-da changes is to preserve compatibility with changes in the superchain-registry?

caught me updating the PR description to mention this. Yup!

**Review by sebastianst — COMMENTED** [review]
Confirmed that e3c2f046c2d7103c765cbd47e949a284e511a47d sets the correct mainnet activation via SCR and backported op-geth dependency updates.

The other commit is the correct plasma->alt-da renaming backported.

There are a few failing CI tests, I triggered a "rerun from failed" in CCI since their failures were due to some weird timeouts that may just be spurious.

**Comment by sebastianst** [comment]
op-geth devnet tests fail with `Fatal: Failed to register the Ethereum service: incompatible state scheme, stored: path, provided: hash`. I'm confused how this failure can be triggered by the changes done in this PR.

I remember that I've seen this once before in a PR of mine, but then I merged in latest develop and it was fixed. But this is not an option here. I think we can be pragmatic in this case and just completely disable and ignore the devnet tests for this PR, since this is just a backport.

**Comment by Inphi** [comment]
> op-geth devnet tests fail with `Fatal: Failed to register the Ethereum service: incompatible state scheme, stored: path, provided: hash`. I'm confused how this failure can be triggered by the changes done in this PR.
> 
> I remember that I've seen this once before in a PR of mine, but then I merged in latest develop and it was fixed. But this is not an option here. I think we can be pragmatic in this case and just completely disable and ignore the devnet tests for this PR, since this is just a backport.

Yeah, thanks for flagging. I agree that we should ignore the devnet test.

**Review by ajsutton — APPROVED** [review]
LGTM.

**Comment by ajsutton** [comment]
Something in the devnet test is using `latest` rather than a fixed version so old versions broke when the latest upstream geth got merged in. Agreed its safe to ignore that failure.

**Pull request closed without merging**
