### PR TITLE
Fix: make build for Apple Silicon

### LINKED ISSUE #2429: Building Optimistic Ethereum locally fails
**Describe the bug**
Building Optimistic Ethereum locally fails. Building via Docker in the `ops/` directory fails during `RUN yarn install --frozen-lockfile && yarn cache clean`. I am running into the issue at commit `71240b1d9db330232361f2bab7669b95874ea650`, but I can build successfully at commit  `0ac233e73040b372464a9f59a325217254fe8e15`, so I imagine the issue was introduced somewhere in between.

**To Reproduce**
1. Clone repo
2. `yarn build` in root
3. `cd ops`
4. `make build`
6. See error:
``` => ERROR [ethereumoptimism/replica-healthcheck:latest base 13/16] RUN yarn install --frozen-lock  63.2s
------
 > [ethereumoptimism/replica-healthcheck:latest base 13/16] RUN yarn install --frozen-lockfile && yarn cache clean:
#36 0.686 yarn install v1.22.18
#36 0.896 [1/4] Resolving packages...
#36 2.462 [2/4] Fetching packages...
#36 40.50 [3/4] Linking dependencies...
#36 40.50 warning " > @eth-optimism/contracts@0.5.20" has unmet peer dependency "ethers@^5".
#36 40.50 warning " > @eth-optimism/sdk@1.0.4" has unmet peer dependency "ethers@^5".
#36 57.15 [4/4] Building fresh packages...
#36 59.26 warning Error running install script for optional dependency: "/opt/optimism/node_modules/node-hid: Command failed.
#36 59.26 Exit code: 1
#36 59.26 Command: prebuild-install || node-gyp rebuild
#36 59.26 Arguments:
#36 59.26 Directory: /opt/optimism/node_modules/node-hid
#36 59.26 Output:
#36 59.26 prebuild-install WARN install No prebuilt binaries found (target=16.14.2 runtime=node arch=arm64 libc=musl platform=linux)
#36 59.26 gyp info it worked if it ends with ok
#36 59.26 gyp info using node-gyp@7.1.2
#36 59.26 gyp info using node@16.14.2 | linux | arm64
#36 59.26 gyp info find Python using Python version 3.9.5 found at \"/usr/bin/python3\"
#36 59.26 gyp http GET https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
#36 59.26 gyp http 200 https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
#36 59.26 gyp http GET https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
#36 59.26 gyp http 200 https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
#36 59.26 (node:82) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
#36 59.26 (Use `node --trace-deprecation ...` to show where the warning was created)
#36 59.26 gyp info spawn /usr/bin/python3
#36 59.26 gyp info spawn args [
#36 59.26 gyp info spawn args   '/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
#36 59.26 gyp info spawn args   'binding.gyp',
#36 59.26 gyp info spawn args   '-f',
#36 59.26 gyp info spawn args   'make',
#36 59.26 gyp info spawn args   '-I',
#36 59.26 gyp info spawn args   '/opt/optimism/node_modules/node-hid/build/config.gypi',
#36 59.26 gyp info spawn args   '-I',
#36 59.26 gyp info spawn args   '/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
#36 59.26 gyp info spawn args   '-I',
#36 59.26 gyp info spawn args   '/root/.cache/node-gyp/16.14.2/include/node/common.gypi',
#36 59.26 gyp info spawn args   '-Dlibrary=shared_library',
#36 59.26 gyp info spawn args   '-Dvisibility=default',
#36 59.26 gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.14.2',
#36 59.26 gyp info spawn args   '-Dnode_gyp_dir=/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp',
#36 59.26 gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
#36 59.26 gyp info spawn args   '-Dmodule_root_dir=/opt/optimism/node_modules/node-hid',
#36 59.26 gyp info spawn args   '-Dnode_engine=v8',
#36 59.26 gyp info spawn args   '--depth=.',
#36 59.26 gyp info spawn args   '--no-parallel',
#36 59.26 gyp info spawn args   '--generator-output',
#36 59.26 gyp info spawn args   'build',
#36 59.26 gyp info spawn args   '-Goutput_dir=.'
#36 59.26 gyp info spawn args ]
#36 59.26 /bin/sh: pkg-config: not found
#36 59.26 gyp: Call to 'pkg-config libusb-1.0 --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
#36 59.26 gyp ERR! configure error
#36 59.26 gyp ERR! stack Error: `gyp` failed with exit code: 1
#36 59.26 gyp ERR! stack     at ChildProcess.onCpExit (/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/configure.js:351:16)
#36 59.26 gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
#36 59.26 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
#36 59.26 gyp ERR! System Linux 5.10.104-linuxkit
#36 59.26 gyp ERR! command \"/usr/local/bin/node\" \"/opt/optimism/node_modules/.bin/node-gyp\" \"rebuild\"
#36 59.26 gyp ERR! cwd /opt/optimism/node_modules/node-hid
#36 59.26 gyp ERR! node -v v16.14.2
#36 59.26 gyp ERR! node-gyp -v v7.1.2
#36 59.26 gyp ERR! not ok"
#36 59.26 info This module is OPTIONAL, you can safely ignore this error
#36 59.27 info This module is OPTIONAL, you can safely ignore this error
#36 59.27 warning Error running install script for optional dependency: "/opt/optimism/node_modules/@ledgerhq/hw-transport-node-hid-noevents/node_modules/node-hid: Command failed.
#36 59.27 Exit code: 1
#36 59.27 Command: prebuild-install --runtime napi || node-gyp rebuild
#36 59.27 Arguments:
#36 59.27 Directory: /opt/optimism/node_modules/@ledgerhq/hw-transport-node-hid-noevents/node_modules/node-hid
#36 59.27 Output:
#36 59.27 prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=arm64 libc=musl platform=linux)
#36 59.27 gyp info it worked if it ends with ok
#36 59.27 gyp info using node-gyp@7.1.2
#36 59.27 gyp info using node@16.14.2 | linux | arm64
#36 59.27 gyp info find Python using Python version 3.9.5 found at \"/usr/bin/python3\"
#36 59.27 gyp http GET https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
#36 59.27 gyp http 200 https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
#36 59.27 gyp http GET https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
#36 59.27 gyp http 200 https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
#36 59.27 (node:72) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
#36 59.27 (Use `node --trace-deprecation ...` to show where the warning was created)
#36 59.27 gyp info spawn /usr/bin/python3
#36 59.27 gyp info spawn args [
#36 59.27 gyp info spawn args   '/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
#36 59.27 gyp info spawn args   'binding.gyp',
#36 59.27 gyp info spawn args   '-f',
#36 59.27 gyp info spawn args   'make',
#36 59.27 gyp info spawn args   '-I',
#36 59.27 gyp info spawn args   '/opt/optimism/node_modules/@ledgerhq/hw-transport-node-hid-noevents/node_modules/node-hid/build/config.gypi',
#36 59.27 gyp info spawn args   '-I',
#36 59.27 gyp info spawn args   '/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
#36 59.27 gyp info spawn args   '-I',
#36 59.27 gyp info spawn args   '/root/.cache/node-gyp/16.14.2/include/node/common.gypi',
#36 59.27 gyp info spawn args   '-Dlibrary=shared_library',
#36 59.27 gyp info spawn args   '-Dvisibility=default',
#36 59.27 gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.14.2',
#36 59.27 gyp info spawn args   '-Dnode_gyp_dir=/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp',
#36 59.27 gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
#36 59.27 gyp info spawn args   '-Dmodule_root_dir=/opt/optimism/node_modules/@ledgerhq/hw-transport-node-hid-noevents/node_modules/node-hid',
#36 59.27 gyp info spawn args   '-Dnode_engine=v8',
#36 59.27 gyp info spawn args   '--depth=.',
#36 59.27 gyp info spawn args   '--no-parallel',
#36 59.27 gyp info spawn args   '--generator-output',
#36 59.27 gyp info spawn args   'build',
#36 59.27 gyp info spawn args   '-Goutput_dir=.'
#36 59.27 gyp info spawn args ]
#36 59.27 /bin/sh: pkg-config: not found
#36 59.27 gyp: Call to 'pkg-config libusb-1.0 --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
#36 59.27 gyp ERR! configure error
#36 59.27 gyp ERR! stack Error: `gyp` failed with exit code: 1
#36 59.27 gyp ERR! stack     at ChildProcess.onCpExit (/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/configure.js:351:16)
#36 59.27 gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
#36 59.27 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
#36 59.27 gyp ERR! System Linux 5.10.104-linuxkit
#36 59.27 gyp ERR! command \"/usr/local/bin/node\" \"/opt/optimism/node_modules/.bin/node-gyp\" \"rebuild\"
#36 59.27 gyp ERR! cwd /opt/optimism/node_modules/@ledgerhq/hw-transport-node-hid-noevents/node_modules/node-hid
#36 59.27 gyp ERR! node -v v16.14.2
#36 59.27 gyp ERR! node-gyp -v v7.1.2
#36 59.27 gyp ERR! not ok"
#36 60.29 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#36 60.29 error /opt/optimism/node_modules/bufferutil: Command failed.
#36 60.29 Exit code: 1
#36 60.29 Command: node-gyp-build
#36 60.29 Arguments:
#36 60.29 Directory: /opt/optimism/node_modules/bufferutil
#36 60.29 Output:
#36 60.29 gyp info it worked if it ends with ok
#36 60.29 gyp info using node-gyp@7.1.2
#36 60.29 gyp info using node@16.14.2 | linux | arm64
#36 60.29 gyp info find Python using Python version 3.9.5 found at "/usr/bin/python3"
#36 60.29 (node:367) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
#36 60.29 (Use `node --trace-deprecation ...` to show where the warning was created)
#36 60.29 gyp info spawn /usr/bin/python3
#36 60.29 gyp info spawn args [
#36 60.29 gyp info spawn args   '/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
#36 60.29 gyp info spawn args   'binding.gyp',
#36 60.29 gyp info spawn args   '-f',
#36 60.29 gyp info spawn args   'make',
#36 60.29 gyp info spawn args   '-I',
#36 60.29 gyp info spawn args   '/opt/optimism/node_modules/bufferutil/build/config.gypi',
#36 60.29 gyp info spawn args   '-I',
#36 60.29 gyp info spawn args   '/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
#36 60.29 gyp info spawn args   '-I',
#36 60.29 gyp info spawn args   '/root/.cache/node-gyp/16.14.2/include/node/common.gypi',
#36 60.29 gyp info spawn args   '-Dlibrary=shared_library',
#36 60.29 gyp info spawn args   '-Dvisibility=default',
#36 60.29 gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.14.2',
#36 60.29 gyp info spawn args   '-Dnode_gyp_dir=/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp',
#36 60.29 gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
#36 60.29 gyp info spawn args   '-Dmodule_root_dir=/opt/optimism/node_modules/bufferutil',
#36 60.29 gyp info spawn args   '-Dnode_engine=v8',
#36 60.29 gyp info spawn args   '--depth=.',
#36 60.29 gyp info spawn args   '--no-parallel',
#36 60.29 gyp info spawn args   '--generator-output',
#36 60.29 gyp info spawn args   'build',
#36 60.29 gyp info spawn args   '-Goutput_dir=.'
#36 60.29 gyp info spawn args ]
#36 60.29 gyp info spawn make
#36 60.29 gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
#36 60.29 make: Entering directory '/opt/optimism/node_modules/bufferutil/build'
#36 60.29   CC(target) Release/obj.target/bufferutil/src/bufferutil.o
#36 60.29   SOLINK_MODULE(target) Release/obj.target/bufferutil.node
#36 60.29 make: g++: No such file or directory
#36 60.29 make: *** [bufferutil.target.mk:137: Release/obj.target/bufferutil.node] Error 127
#36 60.29 make: Leaving directory '/opt/optimism/node_modules/bufferutil/build'
#36 60.29 gyp ERR! build error
#36 60.29 gyp ERR! stack Error: `make` failed with exit code: 2
#36 60.29 gyp ERR! stack     at ChildProcess.onExit (/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/build.js:194:23)
#36 60.29 gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
#36 60.29 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
#36 60.29 gyp ERR! System Linux 5.10.104-linuxkit
#36 60.29 gyp ERR! command "/usr/local/bin/node" "/opt/optimism/node_modules/.bin/node-gyp" "rebuild"
#36 60.29 gyp ERR! cwd /opt/optimism/node_modules/bufferutil
#36 60.29 gyp ERR! node -v v16.14.2
#36 60.29 gyp ERR! node-gyp -v v7.1.2
#36 60.29 gyp ERR! not ok
#36 60.98 warning Error running install script for optional dependency: "/opt/optimism/node_modules/usb: Command failed.
#36 60.98 Exit code: 1
#36 60.98 Command: prebuild-install --runtime napi --target 4 --verbose || node-gyp rebuild
#36 60.98 Arguments:
#36 60.98 Directory: /opt/optimism/node_modules/usb
#36 60.98 Output:
#36 60.98 prebuild-install info begin Prebuild-install version 5.3.6
#36 60.98 prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/ab1e1c-usb-v1.7.1-napi-v4-linuxmusl-arm64.tar.gz
#36 60.98 prebuild-install http request GET https://github.com/tessel/node-usb/releases/download/v1.7.1/usb-v1.7.1-napi-v4-linuxmusl-arm64.tar.gz
#36 60.98 prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.7.1/usb-v1.7.1-napi-v4-linuxmusl-arm64.tar.gz
#36 60.98 prebuild-install WARN install No prebuilt binaries found (target=4 runtime=napi arch=arm64 libc=musl platform=linux)
#36 60.98 gyp info it worked if it ends with ok
#36 60.98 gyp info using node-gyp@7.1.2
#36 60.98 gyp info using node@16.14.2 | linux | arm64
#36 60.98 gyp info find Python using Python version 3.9.5 found at \"/usr/bin/python3\"
#36 60.98 gyp http GET https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
#36 60.98 gyp http 200 https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
#36 60.98 gyp http GET https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
#36 60.98 gyp http 200 https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
#36 60.98 (node:50) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
#36 60.98 (Use `node --trace-deprecation ...` to show where the warning was created)
#36 60.98 gyp info spawn /usr/bin/python3
#36 60.98 gyp info spawn args [
#36 60.98 gyp info spawn args   '/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
#36 60.98 gyp info spawn args   'binding.gyp',
#36 60.98 gyp info spawn args   '-f',
#36 60.98 gyp info spawn args   'make',
#36 60.98 gyp info spawn args   '-I',
#36 60.98 gyp info spawn args   '/opt/optimism/node_modules/usb/build/config.gypi',
#36 60.98 gyp info spawn args   '-I',
#36 60.98 gyp info spawn args   '/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
#36 60.98 gyp info spawn args   '-I',
#36 60.98 gyp info spawn args   '/root/.cache/node-gyp/16.14.2/include/node/common.gypi',
#36 60.98 gyp info spawn args   '-Dlibrary=shared_library',
#36 60.98 gyp info spawn args   '-Dvisibility=default',
#36 60.98 gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.14.2',
#36 60.98 gyp info spawn args   '-Dnode_gyp_dir=/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp',
#36 60.98 gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
#36 60.98 gyp info spawn args   '-Dmodule_root_dir=/opt/optimism/node_modules/usb',
#36 60.98 gyp info spawn args   '-Dnode_engine=v8',
#36 60.98 gyp info spawn args   '--depth=.',
#36 60.98 gyp info spawn args   '--no-parallel',
#36 60.98 gyp info spawn args   '--generator-output',
#36 60.98 gyp info spawn args   'build',
#36 60.98 gyp info spawn args   '-Goutput_dir=.'
#36 60.98 gyp info spawn args ]
#36 60.98 gyp info spawn make
#36 60.98 gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
#36 60.98 make: Entering directory '/opt/optimism/node_modules/usb/build'
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/core.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/io.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
#36 60.98   CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
#36 60.98 ../libusb/libusb/os/linux_udev.c:40:10: fatal error: libudev.h: No such file or directory
#36 60.98    40 | #include <libudev.h>
#36 60.98       |          ^~~~~~~~~~~
#36 60.98 compilation terminated.
#36 60.98 make: *** [libusb.target.mk:150: Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
#36 60.98 make: Leaving directory '/opt/optimism/node_modules/usb/build'
#36 60.98 gyp ERR! build error
#36 60.98 gyp ERR! stack Error: `make` failed with exit code: 2
#36 60.98 gyp ERR! stack     at ChildProcess.onExit (/opt/optimism/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/build.js:194:23)
#36 60.98 gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
#36 60.98 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
#36 60.98 gyp ERR! System Linux 5.10.104-linuxkit
#36 60.98 gyp ERR! command \"/usr/local/bin/node\" \"/opt/optimism/node_modules/.bin/node-gyp\" \"rebuild\"
#36 60.98 gyp ERR! cwd /opt/optimism/node_modules/usb
#36 60.98 gyp ERR! node -v v16.14.2
#36 60.98 gyp ERR! node-gyp -v v7.1.2
#36 60.98 gyp ERR! not ok"
#36 60.98 info This module is OPTIONAL, you can safely ignore this error
------
failed to solve: executor failed running [/bin/sh -c yarn install --frozen-lockfile && yarn cache clean]: exit code: 1
```

**Expected behavior**
Build successfully.

**Screenshots**

**System Specs:**
 - OS: macOS, Apple Silicon
 - Package Version (or commit hash): 71240b1d9db330232361f2bab7669b95874ea650

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by DanieleSalatti**
**Description**
Fixing the build process on Mac with Apple Silicon.

**Additional context**
Building on M1 macs fails because of missing dependencies.

**Metadata**
- Fixes #2429

### CODE REVIEW

**Comment by tynes** [comment]
Does anybody have an m1 to test this out?

**Comment by tuxcanfly** [comment]
This fixes the issue with yarn install. But there's something else that's failing and I'm not sure if it's just me 😕 

```
 => ERROR [base 17/17] RUN yarn build                                                                                                                                                                  17.9s
------
 > [base 17/17] RUN yarn build:
#21 0.782 yarn run v1.22.18
#21 0.812 $ yarn lerna run build
#21 1.043 $ /opt/optimism/node_modules/.bin/lerna run build
#21 1.454 lerna notice cli v4.0.0
#21 1.456 lerna info versioning independent
#21 1.504 lerna info Executing command in 9 packages: "yarn run build"
#21 6.684 lerna info run Ran npm script 'build' in '@eth-optimism/core-utils' in 5.2s:
#21 6.684 $ tsc -p tsconfig.build.json
#21 12.11 lerna info run Ran npm script 'build' in '@eth-optimism/common-ts' in 5.4s:
#21 12.11 $ tsc -p tsconfig.build.json
#21 17.00 lerna ERR! yarn run build exited 2 in '@eth-optimism/replica-healthcheck'
#21 17.00 lerna ERR! yarn run build stdout:
#21 17.00 $ tsc -p tsconfig.build.json
#21 17.00 src/service.ts(3,3): error TS2724: '"@eth-optimism/common-ts"' has no exported member named 'BaseServiceV2'. Did you mean 'BaseService'?
#21 17.00 src/service.ts(4,3): error TS2305: Module '"@eth-optimism/common-ts"' has no exported member 'Counter'.
#21 17.00 src/service.ts(5,3): error TS2305: Module '"@eth-optimism/common-ts"' has no exported member 'Gauge'.
#21 17.00 src/service.ts(6,3): error TS2305: Module '"@eth-optimism/common-ts"' has no exported member 'validators'.
#21 17.00 src/service.ts(90,33): error TS2339: Property 'options' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(93,14): error TS2339: Property 'logger' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(94,14): error TS2339: Property 'metrics' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(104,36): error TS2339: Property 'options' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(109,14): error TS2339: Property 'logger' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(110,14): error TS2339: Property 'metrics' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(122,10): error TS2339: Property 'metrics' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(123,10): error TS2339: Property 'metrics' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(124,10): error TS2339: Property 'metrics' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(126,10): error TS2339: Property 'logger' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(133,34): error TS2339: Property 'options' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(136,12): error TS2339: Property 'logger' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(142,31): error TS2339: Property 'options' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(145,12): error TS2339: Property 'logger' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(156,12): error TS2339: Property 'logger' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(164,12): error TS2339: Property 'logger' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(170,14): error TS2339: Property 'logger' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(171,35): error TS2339: Property 'options' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(172,35): error TS2339: Property 'options' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(181,12): error TS2339: Property 'logger' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(182,12): error TS2339: Property 'metrics' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(183,12): error TS2339: Property 'metrics' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(189,24): error TS2339: Property 'options' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(193,10): error TS2339: Property 'logger' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(198,10): error TS2339: Property 'metrics' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(199,10): error TS2339: Property 'metrics' does not exist on type 'HealthcheckService'.
#21 17.00 src/service.ts(205,11): error TS2339: Property 'run' does not exist on type 'HealthcheckService'.
#21 17.00 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#21 17.00 lerna ERR! yarn run build stderr:
#21 17.00 error Command failed with exit code 2.
#21 17.00 lerna ERR! yarn run build exited 2 in '@eth-optimism/replica-healthcheck'
#21 17.00 lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
#21 17.21 error Command failed with exit code 2.
#21 17.21 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#21 17.39 error Command failed with exit code 2.
#21 17.39 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c yarn build]: exit code: 2
ERROR: Service 'deployer' failed to build : Build failed
```

**Comment by DanieleSalatti** [comment]
@tuxcanfly I did not get that one.

Which commit are you on? I can take a look.

**Comment by tuxcanfly** [comment]
@DanieleSalatti I think it's something silly like outdated dependencies on my local.

@smartcontracts Any idea why this happens? I think I have a pretty clean build and I'm trying to `yarn build` in the `replica-healthcheck` package but seeing this:


```
yarn run v1.22.18
$ tsc -p tsconfig.build.json
src/service.ts:3:3 - error TS2724: '"@eth-optimism/common-ts"' has no exported member named 'BaseServiceV2'. Did you mean 'BaseService'?

3   BaseServiceV2,
    ~~~~~~~~~~~~~

  ../common-ts/dist/base-service.d.ts:13:22
    13 export declare class BaseService<T> {
                            ~~~~~~~~~~~
    'BaseService' is declared here.

src/service.ts:4:3 - error TS2305: Module '"@eth-optimism/common-ts"' has no exported member 'Counter'.
```

**Review by Inphi — COMMENTED** [review]
Looks good. The `build-base` package already contains the libev headers, so you can remove the `evdev-dev` dep.

**Comment by tuxcanfly** [comment]
@smartcontracts That worked! Sorry for holding up this PR, it was probably unrelated.

**Comment by DanieleSalatti** [comment]
> Looks good. The `build-base` package already contains the libev headers, so you can remove the `evdev-dev` dep.

Done :)

**Comment by DanieleSalatti** [comment]
Merging from `development`

**Comment by DanieleSalatti** [comment]
@tuxcanfly @Inphi - quick ping for approval :)

**Review by Inphi — APPROVED** [review]
thanks!

**Pull request merged**
