### PR TITLE
fix[batch-submitter]: add same-address error

### LINKED ISSUE #1072: Warn or throw an error when sequencer and proposer addresses are the same
When the batch submitter submits tx batches and state root batches, it might have the nonce error.
The problem is cause by running the two submitters at the same time, so both submitters might use the same nonce to submit the batches.
https://github.com/ethereum-optimism/optimism/blob/85362d44fc13966f00bee26172dd04e6a442a6c6/packages/batch-submitter/src/exec/run-batch-submitter.ts#L457-L462

### PR DESCRIPTION
**Pull request by 0xYYY**
**Description**
Add a warning when proposer and sequencer have the same address.

**Metadata**
- Fixes #1072.

### CODE REVIEW

**Comment by smartcontracts** [comment]
Actually, could you make this throw an error instead of a warning? Fantastic work btw, thank you!

**Comment by tynes** [comment]
Be sure to squash the commits into a single commit

**Comment by 0xYYY** [comment]
No problem, I'll change it to throw an Error. And also squash the commits.

**Comment by 0xYYY** [comment]
It seems like the failed tests are those doing L2 => L1 actions.

I'm guessing the reason is that the `batch_submitter` service failed to start because of our modification, plus that `PROPOSER_PRIVATE_KEY` isn't specified in `ops/docker-compose.yml`.

https://github.com/ethereum-optimism/optimism/blob/c17a73bf8f9baea1380e2201293b70d396211dcc/ops/docker-compose.yml#L116-L132

I can modify the docker files so that sequencer and proposer use different addresses. Sounds reasonable?

**Comment by smartcontracts** [comment]
Great catch @0xYYY. Running CI again...

**Comment by smartcontracts** [comment]
@0xYYY Could you just rebase this on top of the latest develop? Should be good to go once that's done. Thank you!

**Comment by 0xYYY** [comment]
@smartcontracts I have rebased this to the latest `develop`.

**Comment by 0xYYY** [comment]
@smartcontracts rebased to the latest `develop` again. Should be goold to go after this CI?

**Review by smartcontracts — APPROVED** [review]

**Comment by smartcontracts** [comment]
Thank you!

**Comment by smartcontracts** [comment]
Send me an ETH address and I'll send you a hand-drawn contributor NFT :-)

**Comment by 0xYYY** [comment]
Thanks for the guidance on my first PR to Optimism!
I'll send you an email to claim the NFT. :)

**Pull request merged**
