### PR TITLE
contracts-bedrock: extend the l1block contract to store historical block hash data

### PR DESCRIPTION
**Pull request by vladimir-trifonov**
**Description**

Extend the L1Block contract-bedrock to store L1 historical block hash data.

**Tests**

Added additional L1Block contract tests and RingLib tests.

**Additional context**

https://gov.optimism.io/t/final-extend-the-l1block-contract-to-store-historical-block-hash-data/6103

### CODE REVIEW

**Comment by vladimir-trifonov** [comment]
Hi @roninjin10, can you suggest who can help with the failing ci/circleci jobs because it's not clear what could be done?

**Comment by roninjin10** [comment]
@vladimir-trifonov I can help tomorrow. Why is this pointing at ethereum-optimism:release/v1.1.3 branch?

**Comment by vladimir-trifonov** [comment]
@roninjin10 Cool, thanks... We read that changes to contracts-bedrock should be made against a release candidate branch:
https://github.com/ethereum-optimism/optimism/blob/develop/README.md#development-branch

**Comment by vladimir-trifonov** [comment]
@roninjin10 Should we change it to point to `develop` instead?

**Comment by roninjin10** [comment]
@vladimir-trifonov ah ok didnt realize we were using release canidate branches

The circle ci failures are docker publishes that are not allowed to run by outside contributors. This is expected. Your run looks good otherwise.

```
op-heartbeat-docker-publish - Failed
[fuzz-op-chain-ops](https://circleci.com/gh/ethereum-optimism/optimism/1159391?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[check-generated-mocks-op-service](https://circleci.com/gh/ethereum-optimism/optimism/1159385?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[devnet (with deployed contracts)](https://circleci.com/gh/ethereum-optimism/optimism/1159378?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[contracts-bedrock-slither](https://circleci.com/gh/ethereum-optimism/optimism/1159371?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-service-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159365?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-e2e-HTTP-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159414?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
op-batcher-docker-publish - Failed
[op-proposer-lint](https://circleci.com/gh/ethereum-optimism/optimism/1159406?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[proxyd-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159401?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[semgrep-scan](https://circleci.com/gh/ethereum-optimism/optimism/1159395?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-node-docker-build](https://circleci.com/gh/ethereum-optimism/optimism/1159389?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-e2e-WS-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159382?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-bindings-lint](https://circleci.com/gh/ethereum-optimism/optimism/1159375?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[fuzz-op-node](https://circleci.com/gh/ethereum-optimism/optimism/1159369?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-node-lint](https://circleci.com/gh/ethereum-optimism/optimism/1159364?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-heartbeat tests](https://circleci.com/gh/ethereum-optimism/optimism/1159415?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-bindings-build](https://circleci.com/gh/ethereum-optimism/optimism/1159413?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[cannon-build-test-vectors](https://circleci.com/gh/ethereum-optimism/optimism/1159408?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-heartbeat-docker-build](https://circleci.com/gh/ethereum-optimism/optimism/1159402?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-service-lint](https://circleci.com/gh/ethereum-optimism/optimism/1159396?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[pnpm-monorepo](https://circleci.com/gh/ethereum-optimism/optimism/1159390?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[sdk-next-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159427?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[sdk-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159426?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[core-utils-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159425?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[common-ts-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159424?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[chain-mon-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159423?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[contracts-bedrock-checks](https://circleci.com/gh/ethereum-optimism/optimism/1159422?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-wheel-lint](https://circleci.com/gh/ethereum-optimism/optimism/1159383?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-batcher-docker-build](https://circleci.com/gh/ethereum-optimism/optimism/1159379?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[depcheck](https://circleci.com/gh/ethereum-optimism/optimism/1159421?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-program-docker-build](https://circleci.com/gh/ethereum-optimism/optimism/1159370?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-proposer-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159363?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
chain-mon-docker-publish - Failed
[contracts-bedrock-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159405?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[bedrock-markdown](https://circleci.com/gh/ethereum-optimism/optimism/1159398?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-proposer-docker-build](https://circleci.com/gh/ethereum-optimism/optimism/1159393?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-node-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159387?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[devnet (with genesis contracts)](https://circleci.com/gh/ethereum-optimism/optimism/1159380?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
op-challenger-docker-publish - Failed
op-proposer-docker-publish - Failed
[op-program-lint](https://circleci.com/gh/ethereum-optimism/optimism/1159368?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[fuzz-cannon](https://circleci.com/gh/ethereum-optimism/optimism/1159362?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-bootnode-lint](https://circleci.com/gh/ethereum-optimism/optimism/1159411?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[contracts-ts-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159420?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-program-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159407?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[cannon-go-lint-and-test](https://circleci.com/gh/ethereum-optimism/optimism/1159403?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
indexer-docker-publish - Failed
[check-generated-mocks-op-node](https://circleci.com/gh/ethereum-optimism/optimism/1159394?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[indexer-docker-build](https://circleci.com/gh/ethereum-optimism/optimism/1159388?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-batcher-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159381?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[contracts-bedrock-coverage](https://circleci.com/gh/ethereum-optimism/optimism/1159373?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-challenger-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159367?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-bindings-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159361?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-batcher-lint](https://circleci.com/gh/ethereum-optimism/optimism/1159409?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-chain-ops-lint](https://circleci.com/gh/ethereum-optimism/optimism/1159404?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[go-mod-tidy](https://circleci.com/gh/ethereum-optimism/optimism/1159397?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-challenger-docker-build](https://circleci.com/gh/ethereum-optimism/optimism/1159392?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[hive-test-rpc](https://circleci.com/gh/ethereum-optimism/optimism/1159416?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[hive-test-l1ops](https://circleci.com/gh/ethereum-optimism/optimism/1159418?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[hive-test-p2p](https://circleci.com/gh/ethereum-optimism/optimism/1159417?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[indexer-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159386?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[contracts-bedrock-validate-spaces](https://circleci.com/gh/ethereum-optimism/optimism/1159419?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
op-program-docker-publish - Failed
[op-chain-ops-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159376?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-challenger-lint](https://circleci.com/gh/ethereum-optimism/optimism/1159372?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[op-e2e-lint](https://circleci.com/gh/ethereum-optimism/optimism/1159366?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
[bedrock-go-tests](https://circleci.com/gh/ethereum-optimism/optimism/1159428?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) - Success
op-node-docker-publish - Failed
```

**Comment by Daniel-K-Ivanov** [comment]
@roninjin10 thank you for the confirmation.
@tynes can you review the PR so that we can wrap this item? The changes are exactly the same as the already reviewed ones by you.

**Comment by tynes** [comment]
Do you mind basing this on develop instead of the rc branch? We need to update our contributing docs because we have not been following the rc flow

**Comment by vladimir-trifonov** [comment]
@tynes of course... it's done

**Review by refcell — APPROVED** [review]

**Comment by vladimir-trifonov** [comment]
@mergifyio requeue

**Comment by vladimir-trifonov** [comment]
@mergifyio requeue

**Comment by Perseverance** [comment]
@mergifyio requeue

**Comment by vladimir-trifonov** [comment]
@mergifyio requeue

**Comment by Perseverance** [comment]
@refcell can you please merge or requeue for merging 🙏

**Comment by vladimir-trifonov** [comment]
I added a line to ignore packages/contracts-bedrock/src/libraries/RingLib.sol from the contracts-bedrock code coverage because it is not calculated correctly atm by the coverage tool

**Comment by vladimir-trifonov** [comment]
re: unstale

**Pull request closed without merging**
