### PR TITLE
fix: typo in the code comments

### PR DESCRIPTION
**Pull request by threewebcode**
**Description**

There is typo in the code comment and use this change to correct it.

### CODE REVIEW

**Comment by threewebcode** [comment]
@ajsutton @tynes  Please help review.

**Review by trianglesphere — APPROVED** [review]

**Comment by trianglesphere** [comment]
@threewebcode the skip CI part seemed to cause an issue. We never skip CI in this repo

**Comment by threewebcode** [comment]
> @threewebcode the skip CI part seemed to cause an issue. We never skip CI in this repo

Got it and follow this rule from now on.

**Comment by trianglesphere** [comment]
@threewebcode specifically to merge this PR, you need to modify the commit to remove `[skip CI]` from the subject line or add a new commit on top

**Comment by threewebcode** [comment]
> @threewebcode specifically to merge this PR, you need to modify the commit to remove `[skip CI]` from the subject line or add a new commit on top

Done

**Comment by ultratwo** [comment]
typo farmer. please do not merge.

**Comment by threewebcode** [comment]
> typo farmer. please do not merge.

Currently, I use OP as l2 solution for customization project.

**Comment by threewebcode** [comment]
> > typo farmer. please do not merge.
> 
> Currently, I use OP as l2 solution for customization project.

As private deployment, i adopt my own bridge to replace standard bridge. Moreover, I also modify op-geth for allocation.  There are more upcoming changes like ZK fraud proof and cross-chain integration.

**Review by tynes — APPROVED** [review]

**Pull request merged**
