### PR TITLE
Update `foundry` & `forge-std`

### PR DESCRIPTION
**Pull request by clabby**
# Overview

Updates:
- `foundry` to `edf15abd648bb96e2bcee342c1d72ec7d1066cd1`
- `forge-std` to `v1.4.0` (`a2edd39db95df7e9dd3f9ef9edc8c55fefddb6df`)

**Metadata**
Closes CLI-3369

### CODE REVIEW

**Comment by clabby** [comment]
Current dependencies on/for this PR:
* develop
  * **PR #4929** <a href="https://app.graphite.dev/github/pr/ethereum-optimism/optimism/4929" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/ethereum-optimism/optimism/4929?utm_source=stack-comment).

**Comment by clabby** [comment]
Good to review, but do not merge just yet, making sure [this error](https://app.circleci.com/pipelines/github/ethereum-optimism/optimism/13983/workflows/5ec9de7d-1883-42e4-9943-49f4e887ceec/jobs/461608?invite=true#step-107-30) is insignificant. Foundry's invariant fuzzer uses compilation artifacts for discovery, and when targeting a specific selector, checks the artifact of the contract for it. Because `Proxy.sol` has none of the selectors we're looking for, this error is thrown.

**Comment by tynes** [comment]
Ah interesting, so its not possible to be configurable with proxied contracts with foundry?

**Comment by tynes** [comment]
Looks like tests are passing now, but needs a rebase

**Review by tynes — APPROVED** [review]
I rebased this, should be good to merge

**Review by mslipper — APPROVED** [review]

**Comment by clabby** [comment]
@mergifyio refresh

**Comment by tynes** [comment]
@Mergifyio refresh

**Pull request merged**
