### PR TITLE
fix: typo

### PR DESCRIPTION
**Pull request by pengin7384**
**Description**

Rename 'ResetableStage' to 'ResettableStage'

**Tests**

None

**Additional context**

None

**Metadata**

None

### CODE REVIEW

**Review by trianglesphere — APPROVED** [review]
TYVM

**Comment by trianglesphere** [comment]
@pengin7384 please merge in develop to make CI pass

**Comment by pengin7384** [comment]
@trianglesphere I pushed the changeset file to merge, but It didn't automatically merged.
It seems to be related with `op-bindings-build` job failure, but I successfully built in my environment.
Could I get some help?

**Comment by pengin7384** [comment]
Sorry. I went the wrong way. 😭

**Pull request merged**
