### PR TITLE
op-chain-ops: legacy withdrawal script refactoring

### PR DESCRIPTION
**Pull request by tynes**
**Description**

Clean up the script that is used to migrate legacy withdrawals.
This script is very important for testing the legacy withdrawal
migration.

A bug was introduced with #4911
which was a sherlock audit fix. This was a bug because the change
resulted in the withdrawal hashes changing, meaning that the storage
slots computed client side also changed. This resulted in breaking the
script. This commit reverts this change. The changes landing in
#5470 will cause the
buffer in the gas limit for the  migrated withdrawals to be too small,
so we can reintroduce this code behind a switch with the network.
Its not ideal that the migration code isn't going to match 1:1
with goerli but thats ok because we will be able to thoroughly
test it.

### CODE REVIEW

**Comment by tynes** [comment]
If these fixes are merged and then https://github.com/ethereum-optimism/optimism/pull/5459 is rebased on top of this, it should fix @roninjin10's issue. Will need to actually see it work but feeling pretty sure that the combo of these fixes will work

**Comment by roninjin10** [comment]
Amazing!

**Comment by mslipper** [comment]
Is this a pure revert, or was additional functionality introduced?

**Comment by tynes** [comment]
> Is this a pure revert, or was additional functionality introduced?

I left in the unit tests and modularization that enabled the unit tests but the underlying functionally was reverted

**Review by mslipper — APPROVED** [review]

**Comment by tynes** [comment]
Can I get a review from @ethereum-optimism/ecopod ?

**Review by roninjin10 — APPROVED** [review]

**Pull request merged**
